#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef AIBUDSAUDIO_SWIFT_H
#define AIBUDSAUDIO_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreAudioTypes;
@import CoreML;
@import CoreMedia;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsAudio",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// The main entry point for the AIBudsAudioSDK.
/// Use this class to access SDK version information and other global SDK-level functionality.
SWIFT_CLASS("_TtC11AIBudsAudio14AIBudsAudioSDK")
@interface AIBudsAudioSDK : NSObject
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of AIBudsAudioSDK
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The version number of the SDK
///
/// returns:
/// A string representing the current SDK version (e.g. “1.0.0-beta.1”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// The build number of the SDK
///
/// returns:
/// A string representing the SDK build number (e.g. “20250315001”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkBuild;)
+ (NSString * _Nonnull)sdkBuild SWIFT_WARN_UNUSED_RESULT;
/// The release date of the SDK
///
/// returns:
/// A string representing the SDK release date in YYYY-MM-DD format
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkReleaseDate;)
+ (NSString * _Nonnull)sdkReleaseDate SWIFT_WARN_UNUSED_RESULT;
/// Returns a formatted string containing SDK version information
/// note:
/// The returned string includes an emoji prefix and is formatted for easy reading
///
/// returns:
/// A string containing the SDK name, version, build number and release date
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersionDescription;)
+ (NSString * _Nonnull)sdkVersionDescription SWIFT_WARN_UNUSED_RESULT;
@end

@interface AIBudsAudioSDK (SWIFT_EXTENSION(AIBudsAudio))
/// Error domain for streaming voice player errors in AIBudsAudioSDK
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull StreamingVoicePlayerErrorDomain;)
+ (NSString * _Nonnull)StreamingVoicePlayerErrorDomain SWIFT_WARN_UNUSED_RESULT;
@end

@class AIBudsTenVadResult;
/// TEN Voice Activity Detection (VAD)
SWIFT_CLASS("_TtC11AIBudsAudio12AIBudsTenVad")
@interface AIBudsTenVad : NSObject
/// Initialize TEN VAD instance
/// \param hopSize Number of samples per frame (160 = 10ms, 256 = 16ms at 16kHz)
///
/// \param threshold Voice detection threshold (0.0 - 1.0, default 0.5)
///
- (nullable instancetype)initWithHopSize:(NSInteger)hopSize threshold:(float)threshold OBJC_DESIGNATED_INITIALIZER;
/// Process a single audio frame for voice activity detection
/// \param frame Array of Int16 samples (must match hopSize)
///
///
/// returns:
/// VADResult with probability and speech flag, or nil on error
- (AIBudsTenVadResult * _Nullable)processWithFrame:(NSArray<NSNumber *> * _Nonnull)frame SWIFT_WARN_UNUSED_RESULT;
/// Process multiple frames at once
/// \param samples Array of Int16 samples (will be split into frames)
///
///
/// returns:
/// Array of VADResult for each complete frame
- (NSArray<AIBudsTenVadResult *> * _Nonnull)processBufferWithSamples:(NSArray<NSNumber *> * _Nonnull)samples SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AIBudsVadConfig;
@class NSError;
@class AVAudioPCMBuffer;
@class AIBudsVadResult;
/// Voice Activity Detection (VAD)
SWIFT_CLASS("_TtC11AIBudsAudio9AIBudsVad")
@interface AIBudsVad : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isAvailable;)
+ (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of AIBudsVad
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)start:(AIBudsVadConfig * _Nonnull)config completion:(void (^ _Nullable)(BOOL, NSTimeInterval, NSError * _Nullable))completion;
/// Process an entire in-memory audio buffer.
/// Automatically converts the buffer to 16kHz mono Float32 and processes in 4096-sample chunks (256ms).
/// \code
/// let buffer: AVAudioPCMBuffer = ...
/// let manager = try await VadManager()
/// let results = try await manager.process(buffer)
///
/// \endcode\param audioBuffer Source buffer in any format
///
///
/// returns:
/// Array of per-chunk VAD results
+ (void)process:(AVAudioPCMBuffer * _Nonnull)audioBuffer completionHandler:(void (^ _Nonnull)(NSArray<AIBudsVadResult *> * _Nullable, NSError * _Nullable))completionHandler;
@end

@class AIBudsVadStreamState;
@class AIBudsVadSegmentationConfig;
@class AIBudsVadStreamResult;
@interface AIBudsVad (SWIFT_EXTENSION(AIBudsAudio))
+ (AIBudsVadStreamState * _Nonnull)makeStreamState SWIFT_WARN_UNUSED_RESULT;
/// Process a streaming chunk and emit start/end events using Silero-style hysteresis.
+ (BOOL)processStreamingChunk:(NSArray<NSNumber *> * _Nonnull)audioChunk state:(AIBudsVadStreamState * _Nonnull)state config:(AIBudsVadSegmentationConfig * _Nonnull)config returnSeconds:(BOOL)returnSeconds timeResolution:(NSInteger)timeResolution error:(NSError * _Nullable * _Nullable)error completion:(void (^ _Nonnull)(AIBudsVadStreamResult * _Nonnull))completion;
@end

@class AVAudioFormat;
@class NSData;
@class NSURL;
/// Converts audio buffers to the format required by ASR (16kHz, mono, Float32).
/// Implementation notes:
/// <ul>
///   <li>
///     Uses <code>AVAudioConverter</code> for all sample-rate, sample-format, and channel-count conversions.
///   </li>
///   <li>
///     Avoids any manual resampling; only raw sample extraction occurs after conversion.
///   </li>
///   <li>
///     Creates a new converter for each operation (stateless).
///   </li>
/// </ul>
SWIFT_CLASS_NAMED("AudioConverter")
@interface AIBudsAudioConverter : NSObject
/// Public initializer so external modules (e.g. CLI) can construct the converter
/// \param targetFormat Target audio format
///
- (nonnull instancetype)initWithTargetFormat:(AVAudioFormat * _Nullable)targetFormat OBJC_DESIGNATED_INITIALIZER;
/// Converts a PCM buffer to a specified format
/// \param pcmBuffer The input PCM buffer to convert
///
/// \param targetFormat The target audio format description
///
///
/// returns:
/// The converted PCM buffer, or nil if conversion fails
+ (AVAudioPCMBuffer * _Nullable)convertPCMBuffer:(AVAudioPCMBuffer * _Nonnull)pcmBuffer toFormat:(AudioStreamBasicDescription)targetFormat SWIFT_WARN_UNUSED_RESULT;
/// Converts a PCM buffer to Data
/// \param pcmBuffer The input PCM buffer to convert
///
///
/// returns:
/// The converted audio data as Data, or nil if conversion fails
+ (NSData * _Nullable)convertPCMBufferToInt16Data:(AVAudioPCMBuffer * _Nonnull)pcmBuffer SWIFT_WARN_UNUSED_RESULT;
/// Converts an array of 16-bit PCM samples to normalized Float32 samples.
/// Each <code>Int16</code> value is divided by <code>32768.0</code> to map the range <code>[-32768, 32767]</code>
/// onto the interval <code>[-1.0, 1.0]</code>.
/// \param int16Pcm The source 16-bit PCM samples.
///
///
/// returns:
/// An array of <code>Float</code> values in the range <code>[-1.0, 1.0]</code>.
- (NSArray<NSNumber *> * _Nonnull)convertInt16PcmToFloat:(NSArray<NSNumber *> * _Nonnull)int16Pcm SWIFT_WARN_UNUSED_RESULT;
/// Converts an array of normalized Float32 samples to 16-bit PCM samples.
/// Each <code>Float</code> value is multiplied by <code>32768.0</code>, rounded to the nearest integer,
/// and clipped to the <code>Int16</code> range <code>[-32768, 32767]</code>.
/// \param floatPcm The source Float samples in the range <code>[-1.0, 1.0]</code>.
///
///
/// returns:
/// An array of <code>Int16</code> PCM samples.
- (NSArray<NSNumber *> * _Nonnull)convertFloatPcmToInt16:(NSArray<NSNumber *> * _Nonnull)floatPcm SWIFT_WARN_UNUSED_RESULT;
/// Convert a standalone buffer to the target format.
/// \param buffer Input audio buffer (any format)
///
///
/// returns:
/// Float array at 16kHz mono
- (NSArray<NSNumber *> * _Nullable)resampleBuffer:(AVAudioPCMBuffer * _Nonnull)buffer error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Convert an audio file to 16kHz mono Float32 samples
/// \param url URL of the audio file to read
///
///
/// returns:
/// Float array at 16kHz mono
- (NSArray<NSNumber *> * _Nullable)resampleAudioFile:(NSURL * _Nonnull)url error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Convert an audio file path to 16kHz mono Float32 samples
/// \param path File path of the audio file to read
///
///
/// returns:
/// Float array at 16kHz mono
- (NSArray<NSNumber *> * _Nullable)resampleAudioFileWithPath:(NSString * _Nonnull)path error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Convert a CMSampleBuffer to the target format
/// \param sampleBuffer Input CMSampleBuffer containing PCM data
///
///
/// throws:
/// <code>AudioConverterError.sampleBufferFormatMissing</code> (most likely caused by the sample buffer belonging
/// to a video frame)
///
/// returns:
/// Float array at 16kHz mono
- (NSArray<NSNumber *> * _Nullable)resampleSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Extract the <code>AVAudioPCMBuffer</code> from a <code>CMSampleBuffer</code>
/// \param sampleBuffer Input CMSampleBuffer containing PCM data
///
///
/// throws:
/// <code>AudioConverterError.sampleBufferFormatMissing</code> (most likely caused by the sample buffer belonging
/// to a video frame)
///
/// returns:
/// An <code>AVAudioPCMBuffer</code>
- (AVAudioPCMBuffer * _Nullable)extractAVAudioPCMBufferFrom:(CMSampleBufferRef _Nonnull)sampleBuffer error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An audio recorder that captures audio from the microphone.
SWIFT_CLASS_NAMED("AudioRecorder")
@interface AIBudsAudioRecorder : NSObject
/// Recording state
@property (nonatomic, readonly) BOOL isRecording;
/// Recording callback closure: called whenever an audio buffer is received
@property (nonatomic, copy) void (^ _Nullable onAudioBuffer)(AVAudioPCMBuffer * _Nonnull);
/// Recording error callback
@property (nonatomic, copy) void (^ _Nullable onRecordingError)(NSError * _Nonnull);
/// Start recording
///
/// throws:
/// Throws an error if AVAudioEngine fails to start
- (BOOL)startRecordingAndReturnError:(NSError * _Nullable * _Nullable)error;
/// Stop recording
- (void)stopRecording;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AIBudsPCMConfig;
SWIFT_CLASS_NAMED("PCMAudioPlayer")
@interface AIBudsPCMAudioPlayer : NSObject
@property (nonatomic, readonly) NSTimeInterval currentProgress;
@property (nonatomic, readonly) BOOL isPlaying;
@property (nonatomic, copy) void (^ _Nullable onProgressUpdate)(NSTimeInterval, NSTimeInterval);
@property (nonatomic, copy) void (^ _Nullable onPlayComplete)(void);
- (nullable instancetype)initWithPcmData:(NSData * _Nonnull)pcmData config:(AIBudsPCMConfig * _Nonnull)config error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (BOOL)playAndReturnError:(NSError * _Nullable * _Nullable)error;
- (void)pause;
- (void)stop;
- (void)seekTo:(NSTimeInterval)targetTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("PCMConfig")
@interface AIBudsPCMConfig : NSObject
- (nullable instancetype)initWithSampleRate:(double)sampleRate channelCount:(NSInteger)channelCount bitDepth:(NSInteger)bitDepth error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Playback stop reason
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsPlaybackStopReason, "PlaybackStopReason", open) {
/// Playback finished normally
  AIBudsPlaybackStopReasonFinished = 0,
/// Playback was interrupted
  AIBudsPlaybackStopReasonInterrupted = 1,
/// Playback encountered an error
  AIBudsPlaybackStopReasonError = 2,
};

/// A singleton audio capturer designed for recording audio from the Bluetooth Hands-Free Profile (HFP) SCO channel.
SWIFT_CLASS_NAMED("SCOAudioCapturer")
@interface AIBudsSCOAudioCapturer : NSObject
/// The global shared capturer instance.
/// note:
/// Access this property to obtain the singleton object; do not instantiate <code>SCOAudioCapturer</code> directly.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsSCOAudioCapturer * _Nonnull shared;)
+ (AIBudsSCOAudioCapturer * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to prevent multiple instances.
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Capturing state
@property (nonatomic, readonly) BOOL isCapturing;
/// Capturing callback closure: called whenever an audio buffer is received
@property (nonatomic, copy) void (^ _Nullable onAudioBuffer)(AVAudioPCMBuffer * _Nonnull);
/// Capturing error callback
@property (nonatomic, copy) void (^ _Nullable onCapturingError)(NSError * _Nonnull);
/// Enables background audio capture mode for iOS 16.0 and later.
/// This method configures the shared <code>PushToTalkSession</code> instance to allow audio capture
/// while the application is in the background. It sets up the channel manager and enables
/// the session.
/// note:
/// Available only on iOS 16.0 and later. Does nothing on earlier versions.
+ (void)enableBackgroundMode;
/// Disables background audio capture mode for iOS 16.0 and later.
/// This method disables the shared <code>PushToTalkSession</code> instance, preventing audio capture
/// while the application is in the background.
/// note:
/// Available only on iOS 16.0 and later. Does nothing on earlier versions.
+ (void)disableBackgroundMode;
/// Sets the preferred Bluetooth HFP input device for audio capture.
/// This method configures the audio session to use the specified Bluetooth Hands-Free Profile (HFP)
/// device as the preferred input. If both name and MAC address are provided, the method attempts
/// to match the device by both criteria. If only the name is provided, it matches by name alone.
/// If neither is provided, it selects the first available Bluetooth HFP device.
/// \param preferredBluetoothName The name of the Bluetooth device to prefer. Optional.
///
/// \param preferredMacAddress The MAC address of the Bluetooth device to prefer. Optional.
///
+ (void)setPreferredInput:(NSString * _Nullable)preferredBluetoothName :(NSString * _Nullable)preferredMacAddress;
/// Start capturing SCO audio.
/// \param preferredBluetoothName The name of the Bluetooth device to prefer.
///
/// \param preferredMacAddress The MAC address of the Bluetooth device to prefer.
///
///
/// returns:
/// success or failure
- (BOOL)startCapturing:(NSString * _Nullable)preferredBluetoothName :(NSString * _Nullable)preferredMacAddress SWIFT_WARN_UNUSED_RESULT;
/// Stop capturing SCO audio
- (void)stopCapturing;
@end

@class NSDate;
/// A streaming voice player that plays incoming PCM audio data in real-time.
/// Plays incoming PCM audio data in real-time, supporting interruption, switching, and lifecycle callbacks.
SWIFT_CLASS_NAMED("StreamingVoicePlayer")
@interface AIBudsStreamingVoicePlayer : NSObject
/// The expected audio format for all incoming PCM data: 16 kHz, 16-bit, mono, interleaved.
@property (nonatomic, readonly, strong) AVAudioFormat * _Nullable audioFormat;
/// Called when the first buffer of a new voice is scheduled and playback begins.
/// \param voiceId The unique identifier of the voice that started playing.
///
@property (nonatomic, copy) void (^ _Nullable onVoicePlaybackDidStart)(NSString * _Nonnull);
/// Called when playback stops for any reason (finished, interrupted, or error).
/// \param voiceId The unique identifier of the voice that stopped playing.
///
/// \param reason The reason playback stopped.
///
/// \param startTime The moment playback began.
///
/// \param stopTime The moment playback ended.
///
/// \param error Optional error if playback ended abnormally.
///
@property (nonatomic, copy) void (^ _Nullable onVoicePlaybackDidStop)(NSString * _Nonnull, enum AIBudsPlaybackStopReason, NSDate * _Nonnull, NSDate * _Nonnull, NSError * _Nullable);
/// Initializes a new streaming voice player.
/// Fails if the internal audio engine cannot be started.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Starts the audio engine if it is not already running.
///
/// returns:
/// <code>true</code> if the engine was successfully started; otherwise, <code>false</code>.
- (BOOL)start SWIFT_WARN_UNUSED_RESULT;
/// Stops the audio engine if it is running.
///
/// returns:
/// <code>true</code> if the engine was successfully stopped; otherwise, <code>false</code>.
- (BOOL)stop SWIFT_WARN_UNUSED_RESULT;
/// Appends a chunk of 16-bit integer PCM data to the playback queue.
/// If the engine is not running, callbacks are invoked immediately with an error.
/// If a different <code>voiceId</code> is already playing, the current voice is interrupted.
/// \param pcmData The audio data to append.
///
/// \param voiceId Unique identifier for this voice session.
///
/// \param isFinal <code>true</code> if this is the last buffer for the voice.
///
- (void)appendInt16PCM:(NSData * _Nonnull)pcmData voiceId:(NSString * _Nonnull)voiceId isFinal:(BOOL)isFinal;
/// Returns <code>true</code> if any voice is currently playing.
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
/// Immediately stops the current voice (if any) and reports interruption via callback.
- (void)interruptCurrentVoicePlayback;
@end

/// Errors that can occur during streaming voice player operations.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsStreamingVoicePlayerErrorCode, "StreamingVoicePlayerErrorCode", open) {
/// Unknown
  AIBudsStreamingVoicePlayerErrorCodeUnknown = -1,
/// audio engine not running
  AIBudsStreamingVoicePlayerErrorCodeAudioEngineNotRunning = 1000,
/// waiting more buffer timeout
  AIBudsStreamingVoicePlayerErrorCodeWaitingMoreBufferTimeout = 1001,
};

SWIFT_CLASS_NAMED("TenVadResult")
@interface AIBudsTenVadResult : NSObject
/// The probability of human voice presence, ranging from 0 to 1.
@property (nonatomic, readonly) float probability;
/// Whether is speech
@property (nonatomic, readonly) BOOL isSpeech;
- (nonnull instancetype)initWithProbability:(float)probability isSpeech:(BOOL)isSpeech OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsTenVadResult (SWIFT_EXTENSION(AIBudsAudio)) <NSCopying>
/// 返回当前对象的深拷贝实例
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Voice Activity Detection (VAD) configuration class.
/// This class encapsulates parameters used to configure the VAD model, including threshold, debug mode, and Core ML compute units.
SWIFT_CLASS_NAMED("VadConfig")
@interface AIBudsVadConfig : NSObject
/// Default Core ML compute units.
/// On iOS 16 and above, prefers CPU and Neural Engine combination; otherwise falls back to CPU and GPU.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) MLComputeUnits defaultComputeUnits;)
+ (MLComputeUnits)defaultComputeUnits SWIFT_WARN_UNUSED_RESULT;
/// Default detection threshold.
/// Range is 0 to 1, default is 0.85. Higher values make detection stricter.
@property (nonatomic) float defaultThreshold;
/// Whether to enable debug mode.
/// When enabled, additional debug logs are printed. Default is off.
@property (nonatomic) BOOL debugMode;
/// Core ML compute units to use.
/// Default is <code>defaultComputeUnits</code>, adjustable as needed.
@property (nonatomic) MLComputeUnits computeUnits;
/// Default configuration instance.
/// A singleton <code>VadConfig</code> constructed with default parameters.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsVadConfig * _Nonnull defaultConfig;)
+ (AIBudsVadConfig * _Nonnull)defaultConfig SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Errors that can occur during VAD (Voice Activity Detection) operations.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsVadErrorCode, "VadErrorCode", open) {
/// Unknown
  AIBudsVadErrorCodeUnknown = -1,
/// The VAD system has not been initialized.
  AIBudsVadErrorCodeNotInitialized = 1000,
/// The VAD model could not be loaded.
  AIBudsVadErrorCodeModelLoadingFailed = 1001,
/// An error occurred while processing the model.
  AIBudsVadErrorCodeModelProcessingFailed = 1002,
};

@class AIBudsVadState;
/// The result of a Voice Activity Detection (VAD) inference.
SWIFT_CLASS_NAMED("VadResult")
@interface AIBudsVadResult : NSObject
/// The probability of human voice presence, ranging from 0 to 1.
@property (nonatomic, readonly) float probability;
/// Indicates whether human voice is detected.
@property (nonatomic, readonly) BOOL isVoiceActive;
/// The elapsed time for this inference, measured in seconds.
@property (nonatomic, readonly) NSTimeInterval processingTime;
/// The output state of the VAD.
@property (nonatomic, readonly, strong) AIBudsVadState * _Nonnull outputState;
/// Initializes a new VAD result.
/// \param probability The probability of human voice presence, ranging from 0 to 1.
///
/// \param isVoiceActive Indicates whether human voice is detected.
///
/// \param processingTime The elapsed time for this inference, measured in seconds.
///
/// \param outputState The output state of the VAD.
///
- (nonnull instancetype)initWithProbability:(float)probability isVoiceActive:(BOOL)isVoiceActive processingTime:(NSTimeInterval)processingTime outputState:(AIBudsVadState * _Nonnull)outputState OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsVadResult (SWIFT_EXTENSION(AIBudsAudio)) <NSCopying>
/// 返回当前对象的深拷贝实例
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// A segment of audio identified as voice activity.
/// Use <code>VadSegment</code> to represent a time range during which voice activity is detected.
SWIFT_CLASS_NAMED("VadSegment")
@interface AIBudsVadSegment : NSObject
/// The start time of the segment, in seconds.
@property (nonatomic, readonly) NSTimeInterval startTime;
/// The end time of the segment, in seconds.
@property (nonatomic, readonly) NSTimeInterval endTime;
/// The duration of the segment, in seconds.
/// This value is calculated as <code>endTime - startTime</code>.
@property (nonatomic, readonly) NSTimeInterval duration;
/// Converts the start time to a sample index for a given sample rate.
/// \param sampleRate The sample rate in Hz.
///
///
/// returns:
/// The corresponding sample index.
- (NSInteger)startSampleWithSampleRate:(NSInteger)sampleRate SWIFT_WARN_UNUSED_RESULT;
/// Converts the end time to a sample index for a given sample rate.
/// \param sampleRate The sample rate in Hz.
///
///
/// returns:
/// The corresponding sample index.
- (NSInteger)endSampleWithSampleRate:(NSInteger)sampleRate SWIFT_WARN_UNUSED_RESULT;
/// Calculates the number of samples in this segment for a given sample rate.
/// \param sampleRate The sample rate in Hz.
///
///
/// returns:
/// The number of samples between the start and end times.
- (NSInteger)sampleCountWithSampleRate:(NSInteger)sampleRate SWIFT_WARN_UNUSED_RESULT;
/// Creates a new voice-activity segment.
/// \param startTime The start time of the segment, in seconds.
///
/// \param endTime The end time of the segment, in seconds.
///
- (nonnull instancetype)initWithStartTime:(NSTimeInterval)startTime endTime:(NSTimeInterval)endTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
/// Configuration object for Voice-Activity-Detection (VAD) segmentation.
/// Use this class to tune the sensitivity and timing constraints that determine
/// when a speech segment starts and ends.
SWIFT_CLASS_NAMED("VadSegmentationConfig")
@interface AIBudsVadSegmentationConfig : NSObject
/// Minimum duration (in seconds) of continuous speech before a segment is considered valid.
/// Segments shorter than this value are ignored.
@property (nonatomic) NSTimeInterval minSpeechDuration;
/// Minimum duration (in seconds) of silence that must follow speech before the segment is closed.
@property (nonatomic) NSTimeInterval minSilenceDuration;
/// Hard upper-bound (in seconds) for any single speech segment.
/// When this limit is reached the segment is forcibly terminated.
@property (nonatomic) NSTimeInterval maxSpeechDuration;
/// Extra padding (in seconds) added to both ends of a detected speech segment.
@property (nonatomic) NSTimeInterval speechPadding;
/// Probability threshold in <code>[0, 1]</code> used to decide whether a frame is silence.
/// Frames whose speech probability is <em>below</em> this value are treated as silence.
@property (nonatomic) float silenceThresholdForSplit;
/// Optional override for the lower (negative) threshold in the hysteresis logic.
/// When <code>nil</code>, the negative threshold is computed as
/// <code>silenceThresholdForSplit - negativeThresholdOffset</code>.
@property (nonatomic, strong) NSNumber * _Nullable negativeThreshold;
/// Offset subtracted from <code>silenceThresholdForSplit</code> to obtain the default negative threshold.
/// Ignored when <code>negativeThreshold</code> is explicitly set.
@property (nonatomic) float negativeThresholdOffset;
/// Minimum silence duration (in seconds) that must elapse once <code>maxSpeechDuration</code> is hit.
@property (nonatomic) NSTimeInterval minSilenceAtMaxSpeech;
/// When <code>true</code>, the engine prefers the longest feasible silence window
/// after <code>maxSpeechDuration</code> is reached.
@property (nonatomic) BOOL useMaxPossibleSilenceAtMaxSpeech;
/// A ready-to-use configuration with sensible defaults.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsVadSegmentationConfig * _Nonnull defaultConfig;)
+ (AIBudsVadSegmentationConfig * _Nonnull)defaultConfig SWIFT_WARN_UNUSED_RESULT;
/// Creates a segmentation configuration.
/// \param minSpeechDuration See <code>minSpeechDuration</code>.
///
/// \param minSilenceDuration See <code>minSilenceDuration</code>.
///
/// \param maxSpeechDuration See <code>maxSpeechDuration</code>.
///
/// \param speechPadding See <code>speechPadding</code>.
///
/// \param silenceThresholdForSplit See <code>silenceThresholdForSplit</code>.
///
/// \param negativeThreshold See <code>negativeThreshold</code>.
///
/// \param negativeThresholdOffset See <code>negativeThresholdOffset</code>.
///
/// \param minSilenceAtMaxSpeech See <code>minSilenceAtMaxSpeech</code>.
///
/// \param useMaxPossibleSilenceAtMaxSpeech See <code>useMaxPossibleSilenceAtMaxSpeech</code>.
///
- (nonnull instancetype)initWithMinSpeechDuration:(NSTimeInterval)minSpeechDuration minSilenceDuration:(NSTimeInterval)minSilenceDuration maxSpeechDuration:(NSTimeInterval)maxSpeechDuration speechPadding:(NSTimeInterval)speechPadding silenceThresholdForSplit:(float)silenceThresholdForSplit negativeThreshold:(NSNumber * _Nullable)negativeThreshold negativeThresholdOffset:(float)negativeThresholdOffset minSilenceAtMaxSpeech:(NSTimeInterval)minSilenceAtMaxSpeech useMaxPossibleSilenceAtMaxSpeech:(BOOL)useMaxPossibleSilenceAtMaxSpeech OBJC_DESIGNATED_INITIALIZER;
/// Computes the effective negative (lower) threshold for hysteresis.
/// If <code>negativeThreshold</code> is set, that value is returned; otherwise
/// the result is <code>max(baseThreshold - negativeThresholdOffset, 0.01)</code>.
/// \param baseThreshold The primary positive threshold.
///
///
/// returns:
/// The lower threshold, clamped to at least <code>0.01</code>.
- (float)effectiveNegativeThresholdWithBaseThreshold:(float)baseThreshold SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Voice-Activity-Detection state container.
/// <code>VadState</code> holds the recurrent hidden / cell states and the context vector
/// produced by the VAD neural-network model after each audio frame is processed.
/// The state must be passed to subsequent inference calls so the model can
/// maintain temporal coherence.
SWIFT_CLASS_NAMED("VadState")
@interface AIBudsVadState : NSObject
/// Dimensionality of the context vector produced by the model.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger contextLength;)
+ (NSInteger)contextLength SWIFT_WARN_UNUSED_RESULT;
/// Hidden state vector of the LSTM layer.
/// Its length is 128 and it is updated after every inference call.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull hiddenState;
/// Cell state vector of the LSTM layer.
/// Its length is 128 and it is updated together with <code>hiddenState</code>.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull cellState;
/// Context vector summarizing recent acoustic information.
/// The vector is produced by the model and can be used for downstream tasks.
/// Its length is defined by <code>contextLength</code>.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull context;
/// Creates a new VAD state.
/// \param hiddenState Hidden state vector of length 128.
///
/// \param cellState Cell state vector of length 128.
///
/// \param context Context vector of length <code>contextLength</code>.
/// Defaults to an all-zero vector.
///
- (nonnull instancetype)initWithHiddenState:(NSArray<NSNumber *> * _Nonnull)hiddenState cellState:(NSArray<NSNumber *> * _Nonnull)cellState context:(NSArray<NSNumber *> * _Nonnull)context OBJC_DESIGNATED_INITIALIZER;
/// Returns the canonical initial (all-zero) state.
/// Use this state when processing the very first audio frame of a stream.
+ (AIBudsVadState * _Nonnull)initial SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsVadState (SWIFT_EXTENSION(AIBudsAudio)) <NSCopying>
/// 深拷贝当前实例
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

enum AIBudsVadStreamEventKind : NSInteger;
/// Represents a single event in a Voice Activity Detection (VAD) stream.
SWIFT_CLASS_NAMED("VadStreamEvent")
@interface AIBudsVadStreamEvent : NSObject
/// The type of this event.
@property (nonatomic, readonly) enum AIBudsVadStreamEventKind kind;
/// The sample index at which this event occurred.
@property (nonatomic, readonly) NSInteger sampleIndex;
/// The optional timestamp (in seconds) associated with this event.
@property (nonatomic, readonly, strong) NSNumber * _Nullable time;
/// Creates a new VAD stream event.
/// \param kind The kind of event.
///
/// \param sampleIndex The sample index at which the event occurred.
///
/// \param time An optional timestamp (in seconds) for the event.
///
- (nonnull instancetype)initWithKind:(enum AIBudsVadStreamEventKind)kind sampleIndex:(NSInteger)sampleIndex time:(NSNumber * _Nullable)time OBJC_DESIGNATED_INITIALIZER;
/// Indicates whether this event marks the start of speech.
@property (nonatomic, readonly) BOOL isStart;
/// Indicates whether this event marks the end of speech.
@property (nonatomic, readonly) BOOL isEnd;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsVadStreamEvent (SWIFT_EXTENSION(AIBudsAudio)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// The kind of event emitted by a voice-activity-detection (VAD) stream.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsVadStreamEventKind, "VadStreamEventKind", open) {
/// Indicates that speech has started in the audio stream.
  AIBudsVadStreamEventKindSpeechStart = 0,
/// Indicates that speech has ended in the audio stream.
  AIBudsVadStreamEventKindSpeechEnd = 1,
};

/// The result of a Voice Activity Detection (VAD) stream analysis.
SWIFT_CLASS_NAMED("VadStreamResult")
@interface AIBudsVadStreamResult : NSObject
/// The current state of the VAD stream.
@property (nonatomic, readonly, strong) AIBudsVadStreamState * _Nonnull state;
/// The event that triggered this result, if any.
@property (nonatomic, readonly, strong) AIBudsVadStreamEvent * _Nullable event;
/// The probability (0–1) that the stream contains voice activity.
@property (nonatomic, readonly) float probability;
/// Creates a new VAD stream result.
/// \param state The current state of the VAD stream.
///
/// \param event The event that triggered this result, if any.
///
/// \param probability The probability (0–1) that the stream contains voice activity.
///
- (nonnull instancetype)initWithState:(AIBudsVadStreamState * _Nonnull)state event:(AIBudsVadStreamEvent * _Nullable)event probability:(float)probability OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsVadStreamResult (SWIFT_EXTENSION(AIBudsAudio)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// The state of a Voice Activity Detection (VAD) audio stream.
/// This class encapsulates the runtime state used by the VAD engine to track
/// voice activity over time.
SWIFT_CLASS_NAMED("VadStreamState")
@interface AIBudsVadStreamState : NSObject
/// The current state of the underlying VAD model.
@property (nonatomic, strong) AIBudsVadState * _Nonnull modelState;
/// Indicates whether voice activity has been detected in the current stream.
@property (nonatomic) BOOL triggered;
/// The sample index at which a temporary end of speech was detected, if any.
/// This value is used internally to handle short pauses within an utterance.
@property (nonatomic, strong) NSNumber * _Nullable tempEndSample;
/// The total number of audio samples processed so far in this stream.
@property (nonatomic) NSInteger processedSamples;
/// Creates a new <code>VadStreamState</code> instance.
/// \param modelState The initial state of the VAD model. Defaults to <code>.initial()</code>.
///
/// \param triggered Whether voice activity is initially detected. Defaults to <code>false</code>.
///
/// \param tempEndSample The sample index of a temporary end, if known. Defaults to <code>nil</code>.
///
/// \param processedSamples The number of samples already processed. Defaults to <code>0</code>.
///
- (nonnull instancetype)initWithModelState:(AIBudsVadState * _Nonnull)modelState triggered:(BOOL)triggered tempEndSample:(NSNumber * _Nullable)tempEndSample processedSamples:(NSInteger)processedSamples OBJC_DESIGNATED_INITIALIZER;
/// Returns a fresh <code>VadStreamState</code> instance with default values.
+ (AIBudsVadStreamState * _Nonnull)initial SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsVadStreamState (SWIFT_EXTENSION(AIBudsAudio)) <NSCopying>
/// 实现深拷贝，返回一个新的 VadStreamState 实例，其所有属性均复制自当前实例。
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

@class MLFeatureValue;
/// Zero-copy feature provider for chaining models
SWIFT_CLASS("_TtC11AIBudsAudio31ZeroCopyDiarizerFeatureProvider")
@interface ZeroCopyDiarizerFeatureProvider : NSObject <MLFeatureProvider>
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull featureNames;
- (MLFeatureValue * _Nullable)featureValueForName:(NSString * _Nonnull)featureName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
