#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.1 effective-5.10 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)
#ifndef ABMATE_SWIFT_H
#define ABMATE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ABMate",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AIBuds;
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ABMate",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@protocol AIBudsSDKDelegate;
SWIFT_CLASS("_TtC6ABMate9ABMateSDK")
@interface ABMateSDK : NSObject
/// SDK delegate
@property (nonatomic, strong) id <AIBudsSDKDelegate> _Nullable delegate;
/// The shared singleton instance of ABMateSDK
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ABMateSDK * _Nonnull shared;)
+ (ABMateSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@interface ABMateSDK (SWIFT_EXTENSION(ABMate))
/// The error domain used for ABMateSDK camera ota errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CameraOtaErrorDomain;)
+ (NSString * _Nonnull)CameraOtaErrorDomain SWIFT_WARN_UNUSED_RESULT;
@end

@interface ABMateSDK (SWIFT_EXTENSION(ABMate))
/// The error domain used for ABMateSDK ota errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull OtaErrorDomain;)
+ (NSString * _Nonnull)OtaErrorDomain SWIFT_WARN_UNUSED_RESULT;
@end

@interface ABMateSDK (SWIFT_EXTENSION(ABMate))
/// The data packet error domain used for ABMateSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DataPacketErrorDomain;)
+ (NSString * _Nonnull)DataPacketErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// The data packet error key used for ABMateSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DataPacketErrorKey;)
+ (NSString * _Nonnull)DataPacketErrorKey SWIFT_WARN_UNUSED_RESULT;
@end

@interface ABMateSDK (SWIFT_EXTENSION(ABMate))
/// The error domain used for ABMateSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorDomain;)
+ (NSString * _Nonnull)ErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// The error key used for ABMateSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorKey;)
+ (NSString * _Nonnull)ErrorKey SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsBleProtocolKind)
@protocol AIBudsDeviceConvertible;
@class CBPeripheral;
@class NSNumber;
@class CBCentralManager;
@protocol AIBudsFoundDeviceConvertible;
@interface ABMateSDK (SWIFT_EXTENSION(ABMate)) <AIBudsBleConnectSDK>
/// The version number of the SDK
///
/// returns:
/// A string representing the current SDK version (e.g. “1.0.0-beta.1”)
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
/// The build number of the SDK
///
/// returns:
/// A string representing the SDK build number (e.g. “20250315001”)
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkBuild;
/// The release date of the SDK
///
/// returns:
/// A string representing the SDK release date in YYYY-MM-DD format
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkReleaseDate;
/// Returns a formatted string containing SDK version information
/// note:
/// The returned string includes an emoji prefix and is formatted for easy reading
///
/// returns:
/// A string containing the SDK name, version, build number and release date
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersionDescription;
/// SDK name
///
/// returns:
/// SDK name string, e.g. “TopStepABMateSDK”
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkName;
/// SDK provider name
///
/// returns:
/// SDK provider name string, e.g. “topstep”
@property (nonatomic, readonly, copy) NSString * _Nonnull providerName;
/// Bluetooth data communication protocol type
@property (nonatomic, readonly) enum AIBudsBleProtocolKind protocolKind;
/// The class type of my device model
@property (nonatomic, readonly) Class <AIBudsDeviceConvertible> _Nonnull classForDeviceModel;
/// Sets the delegate for the SDK to receive events and notifications.
/// \param delegate The object that conforms to the <code>SDKDelegate</code> protocol to receive SDK events.
///
- (void)setSDKDelegate:(id <AIBudsSDKDelegate> _Nullable)delegate;
/// Determines whether the scanned peripheral is a known device based on its advertisement data and RSSI
/// \param peripheral The scanned Bluetooth peripheral
///
/// \param advertisementData The advertisement data broadcasted by the peripheral
///
/// \param rssi The signal strength indicator
///
///
/// returns:
/// true if the device is known, false otherwise
- (BOOL)isKnownDevice:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData rssi:(NSNumber * _Nonnull)rssi SWIFT_WARN_UNUSED_RESULT;
/// Resolve as an AI device from the given Bluetooth discovery parameters.
/// \param central The <code>CBCentralManager</code> that discovered the peripheral.
///
/// \param peripheral The discovered <code>CBPeripheral</code>.
///
/// \param advertisementData The advertisement data dictionary, or <code>nil</code> if unavailable.
///
/// \param rssi The received signal strength indicator, or <code>nil</code> if unavailable.
///
///
/// returns:
/// An instance of <code>FoundDeviceConvertible</code> if the device is successfully resolved, otherwise <code>nil</code>.
- (id <AIBudsFoundDeviceConvertible> _Nullable)createWithCentral:(CBCentralManager * _Nonnull)central peripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nullable)advertisementData rssi:(NSNumber * _Nullable)rssi SWIFT_WARN_UNUSED_RESULT;
/// Returns a list of known devices that are currently connected to the iOS device.
///
/// returns:
/// An array of <code>CBPeripheral</code> objects representing the connected devices.
- (NSArray<CBPeripheral *> * _Nonnull)knownDevicesConnectedToiOS SWIFT_WARN_UNUSED_RESULT;
@end

/// Enum for device command types, used to identify the communication direction or purpose of the command.
typedef SWIFT_ENUM_NAMED(uint8_t, ABMateCommandType, "CommandType", open) {
/// Request type, indicating a request initiated by the SDK to the device.
  ABMateCommandTypeRequest = 0x01,
/// Response type, indicating a response from the device to an SDK request.
  ABMateCommandTypeResponse = 0x02,
/// Notification type, indicating data proactively pushed by the device.
  ABMateCommandTypeNotify = 0x03,
/// Invalid type, indicating an unrecognized or unsupported command type.
  ABMateCommandTypeInvalid = 0xff,
};

/// Device connection channel type enumeration
/// This enum represents the different types of connection channels that can be used to communicate with devices:
/// <ul>
///   <li>
///     <code>sppOrGatt</code>: Serial Port Profile (SPP) or Generic Attribute Profile (GATT) connection
///   </li>
///   <li>
///     <code>ble</code>: Bluetooth Low Energy (BLE) connection
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, ABMateConnectionChannel, "ConnectionChannel", open) {
/// Undefined connection channel type
  ABMateConnectionChannelUndefined = -1,
/// Serial Port Profile (SPP) or Generic Attribute Profile (GATT) connection channel
  ABMateConnectionChannelSppOrGatt = 0,
/// Bluetooth Low Energy (BLE) connection channel
  ABMateConnectionChannelBle = 1,
};

@class NSData;
/// Device custom command conversion protocol
/// Types conforming to this protocol can convert themselves into a device-recognizable command format
SWIFT_PROTOCOL_NAMED("CustomCommandConvertiable")
@protocol ABMateCustomCommandConvertiable <NSObject>
/// Command key
/// Used to identify the specific device operation command
@property (nonatomic, readonly) uint8_t cmdKey;
/// Command type
/// Used to distinguish the category of the command, optional values: 0x01 request, 0x02 response, 0x03 notify
@property (nonatomic, readonly) enum ABMateCommandType cmdType;
/// Payload data
/// Additional data carried by the command, may be nil
@property (nonatomic, readonly, copy) NSData * _Nullable payload;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, ABMateDataPacketError, "DataPacketError", open) {
  ABMateDataPacketErrorUnknown = 0,
  ABMateDataPacketErrorInvalidDataLength = 1,
  ABMateDataPacketErrorBadPacketType = 2,
  ABMateDataPacketErrorBadPacket = 3,
};
static NSString * _Nonnull const ABMateDataPacketErrorDomain = @"ABMate.DataPacketError";

/// Debug log category
typedef SWIFT_ENUM_NAMED(uint32_t, ABMateDebugLogCategory, "DebugLogCategory", open) {
/// 0 - Reserved (not used for now)
  ABMateDebugLogCategoryReserved = 0,
/// 1 - System event tracking
  ABMateDebugLogCategorySystemEvent = 1,
/// 2 - User action tracking
  ABMateDebugLogCategoryUserEvent = 2,
/// 3 - Factory test
  ABMateDebugLogCategoryFactoryTest = 3,
};

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsDeviceProduct)
@class NSUUID;
@class NSCoder;
SWIFT_CLASS_NAMED("DeviceBeaconModel")
@interface ABMateDeviceBeaconModel : NSObject <AIBudsDeviceBeaconConvertible>
/// Protocol version
@property (nonatomic, readonly) uint8_t protocolVersion;
/// Device product type
@property (nonatomic, readonly) enum AIBudsDeviceProduct product;
/// Product ID
@property (nonatomic, readonly) uint16_t productId;
/// MAC address
@property (nonatomic, readonly, copy) NSString * _Nullable macAddress;
/// Whether security authentication is required
@property (nonatomic, readonly) BOOL requiresSecureAuthentication;
/// Indicates whether Cross-Transport Key Derivation (CTKD) is supported.
/// When CTKD is supported, you can enable transport bridging by setting
/// <code>CBConnectPeripheralOptionEnableTransportBridgingKey</code> to <code>true</code> in connection options.
/// This allows the iOS system to automatically establish classic Bluetooth profiles
/// alongside the BLE connection.
@property (nonatomic, readonly) BOOL supportCTKD;
/// Whether classic Bluetooth is connected
@property (nonatomic, readonly) BOOL isConnectedToClassicBluetooth;
/// SPP UUID
@property (nonatomic, readonly, copy) NSUUID * _Nullable sppUUID;
/// The type of connection channel used by the device.
/// This property indicates whether the device uses BLE or SPP/GATT for communication.
/// The value is determined by examining bit 5 of the manufacturer data flag byte.
///
/// returns:
/// An <code>ConnectionChannel</code> value indicating the connection channel type:
/// <ul>
///   <li>
///     <code>.ble</code> if the device uses BLE
///   </li>
///   <li>
///     <code>.sppOrGatt</code> if the device uses SPP or GATT
///   </li>
///   <li>
///     <code>.undefined</code> if the connection type cannot be determined
///   </li>
/// </ul>
@property (nonatomic, readonly) enum ABMateConnectionChannel connectionChannel;
/// Main project number
@property (nonatomic, readonly, copy) NSString * _Nullable mainProjNo;
/// Sub-project number
@property (nonatomic, readonly, copy) NSString * _Nullable subProjNo;
/// Raw advertisement data
@property (nonatomic, readonly, copy) NSData * _Nullable data;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ABMateDeviceBeaconModel (SWIFT_EXTENSION(ABMate))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// 埋点调试信息特征码（4 字节 ASCII 标识）
typedef SWIFT_ENUM_NAMED(uint32_t, ABMateEventLogSignature, "EventLogSignature", open) {
/// LOGI (0x49474F4C) - 逻辑调试数据
  ABMateEventLogSignatureLogi = 0x49474F4C,
/// BATT (0x54544142) - 电池调试数据
  ABMateEventLogSignatureBatt = 0x54544142,
/// AWNR (0x524E5741) - 全志调试数据
  ABMateEventLogSignatureAwnr = 0x524E5741,
/// CHAT (0x54414843) - AI 对话调试
  ABMateEventLogSignatureChat = 0x54414843,
};

/// A model class representing an AB Mate Bluetooth device.
SWIFT_CLASS_NAMED("FoundDeviceModel")
@interface ABMateFoundDeviceModel : NSObject <AIBudsFoundDeviceConvertible>
/// CBCentralManager instance
@property (nonatomic, readonly, weak) CBCentralManager * _Nullable central;
/// CBPeripheral instance
@property (nonatomic, readonly, strong) CBPeripheral * _Nonnull peripheral;
/// Advertisement data dictionary
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable advertisementData;
/// Signal strength indicator
@property (nonatomic, strong) NSNumber * _Nullable RSSI;
/// Bluetooth data communication protocol type
@property (nonatomic, readonly) enum AIBudsBleProtocolKind protocolKind;
/// Device type
@property (nonatomic, readonly) enum AIBudsDeviceProduct product;
/// Protocol version
@property (nonatomic, readonly) uint8_t protocolVersion;
/// Product ID
@property (nonatomic, readonly) uint16_t productId;
/// MAC address
@property (nonatomic, readonly, copy) NSString * _Nullable macAddress;
/// Whether security authentication is required
@property (nonatomic, readonly) BOOL requiresSecureAuthentication;
/// Indicates whether Cross-Transport Key Derivation (CTKD) is supported.
/// When CTKD is supported, you can enable transport bridging by setting
/// <code>CBConnectPeripheralOptionEnableTransportBridgingKey</code> to <code>true</code> in connection options.
/// This allows the iOS system to automatically establish classic Bluetooth profiles
/// alongside the BLE connection.
@property (nonatomic, readonly) BOOL supportCTKD;
/// Whether classic Bluetooth is connected
@property (nonatomic, readonly) BOOL isConnectedToClassicBluetooth;
/// SPP UUID
@property (nonatomic, readonly, copy) NSUUID * _Nullable sppUUID;
/// The type of connection channel used by the device.
/// This property indicates whether the device uses BLE or SPP/GATT for communication.
/// The value is determined by examining bit 5 of the manufacturer data flag byte.
///
/// returns:
/// An <code>ABDeviceConnectionChannelType</code> value indicating the connection channel type:
/// <ul>
///   <li>
///     <code>.ble</code> if the device uses BLE
///   </li>
///   <li>
///     <code>.sppOrGatt</code> if the device uses SPP or GATT
///   </li>
///   <li>
///     <code>.undefined</code> if the connection type cannot be determined
///   </li>
/// </ul>
@property (nonatomic, readonly) enum ABMateConnectionChannel connectionChannel;
/// Main project number
@property (nonatomic, readonly, copy) NSString * _Nullable mainProjNo;
/// Sub-project number
@property (nonatomic, readonly, copy) NSString * _Nullable subProjNo;
/// Indicates if device is already paired with system
@property (nonatomic, readonly) BOOL alreadyPaired;
/// Initializes an ABDeviceModel instance with the specified peripheral, advertisement data, and RSSI.
/// \param peripheral The CBPeripheral instance
///
/// \param central The CBCentralManager instance
///
/// \param advertisementData The advertisement data dictionary
///
/// \param rssi The signal strength indicator
///
- (nonnull instancetype)initWithPeripheral:(CBPeripheral * _Nonnull)peripheral central:(CBCentralManager * _Nullable)central advertisementData:(NSDictionary<NSString *, id> * _Nullable)advertisementData rssi:(NSNumber * _Nullable)rssi OBJC_DESIGNATED_INITIALIZER;
/// Creates an instance of the conforming type from the given Bluetooth discovery parameters.
/// \param central The <code>CBCentralManager</code> that discovered the peripheral.
///
/// \param peripheral The discovered <code>CBPeripheral</code>.
///
/// \param advertisementData The advertisement data dictionary, or <code>nil</code> if unavailable.
///
/// \param rssi The received signal strength indicator, or <code>nil</code> if unavailable.
///
///
/// returns:
/// A new instance of the conforming type, or <code>nil</code> if creation fails.
+ (id <AIBudsFoundDeviceConvertible> _Nullable)createWithCentral:(CBCentralManager * _Nonnull)central peripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nullable)advertisementData rssi:(NSNumber * _Nullable)rssi SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ABMateFoundDeviceModel (SWIFT_EXTENSION(ABMate))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

/// Camera OTA Error Code
typedef SWIFT_ENUM_NAMED(NSInteger, ABMateSdkCameraOtaErrorCode, "SdkCameraOtaErrorCode", open) {
/// Unknown
  ABMateSdkCameraOtaErrorCodeUnknown = -1,
/// Network request failed
  ABMateSdkCameraOtaErrorCodeNetworkRequestFailed = 0,
/// Camera OTA file not found
  ABMateSdkCameraOtaErrorCodeCameraOtaFileNotFound = 1,
/// Invalid camera OTA file
  ABMateSdkCameraOtaErrorCodeInvalidCameraOtaFile = 2,
/// Hotspot disconnected during OTA file transfer
  ABMateSdkCameraOtaErrorCodeHotspotDisconnectedDuringTransfer = 3,
/// Stage two did not complete within the specified time (stuck at 99% timeout)
  ABMateSdkCameraOtaErrorCodeStageTwoTimeout = 4,
/// Invalid hotspot configuration
  ABMateSdkCameraOtaErrorCodeInvalidHotspotConfig = 5,
/// Interrupted by shutdown command or low battery
  ABMateSdkCameraOtaErrorCodeInterruptedByShutdownOrLowBattery = 6,
/// Network connection timeout
  ABMateSdkCameraOtaErrorCodeNetworkTimeout = 7,
/// Camera OTA task already running
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskAlreadyRunning = 4001,
/// Camera OTA task create failed due to file not found
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskCreateFailedDueToFileNotFound = 4002,
/// Camera OTA task failed due to device disconnect
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskFailedDueToDeviceDisconnect = 4003,
/// Camera OTA task failed due to timeout
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskFailedDueToTimeout = 4004,
/// Camera OTA task start failed due to hotspot configure error
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskStartFailedDueToHotspotConfigureError = 4005,
/// Camera OTA task start failed due to enter camera OTA mode failed
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskStartFailedDueToEnterCameraOtaModeFailed = 4006,
/// Camera OTA task start failed due to hotspot connection failure
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskStartFailedDueToHotspotConnectionFailure = 4007,
/// Camera OTA task start failed due to http server start failed
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskStartFailedDueToHttpServerStartFailed = 4008,
/// Camera OTA task failed due to send firmware file url info failed
  ABMateSdkCameraOtaErrorCodeCameraOtaTaskFailedDueToSendFileUrlInfoFailed = 4009,
/// Enter camera OTA mode failed due to bad command
  ABMateSdkCameraOtaErrorCodeEnterCameraOtaModeFailedDueToBadCommand = 5001,
/// Enter camera OTA mode failed due to storage full
  ABMateSdkCameraOtaErrorCodeEnterCameraOtaModeFailedDueToStorageFull = 5002,
/// Enter camera OTA mode failed due to not allow, for example, low battery, high core temperature, etc.
  ABMateSdkCameraOtaErrorCodeEnterCameraOtaModeFailedDueToNotAllow = 5003,
/// Enter camera OTA mode failed due to no data transfer channel available
  ABMateSdkCameraOtaErrorCodeEnterCameraOtaModeFailedDueToNoDataTransferChannel = 5004,
/// Enter camera OTA mode failed due to status conflict
  ABMateSdkCameraOtaErrorCodeEnterCameraOtaModeFailedDueToStatusConflict = 5005,
/// Send camera OTA file URL info failed due to bad command
  ABMateSdkCameraOtaErrorCodeSendCameraOtaFileUrlInfoFailedDueToBadCommand = 5006,
/// Send camera OTA file URL info failed due to storage full
  ABMateSdkCameraOtaErrorCodeSendCameraOtaFileUrlInfoFailedDueToStorageFull = 5007,
/// Send camera OTA file URL info failed due to not allow, for example, low battery, high core temperature, etc.
  ABMateSdkCameraOtaErrorCodeSendCameraOtaFileUrlInfoFailedDueToNotAllow = 5008,
/// Send camera OTA file URL info failed due to no data transfer channel available
  ABMateSdkCameraOtaErrorCodeSendCameraOtaFileUrlInfoFailedDueToNoDataTransferChannel = 5009,
/// Send camera OTA file URL info failed due to status conflict
  ABMateSdkCameraOtaErrorCodeSendCameraOtaFileUrlInfoFailedDueToStatusConflict = 5010,
};

/// The error codes used for ABMateSDK errors
typedef SWIFT_ENUM_NAMED(NSInteger, ABMateSdkErrorCode, "SdkErrorCode", open) {
/// Unknown error
  ABMateSdkErrorCodeUnknown = -1,
/// Device not support
  ABMateSdkErrorCodeDeviceNotSupport = 1,
/// Device not connected
  ABMateSdkErrorCodeDeviceNotConnected = 2,
/// Device not ready
  ABMateSdkErrorCodeDeviceNotReady = 3,
/// Device busy
  ABMateSdkErrorCodeDeviceBusy = 4,
/// Scanning start failed due to Bluetooth not being powered on
  ABMateSdkErrorCodeScanningStartFailedDueToBluetoothNotPoweredOn = 1001,
/// Scanning start failed due to Bluetooth authorization being denied or restricted
  ABMateSdkErrorCodeScanningStartFailedDueToBluetoothAuthorizationDeniedOrRestricted = 1002,
/// Scanning start failed due to Bluetooth being unsupported
  ABMateSdkErrorCodeScanningStartFailedDueToBluetoothUnsupported = 1003,
/// Scanning start failed due to scanning already running
  ABMateSdkErrorCodeScanningStartFailedDueToScanningAlreadyRunning = 1004,
/// Scanning canceled due to Bluetooth not being powered on
  ABMateSdkErrorCodeScanningCanceledDueToBluetoothNotPoweredOn = 1005,
/// Request send failed due to peripheral being unavailable
  ABMateSdkErrorCodeRequestSendFailedDueToPeripheralUnavailable = 2001,
/// Request send failed due to peripheral not connected
  ABMateSdkErrorCodeRequestSendFailedDueToPeripheralNotConnected = 2002,
/// Bluetooth packet send failed due to peripheral being unavailable
  ABMateSdkErrorCodeBlePacketSendFailedDueToPeripheralUnavailable = 2003,
/// Bluetooth packet send failed due to timeout
  ABMateSdkErrorCodeBlePacketSendFailedDueToTimeout = 2004,
/// Bluetooth packet send failed due to write error
  ABMateSdkErrorCodeBlePacketSendFailedDueToWriteError = 2005,
/// Bluetooth command execution failed due to timeout
  ABMateSdkErrorCodeBleCommandExecFailedDueToTimeout = 2006,
/// Bluetooth data handle failed due to unexpected frame sequence number
  ABMateSdkErrorCodeBleDataHandleFailedDueToUnexpectedFrameSeqNum = 2007,
/// Bluetooth data handle failed due to packet info corruption
  ABMateSdkErrorCodeBleDataHandleFailedDueToPacketInfoCorruption = 2008,
/// Bluetooth data handle failed due to packet frames not matching
  ABMateSdkErrorCodeBleDataHandleFailedDueToPacketFramesNotMatching = 2009,
/// Operation failed due to wrong parameters
  ABMateSdkErrorCodeOperationFailedDueToWrongParameters = 3001,
/// Operation failed due to device return a non-success status code
  ABMateSdkErrorCodeOperationFailedDueToDeviceReturnNonSuccessStatusCode = 3002,
/// Operation failed due to device response data parsing failed
  ABMateSdkErrorCodeOperationFailedDueToDeviceResponseDataParsingFailed = 3003,
/// AI chat hangup or failed to start due to device exception
  ABMateSdkErrorCodeAiChatHangupOrFailedToStartDueToDeviceException = 3004,
/// Hotspot connection failed
  ABMateSdkErrorCodeHotspotConnectionFailed = 4001,
/// Photo data for scene recognition handle failed due to bad command
  ABMateSdkErrorCodePhotoDataForSceneRecognitionHandleFailedDueToBadCommand = 5001,
/// Photo data for scene recognition handle failed due to invalid status code
  ABMateSdkErrorCodePhotoDataForSceneRecognitionHandleFailedDueToInvalidStatusCode = 5002,
/// Photo data for scene recognition transfer canceled due to system capture failed
  ABMateSdkErrorCodePhotoDataForSceneRecognitionTransferCanceledDueToSystemCaptureFailed = 5003,
/// Photo data for scene recognition transfer canceled due to Bluetooth communication error
  ABMateSdkErrorCodePhotoDataForSceneRecognitionTransferCanceledDueToBluetoothCommunicationError = 5004,
/// Fetch media files info failed due to local network usage description missing
  ABMateSdkErrorCodeFetchMediaFilesInfoFailedDueToLocalNetworkUsageDescMissing = 6000,
/// File import not ready
  ABMateSdkErrorCodeFileImportNotReady = 6001,
/// File import already in progress
  ABMateSdkErrorCodeFileImportAlreadyInProgress = 6002,
/// File import not in progress
  ABMateSdkErrorCodeFileImportNotInProgress = 6003,
/// Fetch media file infos failed due to hotspot configure error
  ABMateSdkErrorCodeFetchMediaFileInfosFailedDueToHotspotConfigureError = 6004,
/// File import task prepare failed due to enter file transfer mode failed
  ABMateSdkErrorCodeFileImportTaskPrepareFailedDueToEnterFileTransferModeFailed = 6005,
/// Fetch media file infos failed due to hotspot connection failure
  ABMateSdkErrorCodeFetchMediaFileInfosFailedDueToHotspotConnectionFailure = 6006,
/// Fetch media file infos failed due to empty base url
  ABMateSdkErrorCodeFetchMediaFileInfosFailedDueToEmptyBaseUrl = 6007,
/// Fetch media file infos failed due to invalid config file url
  ABMateSdkErrorCodeFetchMediaFileInfosFailedDueToInvalidConfigUrl = 6008,
/// Fetch media file infos failed due to config file error
  ABMateSdkErrorCodeFetchMediaFileInfosFailedDueToConfigFileError = 6009,
/// Fetch media file infos failed due to network error
  ABMateSdkErrorCodeFetchMediaFileInfosFailedDueToNetworkError = 6010,
/// Fetch media file infos failed due to invalid response
  ABMateSdkErrorCodeFetchMediaFileInfosFailedDueToInvalidResponse = 6011,
/// Fetch media file infos failed due to HTTP error code not success range
  ABMateSdkErrorCodeFetchMediaFileInfosFailedDueToHttpError = 6012,
/// Import files failed due to device connection lost
  ABMateSdkErrorCodeImportFilesFailedDueToDeviceHotspotConnectionLost = 6013,
/// Import files failed due to invalid url
  ABMateSdkErrorCodeImportFilesFailedDueToInvalidUrl = 6014,
/// Import files failed due to HTTP error code not success range
  ABMateSdkErrorCodeImportFilesFailedDueToHttpError = 6015,
/// Import files failed due to network error
  ABMateSdkErrorCodeImportFilesFailedDueToNetworkError = 6016,
/// Fetch media files info failed due to allow local networking missing
  ABMateSdkErrorCodeFetchMediaFilesInfoFailedDueToAllowLocalNetworkingMissing = 6017,
/// Prompt script is invalid or empty
  ABMateSdkErrorCodePromptScriptInvalidOrEmpty = 7001,
/// Prompt script is sending
  ABMateSdkErrorCodePromptScriptIsSending = 7002,
/// Prompt script sending failed
  ABMateSdkErrorCodePromptScriptSendingFailed = 7003,
/// Prompt script sending failed due to device disconnected
  ABMateSdkErrorCodePromptScriptSendingFailedDueToDeviceDisconnect = 7004,
};

/// The error codes used for ABMateSDK ota errors
typedef SWIFT_ENUM_NAMED(NSInteger, ABMateSdkOtaErrorCode, "SdkOtaErrorCode", open) {
/// Unknown error
  ABMateSdkOtaErrorCodeUnknown = -1,
/// OTA task already running
  ABMateSdkOtaErrorCodeOtaTaskAlreadyRunning = 4001,
/// OTA task create failed due to file not found
  ABMateSdkOtaErrorCodeOtaTaskCreateFailedDueToFileNotFound = 4002,
/// OTA task start failed due to file read error
  ABMateSdkOtaErrorCodeOtaTaskStartFailedDueToFileReadError = 4003,
/// OTA task start failed due to file handle create error
  ABMateSdkOtaErrorCodeOtaTaskStartFailedDueToFileHandleCreateError = 4004,
/// OTA task start failed due to invalid file hash data
  ABMateSdkOtaErrorCodeOtaTaskStartFailedDueToInvalidFileHashData = 4005,
/// OTA task start failed due to get ota info error
  ABMateSdkOtaErrorCodeOtaTaskStartFailedDueToGetOtaInfoError = 4006,
/// OTA task start failed due to invalid offset address
  ABMateSdkOtaErrorCodeOtaTaskStartFailedDueToInvalidOffsetAddress = 4007,
/// OTA task start failed due to invalid block size
  ABMateSdkOtaErrorCodeOtaTaskStartFailedDueToInvalidBlockSize = 4008,
/// OTA task start failed due to not allow update
  ABMateSdkOtaErrorCodeOtaTaskStartFailedDueToNotAllowUpdate = 4009,
/// OTA task send data failed due to file handle is nil
  ABMateSdkOtaErrorCodeOtaTaskSendDataFailedDueToFileHandleIsNil = 4010,
/// OTA task send data failed due to seek file handle failed
  ABMateSdkOtaErrorCodeOtaTaskSendDataFailedDueToSeekFileHandleFailed = 4011,
/// OTA task send data failed due to read file data failed
  ABMateSdkOtaErrorCodeOtaTaskSendDataFailedDueToReadFileDataFailed = 4012,
/// OTA task send data failed due to ota info is nil
  ABMateSdkOtaErrorCodeOtaTaskSendDataFailedDueToOtaInfoIsNil = 4013,
/// OTA task failed due to device report key mismatch
  ABMateSdkOtaErrorCodeOtaTaskFailedDueToDeviceReportKeyMismatch = 4014,
/// OTA task failed due to device report crc error
  ABMateSdkOtaErrorCodeOtaTaskFailedDueToDeviceReportCrcError = 4015,
/// OTA task failed due to device report seq error
  ABMateSdkOtaErrorCodeOtaTaskFailedDueToDeviceReportSeqError = 4016,
/// OTA task failed due to device report data length error
  ABMateSdkOtaErrorCodeOtaTaskFailedDueToDeviceReportDataLengthError = 4017,
/// OTA task failed due to device disconnect
  ABMateSdkOtaErrorCodeOtaTaskFailedDueToDeviceDisconnect = 4018,
/// OTA task failed due to timeout
  ABMateSdkOtaErrorCodeOtaTaskFailedDueToTimeout = 4019,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
