#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef AIBUDSMAGICHELPER_SWIFT_H
#define AIBUDSMAGICHELPER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsMagicHelper",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AIBudsAI;
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsMagicHelper",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Enumeration for AIGC (AI Generated Content) error codes
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkAigcErrorCode, "AigcErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkAigcErrorCodeUnknown = -1,
/// SDK not initialized or initialized failed.
  AIBudsMagicHelperSdkAigcErrorCodeSdkNotInitialized = 1,
/// Invalid parameter
  AIBudsMagicHelperSdkAigcErrorCodeInvalidParameter = 2,
/// Bad server response
  AIBudsMagicHelperSdkAigcErrorCodeBadServerResponse = 3,
/// Generation failed
  AIBudsMagicHelperSdkAigcErrorCodeGenerationFailed = 201,
/// Content is intercepted due to profanity
  AIBudsMagicHelperSdkAigcErrorCodeContentInterceptedDueToProfanity = 501,
/// Content is intercepted due to copyright
  AIBudsMagicHelperSdkAigcErrorCodeContentInterceptedDueToCopyright = 503,
/// Server internal error
  AIBudsMagicHelperSdkAigcErrorCodeServerInternalError = 282000,
/// Missing required parameter
  AIBudsMagicHelperSdkAigcErrorCodeMissingRequiredParameter = 282003,
/// Text or image blocked by moderation: the request contains sensitive words, illegal parameters, exceeds the character limit, or includes a prohibited reference image; please review and try again.
  AIBudsMagicHelperSdkAigcErrorCodeContentInterceptedDueToOtherReason = 282004,
/// Parameter does not satisfy the format requirements.
  AIBudsMagicHelperSdkAigcErrorCodeParameterFormatNotSatisfied = 216100,
/// Reference image format not satisfied.
  AIBudsMagicHelperSdkAigcErrorCodeReferenceImageFormatNotSatisfied = 216201,
/// Task timeout
  AIBudsMagicHelperSdkAigcErrorCodeTaskTimeout = 216303,
/// Parameter <code>change_degree</code> does not exist in the request.
  AIBudsMagicHelperSdkAigcErrorCodeParameterChangeDegreeNotFound = 216630,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkAigcErrorCodeInternetConnectionOffline = 9999,
};

/// Enumeration for ASR (Automatic Speech Recognition) error codes
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkAsrErrorCode, "AsrErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkAsrErrorCodeUnknown = -1,
/// SDK not initialized or initialized failed.
  AIBudsMagicHelperSdkAsrErrorCodeSdkNotInitialized = 1,
/// Invalid parameter
  AIBudsMagicHelperSdkAsrErrorCodeInvalidParameter = 2,
/// Bad server response
  AIBudsMagicHelperSdkAsrErrorCodeBadServerResponse = 3,
/// Recognize the speech failed for voice empty or any other reason.
  AIBudsMagicHelperSdkAsrErrorCodeRecognizeFailed = 4,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkAsrErrorCodeInternetConnectionOffline = 9999,
};

/// Enumeration for GPT (Generative Pre-trained Transformer) error codes
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkGptErrorCode, "GptErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkGptErrorCodeUnknown = -1,
/// SDK not initialized or initialized failed.
  AIBudsMagicHelperSdkGptErrorCodeSdkNotInitialized = 1,
/// Invalid parameter
  AIBudsMagicHelperSdkGptErrorCodeInvalidParameter = 2,
/// Bad server response
  AIBudsMagicHelperSdkGptErrorCodeBadServerResponse = 3,
/// Bad request
  AIBudsMagicHelperSdkGptErrorCodeBadRequest = 400,
/// Authentication failed
  AIBudsMagicHelperSdkGptErrorCodeAuthenticationFailed = 401,
/// Permission denied
  AIBudsMagicHelperSdkGptErrorCodePermissionDenied = 403,
/// Not found
  AIBudsMagicHelperSdkGptErrorCodeNotFound = 404,
/// Unprocessable entity
  AIBudsMagicHelperSdkGptErrorCodeUnprocessableEntity = 422,
/// Rate limit exceeded
  AIBudsMagicHelperSdkGptErrorCodeRateLimitExceeded = 429,
/// Content intercepted due to violation
  AIBudsMagicHelperSdkGptErrorCodeContentInterceptedDueToViolation = 430,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkGptErrorCodeInternetConnectionOffline = 9999,
};

/// Enumeration for initialization error codes
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkInitErrorCode, "InitErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkInitErrorCodeUnknown = -1,
/// The SDK does not conform to ATS (App Transport Security) policy, and <code>NSAllowsArbitraryLoads</code> is not to true in Info.plist.
  AIBudsMagicHelperSdkInitErrorCodeNotAllowsArbitraryLoads = 0,
/// Invalid parameter
  AIBudsMagicHelperSdkInitErrorCodeInvalidParameter = 2,
/// Bad server response
  AIBudsMagicHelperSdkInitErrorCodeBadServerResponse = 3,
/// Parameter <code>ak</code> does not exist in the request.
  AIBudsMagicHelperSdkInitErrorCodeParameterAKNotFound = 101,
/// Parameter <code>sn</code> does not exist in the request.
  AIBudsMagicHelperSdkInitErrorCodeParameterSNNotFound = 102,
/// Device prohibited.
  AIBudsMagicHelperSdkInitErrorCodeDeviceProhibited = 104,
/// Channel prohibited.
  AIBudsMagicHelperSdkInitErrorCodeChannelProhibited = 106,
/// Service not enabled.
  AIBudsMagicHelperSdkInitErrorCodeServiceNotEnabled = 107,
/// Parameter validation failed.
  AIBudsMagicHelperSdkInitErrorCodeParameterValidationFailed = 108,
/// Need to check the details message for more information.
  AIBudsMagicHelperSdkInitErrorCodeNeedToCheckDetailsMessage = 111,
/// Device not registered, Please contact TopStep support.
  AIBudsMagicHelperSdkInitErrorCodeDeviceNotRegistered = 500,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkInitErrorCodeInternetConnectionOffline = 9999,
};

@protocol AIBudsMltCloudBridgePlugin;
/// The main entry point for the MagicHelperSDK.
/// Use this class to access SDK version information and other global SDK-level functionality.
SWIFT_CLASS_NAMED("MagicHelperSDK")
@interface AIBudsMagicHelperSDK : NSObject
/// The shared singleton instance of MagicHelperSDK
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsMagicHelperSDK * _Nonnull shared;)
+ (AIBudsMagicHelperSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of MagicHelperSDK
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The bridge plugin used to connect AIBuds devices to MltCloud services.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <AIBudsMltCloudBridgePlugin> _Nonnull bridgePlugin;)
+ (id <AIBudsMltCloudBridgePlugin> _Nonnull)bridgePlugin SWIFT_WARN_UNUSED_RESULT;
@end

@class NSString;
@interface AIBudsMagicHelperSDK (SWIFT_EXTENSION(AIBudsMagicHelper))
/// The error domain used for AIBudsStarBurstSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorDomain;)
+ (NSString * _Nonnull)ErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// The error key used for AIBudsStarBurstSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorKey;)
+ (NSString * _Nonnull)ErrorKey SWIFT_WARN_UNUSED_RESULT;
/// Error domain for initialization errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull InitErrorDomain;)
+ (NSString * _Nonnull)InitErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// Error domain for ASR (Automatic Speech Recognition) related errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AsrErrorDomain;)
+ (NSString * _Nonnull)AsrErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// Error domain for AIGC (AI Generated Content) related errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AigcErrorDomain;)
+ (NSString * _Nonnull)AigcErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// Error domain for GPT (Generative Pre-trained Transformer) related errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull GptErrorDomain;)
+ (NSString * _Nonnull)GptErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// Error domain for TTS (Text-to-Speech) related errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull TTSErrorDomain;)
+ (NSString * _Nonnull)TTSErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// Error domain for translation related errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull TranslateErrorDomain;)
+ (NSString * _Nonnull)TranslateErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// Error domain for summary related errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SummaryErrorDomain;)
+ (NSString * _Nonnull)SummaryErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// Error domain for simultaneous interpretation related errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SimultaneousInterpretationErrorDomain;)
+ (NSString * _Nonnull)SimultaneousInterpretationErrorDomain SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsAIServiceVendor)
@class AIBudsAIServiceLanguage;
SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsAIAuthenticationMode)
@protocol AIBudsAIAuthenticationServiceAPI;
@protocol AIBudsAIChatServiceAPI;
@protocol AIBudsAITextTranslationServiceAPI;
@protocol AIBudsSimultaneousInterpretationServiceAPI;
@protocol AIBudsAISummaryServiceAPI;
@protocol AIBudsAIAudioRecordingServiceAPI;
@protocol AIBudsStreamingASRServiceAPI;
@protocol AIBudsTTSServiceAPI;
@protocol AIBudsAIGCServiceAPI;
@protocol AIBudsAIAskingServiceAPI;
@interface AIBudsMagicHelperSDK (SWIFT_EXTENSION(AIBudsMagicHelper)) <AIBudsAIConnectSDK>
/// The version number of the SDK
///
/// returns:
/// A string representing the current SDK version (e.g. “1.0.0-beta.1”)
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
/// The build number of the SDK
///
/// returns:
/// A string representing the SDK build number (e.g. “20250315001”)
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkBuild;
/// The release date of the SDK
///
/// returns:
/// A string representing the SDK release date in YYYY-MM-DD format
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkReleaseDate;
/// Returns a formatted string containing SDK version information
/// note:
/// The returned string includes an emoji prefix and is formatted for easy reading
///
/// returns:
/// A string containing the SDK name, version, build number and release date
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersionDescription;
/// The name of the SDK
///
/// returns:
/// A string representing the SDK name (e.g. “StarBurstSDK”)
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkName;
/// The name of the SDK vendor
///
/// returns:
/// A string representing the SDK provider name (e.g. “ByteDance”)
@property (nonatomic, readonly, copy) NSString * _Nonnull vendorName;
/// The SDK vendor
///
/// returns:
/// An AIServiceVendor value indicating the type of service provider (e.g. .byteDance)
@property (nonatomic, readonly) enum AIBudsAIServiceVendor vendor;
/// The supported languages for the service provider
///
/// returns:
/// An array of AIServiceLanguage objects representing the supported languages
@property (nonatomic, readonly, copy) NSArray<AIBudsAIServiceLanguage *> * _Nonnull allSupportedLanguages;
/// The authentication initiation mode for the ai service.
///
/// returns:
/// A AIAuthenticationMode value indicating the authentication initiation mode (e.g. .deviceInitiated)
@property (nonatomic, readonly) enum AIBudsAIAuthenticationMode authenticationMode;
/// Indicates whether the device is authenticated for the service provider
///
/// returns:
/// A boolean value indicating whether the device is authenticated
@property (nonatomic, readonly) BOOL isAuthenticated;
/// The authentication service interface for the service provider
///
/// returns:
/// An object conforming to AIAuthenticationServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAIAuthenticationServiceAPI> _Nullable aiAuthenticationService;
/// The chat service interface for the service provider
///
/// returns:
/// An object conforming to AIChatServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAIChatServiceAPI> _Nullable aiChatService;
/// The text translation service interface for the service provider
///
/// returns:
/// An object conforming to AITextTranslationAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAITextTranslationServiceAPI> _Nullable textTranslationService;
/// The simultaneous interpretation service interface for the service provider
///
/// returns:
/// An object conforming to SimultaneousInterpretationService if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsSimultaneousInterpretationServiceAPI> _Nullable simultaneousInterpretationService;
/// The summary service interface for the service provider
///
/// returns:
/// An object conforming to AISummaryAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAISummaryServiceAPI> _Nullable aiSummaryService;
/// The audio recording service interface for the service provider
///
/// returns:
/// An object conforming to AIAudioRecordingAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAIAudioRecordingServiceAPI> _Nullable aiAudioRecordingService;
/// The streaming ASR service interface for the service provider
///
/// returns:
/// An object conforming to StreamingASRServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsStreamingASRServiceAPI> _Nullable streamingASRService;
/// The TTS service interface for the service provider
///
/// returns:
/// An object conforming to TTSServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsTTSServiceAPI> _Nullable ttsService;
/// The AIGC service interface for the service provider
///
/// returns:
/// An object conforming to AIGCServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAIGCServiceAPI> _Nullable aigcService;
/// The AI asking service interface for the service provider.
@property (nonatomic, readonly, strong) id <AIBudsAIAskingServiceAPI> _Nullable aiAskingService;
@end

/// The error codes used for AIBudsMagicHelperSDK errors
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkErrorCode, "SdkErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkErrorCodeUnknown = -1,
/// The SDK does not conform to ATS (App Transport Security) policy, and <code>NSAllowsArbitraryLoads</code> is not to true in Info.plist.
  AIBudsMagicHelperSdkErrorCodeNotAllowsArbitraryLoads = 0,
/// SDK not initialized or initialized failed.
  AIBudsMagicHelperSdkErrorCodeSdkNotInitialized = 1,
/// Device not registered, Please contact TopStep support.
  AIBudsMagicHelperSdkErrorCodeDeviceNotRegistered = 2,
/// Device prohibited.
  AIBudsMagicHelperSdkErrorCodeDeviceProhibited = 3,
/// Channel prohibited.
  AIBudsMagicHelperSdkErrorCodeChannelProhibited = 4,
/// Service not enabled.
  AIBudsMagicHelperSdkErrorCodeServiceNotEnabled = 5,
/// Invalid parameter
  AIBudsMagicHelperSdkErrorCodeInvalidParameter = 6,
/// Bad server response
  AIBudsMagicHelperSdkErrorCodeBadServerResponse = 7,
/// Server internal error
  AIBudsMagicHelperSdkErrorCodeServerInternalError = 8,
/// Task timeout
  AIBudsMagicHelperSdkErrorCodeTaskTimeout = 9,
/// Generation failed for AI photo
  AIBudsMagicHelperSdkErrorCodeAiPhotoGenerationFailed = 10,
/// Content is intercepted due to profanity
  AIBudsMagicHelperSdkErrorCodeContentInterceptedDueToProfanity = 11,
/// Content is intercepted due to copyright
  AIBudsMagicHelperSdkErrorCodeContentInterceptedDueToCopyright = 12,
/// Text or image blocked by moderation: the request contains sensitive words, illegal parameters, exceeds the character limit, or includes a prohibited reference image; please review and try again.
  AIBudsMagicHelperSdkErrorCodeContentInterceptedDueToOtherReason = 13,
/// Reference image format not satisfied.
  AIBudsMagicHelperSdkErrorCodeReferenceImageFormatNotSatisfied = 14,
/// Recognize the speech failed for voice empty or any other reason.
  AIBudsMagicHelperSdkErrorCodeRecognizeFailed = 15,
/// Failed to save audio file
  AIBudsMagicHelperSdkErrorCodeAudioFileSaveFailed = 16,
/// Need to check the details message for more information.
  AIBudsMagicHelperSdkErrorCodeNeedToCheckDetailsMessage = 17,
/// Invalid response
  AIBudsMagicHelperSdkErrorCodeInvalidResponse = 18,
/// Authentication failed
  AIBudsMagicHelperSdkErrorCodeAuthenticationFailed = 1001,
/// Insufficient quota
  AIBudsMagicHelperSdkErrorCodeInsufficientQuota = 1002,
/// Service failed due to the sdk is not authenticated
  AIBudsMagicHelperSdkErrorCodeServiceFailedDueToSdkNotAuthenticated = 1003,
/// Busy, please wait for the previous request to complete
  AIBudsMagicHelperSdkErrorCodeBusy = 1004,
/// Microphone usage description not configured in the Info.plist
  AIBudsMagicHelperSdkErrorCodeMicrophoneUsageDescriptionNotConfigured = 1005,
/// Microphone permission denied by the user
  AIBudsMagicHelperSdkErrorCodeMicrophonePermissionDenied = 1006,
/// Streaming voice player start failed
  AIBudsMagicHelperSdkErrorCodeStreamingVoicePlayerStartFailed = 1007,
/// Generate summary failed
  AIBudsMagicHelperSdkErrorCodeGenerateSummaryFailed = 3001,
/// Translate failed due to the target language is empty
  AIBudsMagicHelperSdkErrorCodeTranslateFailedDueToTargetLanguageEmpty = 4001,
/// Translate failed
  AIBudsMagicHelperSdkErrorCodeTranslateFailed = 4002,
/// Start simultaneous interpretation failed due to the target language is empty
  AIBudsMagicHelperSdkErrorCodeStartSimultaneousInterpretationFailedDueToTargetLanguageEmpty = 5001,
/// Start simultaneous interpretation failed due to the source language is same as target language
  AIBudsMagicHelperSdkErrorCodeStartSimultaneousInterpretationFailedDueToSourceLanguageSameAsTargetLanguage = 5002,
/// Start simultaneous interpretation failed due to the record error
  AIBudsMagicHelperSdkErrorCodeStartSimultaneousInterpretationFailedDueToRecordError = 5003,
/// Simultaneous interpretation stopped unexpectedly
  AIBudsMagicHelperSdkErrorCodeSimultaneousInterpretationStoppedUnexpectedly = 5004,
/// BLE disconnected during simultaneous interpretation
  AIBudsMagicHelperSdkErrorCodeBleDisconnectedDuringSimultaneousInterpretation = 5005,
/// WebSocket disconnected during simultaneous interpretation
  AIBudsMagicHelperSdkErrorCodeWebsocketDisconnectedDuringSimultaneousInterpretation = 5006,
/// WebSocket ping timeout during simultaneous interpretation
  AIBudsMagicHelperSdkErrorCodeWebsocketPingTimeoutDuringSimultaneousInterpretation = 5007,
/// Network error during simultaneous interpretation
  AIBudsMagicHelperSdkErrorCodeNetworkErrorDuringSimultaneousInterpretation = 5008,
/// Start AI-Chat failed due to unable to start the SCO audio capturer
  AIBudsMagicHelperSdkErrorCodeStartAIChatFailedDueToUnableToStartSCOAudioCapturer = 6001,
/// BLE disconnected during AI-Chat session
  AIBudsMagicHelperSdkErrorCodeBleDisconnectedDuringAIChatSession = 6002,
/// WebSocket disconnected during AI-Chat session
  AIBudsMagicHelperSdkErrorCodeWebsocketDisconnectedDuringAIChatSession = 6003,
/// WebSocket ping timeout during AI-Chat session
  AIBudsMagicHelperSdkErrorCodeWebsocketPingTimeoutDuringAIChatSession = 6004,
/// Network error during AI-Chat session
  AIBudsMagicHelperSdkErrorCodeNetworkErrorDuringAIChatSession = 6005,
/// ASR error with single word unrecognized during AI-Chat session
  AIBudsMagicHelperSdkErrorCodeAsrErrorWithSingleWordUnrecognized = 6006,
/// Unknown server error during AI-Chat session
  AIBudsMagicHelperSdkErrorCodeUnknownServerErrorDuringAIChatSession = 6007,
/// AI-Chat session config internal error
  AIBudsMagicHelperSdkErrorCodeAiChatSessionConfigInternalError = 6008,
/// Start AI audio recording failed due to the language for speech input is empty
  AIBudsMagicHelperSdkErrorCodeStartAIAudioRecordingFailedDueToLanguageForSpeechInputEmpty = 7001,
/// BLE disconnected during AI audio recording
  AIBudsMagicHelperSdkErrorCodeBleDisconnectedDuringAIAudioRecording = 7002,
/// WebSocket disconnected during AI audio recording
  AIBudsMagicHelperSdkErrorCodeWebsocketDisconnectedDuringAIAudioRecording = 7003,
/// WebSocket ping timeout during AI audio recording
  AIBudsMagicHelperSdkErrorCodeWebsocketPingTimeoutDuringAIAudioRecording = 7004,
/// Network error during AI audio recording
  AIBudsMagicHelperSdkErrorCodeNetworkErrorDuringAIAudioRecording = 7005,
/// Recognize voice data failed due to unable to resolve fed data
  AIBudsMagicHelperSdkErrorCodeRecognizeVoiceDataFailedDueToUnableToResolveFedData = 8001,
/// Recognize voice data failed due to audio file not found
  AIBudsMagicHelperSdkErrorCodeRecognizeVoiceDataFailedDueToAudioFileNotFound = 8002,
/// BLE disconnected during streaming ASR
  AIBudsMagicHelperSdkErrorCodeBleDisconnectedDuringStreamingASR = 8003,
/// WebSocket disconnected during streaming ASR
  AIBudsMagicHelperSdkErrorCodeWebsocketDisconnectedDuringStreamingASR = 8004,
/// WebSocket ping timeout during streaming ASR
  AIBudsMagicHelperSdkErrorCodeWebsocketPingTimeoutDuringStreamingASR = 8005,
/// Network error during streaming ASR
  AIBudsMagicHelperSdkErrorCodeNetworkErrorDuringStreamingASR = 8006,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkErrorCodeInternetConnectionOffline = 9999,
};

/// Enumeration for Simultaneous Interpretation error codes
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkSimultaneousInterpretationErrorCode, "SimultaneousInterpretationErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkSimultaneousInterpretationErrorCodeUnknown = -1,
/// SDK not initialized or initialized failed.
  AIBudsMagicHelperSdkSimultaneousInterpretationErrorCodeSdkNotInitialized = 1,
/// Invalid parameter
  AIBudsMagicHelperSdkSimultaneousInterpretationErrorCodeInvalidParameter = 2,
/// Bad server response
  AIBudsMagicHelperSdkSimultaneousInterpretationErrorCodeBadServerResponse = 3,
/// Invalid URL
  AIBudsMagicHelperSdkSimultaneousInterpretationErrorCodeInvalidURL = 1003,
/// Network request failed
  AIBudsMagicHelperSdkSimultaneousInterpretationErrorCodeNetworkRequestFailed = 1004,
/// Server error
  AIBudsMagicHelperSdkSimultaneousInterpretationErrorCodeServerError = 1005,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkSimultaneousInterpretationErrorCodeInternetConnectionOffline = 9999,
};

/// Enumeration for Summary error codes
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkSummaryErrorCode, "SummaryErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkSummaryErrorCodeUnknown = -1,
/// SDK not initialized or initialized failed.
  AIBudsMagicHelperSdkSummaryErrorCodeSdkNotInitialized = 1,
/// Invalid parameter
  AIBudsMagicHelperSdkSummaryErrorCodeInvalidParameter = 2,
/// Bad server response
  AIBudsMagicHelperSdkSummaryErrorCodeBadServerResponse = 3,
/// Invalid URL
  AIBudsMagicHelperSdkSummaryErrorCodeInvalidURL = 1003,
/// Network request failed
  AIBudsMagicHelperSdkSummaryErrorCodeNetworkRequestFailed = 1004,
/// Server error
  AIBudsMagicHelperSdkSummaryErrorCodeServerError = 1005,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkSummaryErrorCodeInternetConnectionOffline = 9999,
};

/// Enumeration for Text-to-Speech error codes
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkTTSErrorCode, "TTSErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkTTSErrorCodeUnknown = -1,
/// SDK not initialized or initialized failed.
  AIBudsMagicHelperSdkTTSErrorCodeSdkNotInitialized = 1,
/// Invalid parameter
  AIBudsMagicHelperSdkTTSErrorCodeInvalidParameter = 2,
/// Bad server response
  AIBudsMagicHelperSdkTTSErrorCodeBadServerResponse = 3,
/// Failed to save audio file
  AIBudsMagicHelperSdkTTSErrorCodeAudioFileSaveFailed = 1001,
/// Failed to convert audio
  AIBudsMagicHelperSdkTTSErrorCodeAudioConversionFailed = 1002,
/// Invalid URL
  AIBudsMagicHelperSdkTTSErrorCodeInvalidURL = 1003,
/// Network request failed
  AIBudsMagicHelperSdkTTSErrorCodeNetworkRequestFailed = 1004,
/// Server error
  AIBudsMagicHelperSdkTTSErrorCodeServerError = 1005,
/// File not found
  AIBudsMagicHelperSdkTTSErrorCodeFileNotFound = 1006,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkTTSErrorCodeInternetConnectionOffline = 9999,
};

/// Enumeration for translation error codes
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMagicHelperSdkTranslateErrorCode, "TranslateErrorCode", open) {
/// Unknown error
  AIBudsMagicHelperSdkTranslateErrorCodeUnknown = -1,
/// SDK not initialized or initialized failed.
  AIBudsMagicHelperSdkTranslateErrorCodeSdkNotInitialized = 1,
/// Invalid parameter
  AIBudsMagicHelperSdkTranslateErrorCodeInvalidParameter = 2,
/// Bad server response
  AIBudsMagicHelperSdkTranslateErrorCodeBadServerResponse = 3,
/// The Internet connection appears to be offline.
  AIBudsMagicHelperSdkTranslateErrorCodeInternetConnectionOffline = 9999,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
