#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.1 effective-5.10 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)
#ifndef AIBUDSFOUNDATION_SWIFT_H
#define AIBUDSFOUNDATION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsFoundation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsFoundation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class AIBudsStarBurstAIAuthParams;
@class AIBudsMltCloudAIAuthParams;
@class NSString;
@class NSCoder;
/// Parameters required to authenticate a device with a AI service vendor.
SWIFT_CLASS_NAMED("AIAuthParams")
@interface AIBudsAIAuthParams : NSObject <NSSecureCoding>
/// StarBurst AI authentication parameters.
/// <blockquote>
/// Important: This value is required when connecting devices that support StarBurst AI features.
///
/// </blockquote>
@property (nonatomic, strong) AIBudsStarBurstAIAuthParams * _Nullable starburst;
/// MltCloud AI authentication parameters.
/// <blockquote>
/// Important: This value is required when connecting devices that support MltCloud AI features.
///
/// </blockquote>
@property (nonatomic, strong) AIBudsMltCloudAIAuthParams * _Nullable mltcloud;
/// Initializes a new instance of the <code>AIAuthParams</code> class.
/// This initializer creates a new instance of the <code>AIAuthParams</code> class with default values for all properties.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Description of the authentication parameters.
/// This property provides a string description of the authentication parameters,
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// AI Chat Session Channel
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsAIChatAudioChannel, "AIChatAudioChannel", open) {
/// SCO (Synchronous Connection-Oriented) channel
  AIBudsAIChatAudioChannelSco = 0,
/// Opus encoded input, A2DP output channel
  AIBudsAIChatAudioChannelOpusInA2dpOut = 1,
/// Opus encoded input, Opus encoded output channel
  AIBudsAIChatAudioChannelOpusInOpusOut = 2,
};

/// AI chat session event
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsAIChatSessionEvent, "AIChatSessionEvent", open) {
/// Terminate current AI chat session
  AIBudsAIChatSessionEventTerminate = 0,
/// Initiate new AI chat session via SCO
  AIBudsAIChatSessionEventInitiateWithSCO = 1,
/// Initiate new AI chat session via Opus
  AIBudsAIChatSessionEventInitiateWithOpus = 2,
/// Interrupt AI chat session due to state conflict
  AIBudsAIChatSessionEventInterruptByStateConflict = 0xff,
};

/// AI image resolution mode
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsAIImageResolutionMode, "AIImageResolutionMode", open) {
/// Fastest speed
  AIBudsAIImageResolutionModeUltraFast = 0,
/// Speed priority
  AIBudsAIImageResolutionModeSpeed = 1,
/// Balanced towards speed
  AIBudsAIImageResolutionModeBalancedSpeed = 2,
/// Balanced towards quality
  AIBudsAIImageResolutionModeBalancedQuality = 3,
/// Quality priority
  AIBudsAIImageResolutionModeQuality = 4,
/// Highest quality
  AIBudsAIImageResolutionModeUltraQuality = 5,
};

/// Active Noise Cancellation mode
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsANCMode, "ANCMode", open) {
/// Unknown mode
  AIBudsANCModeUnknown = -1,
/// Normal mode (noise cancellation off)
  AIBudsANCModeNormal = 0,
/// Noise cancellation mode
  AIBudsANCModeAnc = 1,
/// Transparency mode
  AIBudsANCModeTransparency = 2,
};

/// Represents the range of values for the dynamic bass engine.
SWIFT_CLASS_NAMED("BassEngineRange")
@interface AIBudsBassEngineRange : NSObject
/// The minimum value for the dynamic bass engine.
@property (nonatomic, readonly) NSInteger minValue;
/// The maximum value for the dynamic bass engine.
@property (nonatomic, readonly) NSInteger maxValue;
- (nonnull instancetype)initWithMinValue:(NSInteger)minValue maxValue:(NSInteger)maxValue OBJC_DESIGNATED_INITIALIZER;
/// A string representation of <code>BassEngineRange</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Enum for battery components, used to identify the battery status of different components in the device.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsBatteryComponent, "BatteryComponent", open) {
/// Unknown component
  AIBudsBatteryComponentUnknown = -1,
/// Glasses body
  AIBudsBatteryComponentGlass = 0,
/// Left earbud
  AIBudsBatteryComponentLeftEarbud = 1,
/// Right earbud
  AIBudsBatteryComponentRightEarbud = 2,
/// Charging case
  AIBudsBatteryComponentChargingCase = 3,
/// Main speaker
  AIBudsBatteryComponentMainSpeaker = 4,
/// Side speaker
  AIBudsBatteryComponentSideSpeaker = 5,
};

@class NSNumber;
SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsChargingState)
/// Battery information model.
SWIFT_CLASS_NAMED("BatteryInfoModel")
@interface AIBudsBatteryInfoModel : NSObject
/// Current battery level, expressed as an integer percentage (0–100).
/// A value of <code>nil</code> indicates the level is unknown or unavailable.
@property (nonatomic, readonly, strong) NSNumber * _Nonnull batteryLevel;
/// Current charging state of the battery.
@property (nonatomic, readonly) enum AIBudsChargingState chargingState;
/// Creates a new <code>BatteryInfoModel</code> instance.
/// \param batteryLevel The battery level percentage.
///
/// \param chargingState The current charging state.
///
- (nonnull instancetype)initWithBatteryLevel:(NSNumber * _Nonnull)batteryLevel chargingState:(enum AIBudsChargingState)chargingState OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AIBudsBatteryUnitInfoModel;
/// Battery status model describing real-time information for each battery component in the device.
SWIFT_CLASS_NAMED("BatteryStatusModel")
@interface AIBudsBatteryStatusModel : NSObject
/// An array containing real-time information for each battery unit in the device.
@property (nonatomic, readonly, copy) NSArray<AIBudsBatteryUnitInfoModel *> * _Nonnull units;
/// Creates a battery-status model from the provided battery-unit information.
/// \param units An array of <code>BatteryUnitInfoModel</code> instances describing each battery unit.
///
- (nonnull instancetype)initWithUnits:(NSArray<AIBudsBatteryUnitInfoModel *> * _Nonnull)units OBJC_DESIGNATED_INITIALIZER;
/// Retrieves detailed information for the specified battery component.
/// \param component The battery component to query.
///
///
/// returns:
/// The corresponding battery info, or <code>nil</code> if the component is absent.
- (AIBudsBatteryInfoModel * _Nullable)infoForComponent:(enum AIBudsBatteryComponent)component SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Battery unit information model, used to describe the battery component and its corresponding battery information.
SWIFT_CLASS_NAMED("BatteryUnitInfoModel")
@interface AIBudsBatteryUnitInfoModel : NSObject
/// Battery component type.
@property (nonatomic, readonly) enum AIBudsBatteryComponent component;
/// Detailed battery information.
@property (nonatomic, readonly, strong) AIBudsBatteryInfoModel * _Nonnull battery;
/// Initializes a battery unit information model with the specified battery component and battery information.
/// \param component The battery component.
///
/// \param battery The battery information.
///
- (nonnull instancetype)initWithComponent:(enum AIBudsBatteryComponent)component battery:(AIBudsBatteryInfoModel * _Nonnull)battery OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The ble protocol kind of the device.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsBleProtocolKind, "BleProtocolKind", open) {
/// None
  AIBudsBleProtocolKindNone = -1,
/// ABMate
  AIBudsBleProtocolKindAbmate = 0,
/// FitCloud Pro
  AIBudsBleProtocolKindFitcloudPro = 1,
/// W30
  AIBudsBleProtocolKindW30 = 2,
};

/// Call status enum
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsCallStatus, "CallStatus", open) {
/// Unknown
  AIBudsCallStatusUnknown = -1,
/// Not in call
  AIBudsCallStatusNotInCall = 0,
/// Ringing
  AIBudsCallStatusRinging = 1,
/// In call
  AIBudsCallStatusInCall = 2,
/// Three way ringing (if supported)
  AIBudsCallStatusThreeWayRinging = 3,
/// AI Chat
  AIBudsCallStatusAiChat = 4,
};

/// Camera OTA progress phase
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsCameraOtaProgressPhase, "CameraOtaProgressPhase", open) {
/// Transferring firmware file
  AIBudsCameraOtaProgressPhaseTransferring = 1,
/// Updating firmware
  AIBudsCameraOtaProgressPhaseFlashing = 2,
};

/// The capture mode used by the camera.
/// <ul>
///   <li>
///     In camera mode, the camera immediately captures a high-resolution image and stores it in the device’s storage.
///     If the camera is already on and in camera mode, sending this command again will take another photo.
///   </li>
///   <li>
///     In AI mode, the camera immediately captures a 320×240 JPEG image and pushes it to the phone via the AI image-push command.
///     After the push is complete, the camera turns off automatically.
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsCaptureMode, "CaptureMode", open) {
  AIBudsCaptureModeCamera = 0,
/// High-resolution, stored locally
  AIBudsCaptureModeAi = 1,
};

/// Charging state enumeration
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsChargingState, "ChargingState", open) {
/// Unknown charging state
  AIBudsChargingStateUnknown = -1,
/// Discharging state
  AIBudsChargingStateDischarging = 0,
/// Charging state
  AIBudsChargingStateCharging = 1,
};

/// Color-changing lens information model
SWIFT_CLASS_NAMED("ColorLensInfoModel")
@interface AIBudsColorLensInfoModel : NSObject
/// Number of supported color-changing lens levels
@property (nonatomic, readonly, strong) NSNumber * _Nonnull supportedLevelCount;
/// Current color-changing lens level
@property (nonatomic, readonly, strong) NSNumber * _Nonnull currentLevel;
/// Initialize with supported level count and current level
/// \param supportedLevelCount Number of supported color-changing lens levels
///
/// \param currentLevel Current color-changing lens level
///
- (nonnull instancetype)initWithSupportedLevelCount:(NSNumber * _Nonnull)supportedLevelCount currentLevel:(NSNumber * _Nonnull)currentLevel OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Parameters required to establish a connection.
SWIFT_CLASS_NAMED("ConnectParams")
@interface AIBudsConnectParams : NSObject <NSSecureCoding>
/// The unique identifier of the user.
/// This value is used to identify the user attempting to connect.
/// Only valid on devices that support binding a user ID.
@property (nonatomic, copy) NSString * _Nullable userId;
/// A randomly generated code for authentication or pairing purposes.
/// This code may be used to verify the connection request.
/// Only valid on devices that requires a random code.
@property (nonatomic, copy) NSString * _Nullable randomCode;
/// Whether to connect to Classic Bluetooth simultaneously.
/// Defaults to <code>true</code>. Set to <code>false</code> to use BLE only.
@property (nonatomic) BOOL enableClassicBT;
/// The AI authentication parameters.
/// This value is used to authenticate the user with AI features.
@property (nonatomic, strong) AIBudsAIAuthParams * _Nullable aiAuthParams;
/// Initializes a new instance of the <code>ConnectParams</code> class.
/// This initializer creates a new instance of the <code>ConnectParams</code> class with default values for all properties.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Description of the connection parameters.
/// This property provides a string description of the connection parameters,
/// including user ID, random code, Classic Bluetooth enablement, SDK type for StarBurst AI,
/// product ID for StarBurst AI, and PPE environment for StarBurst AI.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// Content display capability
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsContentDisplayCapability, "ContentDisplayCapability", open) {
/// None
  AIBudsContentDisplayCapabilityNone = 0,
/// Mono chrome display
  AIBudsContentDisplayCapabilityMonochrome = 1,
/// Color display
  AIBudsContentDisplayCapabilityColor = 2,
};

/// A protocol for objects that can provide a debug JSON string representation.
SWIFT_PROTOCOL_NAMED("CustomDebugJsonStringConvertible")
@protocol AIBudsCustomDebugJsonStringConvertible <NSObject>
/// The debug JSON string representation of the object.
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
@end

/// Device side application
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsDeviceApp, "DeviceApp", open) {
/// Home screen (cannot be used as a parameter for start/stop commands)
  AIBudsDeviceAppHomeScreen = 0x00,
/// Teleprompter
  AIBudsDeviceAppTeleprompter = 0x01,
/// AI Chat
  AIBudsDeviceAppAiChat = 0x02,
/// Navigation
  AIBudsDeviceAppNavigation = 0x03,
/// Clock
  AIBudsDeviceAppClock = 0x04,
/// Translation
  AIBudsDeviceAppTranslation = 0x05,
};

/// Device key function enumeration
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsDeviceFunction, "DeviceFunction", open) {
/// No effect
  AIBudsDeviceFunctionNone = 0,
/// Redial
  AIBudsDeviceFunctionRedial = 1,
/// Voice assistant
  AIBudsDeviceFunctionVoiceAssistant = 2,
/// Previous track
  AIBudsDeviceFunctionPreviousTrack = 3,
/// Next track
  AIBudsDeviceFunctionNextTrack = 4,
/// Volume up
  AIBudsDeviceFunctionVolumeUp = 5,
/// Volume down
  AIBudsDeviceFunctionVolumeDown = 6,
/// Play / Pause
  AIBudsDeviceFunctionPlayPause = 7,
/// Game mode
  AIBudsDeviceFunctionGameMode = 8,
/// Noise reduction
  AIBudsDeviceFunctionNoiseReduction = 9,
/// Take photo
  AIBudsDeviceFunctionTakePhoto = 10,
/// Continuous shooting
  AIBudsDeviceFunctionContinuousShooting = 11,
/// Video record start / stop
  AIBudsDeviceFunctionVideoRecordToggle = 12,
/// Audio record start / stop
  AIBudsDeviceFunctionAudioRecordToggle = 13,
/// Local / Bluetooth playback toggle
  AIBudsDeviceFunctionLocalBluetoothToggle = 14,
};

/// Device languages definition
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsDeviceLanguage, "DeviceLanguage", open) {
  AIBudsDeviceLanguageUnknown = -1,
  AIBudsDeviceLanguageEnglish = 0,
  AIBudsDeviceLanguageSimplifiedChinese = 1,
  AIBudsDeviceLanguageFrench = 2,
  AIBudsDeviceLanguageTraditionalChineseHK = 3,
  AIBudsDeviceLanguageGerman = 4,
  AIBudsDeviceLanguageRussian = 5,
  AIBudsDeviceLanguageSpanish = 6,
  AIBudsDeviceLanguagePortuguese = 7,
  AIBudsDeviceLanguageJapanese = 8,
  AIBudsDeviceLanguageArabic = 9,
  AIBudsDeviceLanguageDutch = 10,
  AIBudsDeviceLanguageItalian = 11,
  AIBudsDeviceLanguageCzech = 12,
  AIBudsDeviceLanguageDanish = 13,
  AIBudsDeviceLanguageGreek = 14,
  AIBudsDeviceLanguageHebrew = 15,
  AIBudsDeviceLanguageHindi = 16,
  AIBudsDeviceLanguageHungarian = 17,
  AIBudsDeviceLanguageIndonesian = 18,
  AIBudsDeviceLanguageKorean = 19,
  AIBudsDeviceLanguageMalay = 20,
  AIBudsDeviceLanguagePolish = 21,
  AIBudsDeviceLanguagePersian = 22,
  AIBudsDeviceLanguageSwedish = 23,
  AIBudsDeviceLanguageThai = 24,
  AIBudsDeviceLanguageVietnamese = 25,
  AIBudsDeviceLanguageSlovak = 26,
  AIBudsDeviceLanguageFinnish = 27,
  AIBudsDeviceLanguageIrish = 28,
  AIBudsDeviceLanguageRomanian = 29,
  AIBudsDeviceLanguageTurkish = 30,
  AIBudsDeviceLanguageCroatian = 31,
  AIBudsDeviceLanguageAlbanian = 32,
  AIBudsDeviceLanguageUkrainian = 33,
  AIBudsDeviceLanguageBulgarian = 34,
  AIBudsDeviceLanguageSlovenian = 35,
};

/// Device operations enumeration
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsDeviceOperation, "DeviceOperation", open) {
/// Unknown operation
  AIBudsDeviceOperationUnknown = -1,
/// Left single click
  AIBudsDeviceOperationLeftSingleClick = 0x01,
/// Right single click
  AIBudsDeviceOperationRightSingleClick = 0x02,
/// Left double click
  AIBudsDeviceOperationLeftDoubleClick = 0x03,
/// Right double click
  AIBudsDeviceOperationRightDoubleClick = 0x04,
/// Left triple click
  AIBudsDeviceOperationLeftTripleClick = 0x05,
/// Right triple click
  AIBudsDeviceOperationRightTripleClick = 0x06,
/// Left long press
  AIBudsDeviceOperationLeftLongPress = 0x07,
/// Right long press
  AIBudsDeviceOperationRightLongPress = 0x08,
/// Left touch single click
  AIBudsDeviceOperationLeftTouchSingleClick = 0x10,
/// Right touch single click
  AIBudsDeviceOperationRightTouchSingleClick = 0x11,
/// Left touch double click
  AIBudsDeviceOperationLeftTouchDoubleClick = 0x12,
/// Right touch double click
  AIBudsDeviceOperationRightTouchDoubleClick = 0x13,
/// Left touch long press
  AIBudsDeviceOperationLeftTouchLongPress = 0x14,
/// Right touch long press
  AIBudsDeviceOperationRightTouchLongPress = 0x15,
/// Left button 1 single click
  AIBudsDeviceOperationLeftButton1SingleClick = 0x16,
/// Right button 1 single click
  AIBudsDeviceOperationRightButton1SingleClick = 0x17,
/// Left button 1 double click
  AIBudsDeviceOperationLeftButton1DoubleClick = 0x18,
/// Right button 1 double click
  AIBudsDeviceOperationRightButton1DoubleClick = 0x19,
/// Left button 1 long press
  AIBudsDeviceOperationLeftButton1LongPress = 0x1A,
/// Right button 1 long press
  AIBudsDeviceOperationRightButton1LongPress = 0x1B,
/// Left button 2 single click
  AIBudsDeviceOperationLeftButton2SingleClick = 0x1C,
/// Right button 2 single click
  AIBudsDeviceOperationRightButton2SingleClick = 0x1D,
/// Left button 2 double click
  AIBudsDeviceOperationLeftButton2DoubleClick = 0x1E,
/// Right button 2 double click
  AIBudsDeviceOperationRightButton2DoubleClick = 0x1F,
/// Left button 2 long press
  AIBudsDeviceOperationLeftButton2LongPress = 0x20,
/// Right button 2 long press
  AIBudsDeviceOperationRightButton2LongPress = 0x21,
/// Touch slide backward to forward
  AIBudsDeviceOperationTouchSlideBackwardToForward = 0x22,
/// Touch slide forward to backward
  AIBudsDeviceOperationTouchSlideForwardToBackward = 0x23,
};

/// Device product category enumeration
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsDeviceProduct, "DeviceProduct", open) {
/// unknown
  AIBudsDeviceProductUnknown = -1,
/// smart watch
  AIBudsDeviceProductWatch = 0,
/// smart ring
  AIBudsDeviceProductRing = 1,
/// smart glasses
  AIBudsDeviceProductGlasses = 2,
/// charging case
  AIBudsDeviceProductChargingCase = 3,
/// earbuds
  AIBudsDeviceProductEarbuds = 4,
/// smart speaker
  AIBudsDeviceProductSpeaker = 5,
};

/// AIBuds device state enumeration
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsDeviceState, "DeviceState", open) {
/// Unknown
  AIBudsDeviceStateUnknown = -1,
/// Connecting
  AIBudsDeviceStateConnecting = 0,
/// Connected
  AIBudsDeviceStateConnected = 1,
/// Initializing
  AIBudsDeviceStateInitializing = 2,
/// Idle
  AIBudsDeviceStateIdle = 3,
/// Busy
  AIBudsDeviceStateBusy = 4,
/// Disconnecting
  AIBudsDeviceStateDisconnecting = 5,
/// Disconnected
  AIBudsDeviceStateDisconnected = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsDeviceVolumeType, "DeviceVolumeType", open) {
/// system prompt volume
  AIBudsDeviceVolumeTypeSystemPrompt = 0,
/// media-playback volume
  AIBudsDeviceVolumeTypeMedia = 1,
/// in-call volume
  AIBudsDeviceVolumeTypeCall = 2,
};

/// A model representing a equalizer configuration.
SWIFT_CLASS_NAMED("EQSettingModel")
@interface AIBudsEQSettingModel : NSObject
/// The default equalizer setting.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsEQSettingModel * _Nonnull defaultEQ;)
+ (AIBudsEQSettingModel * _Nonnull)defaultEQ SWIFT_WARN_UNUSED_RESULT;
/// The pop equalizer setting.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsEQSettingModel * _Nonnull pop;)
+ (AIBudsEQSettingModel * _Nonnull)pop SWIFT_WARN_UNUSED_RESULT;
/// The rock equalizer setting.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsEQSettingModel * _Nonnull rock;)
+ (AIBudsEQSettingModel * _Nonnull)rock SWIFT_WARN_UNUSED_RESULT;
/// The jazz equalizer setting.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsEQSettingModel * _Nonnull jazz;)
+ (AIBudsEQSettingModel * _Nonnull)jazz SWIFT_WARN_UNUSED_RESULT;
/// The classic equalizer setting.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsEQSettingModel * _Nonnull classic;)
+ (AIBudsEQSettingModel * _Nonnull)classic SWIFT_WARN_UNUSED_RESULT;
/// The country equalizer setting.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsEQSettingModel * _Nonnull country;)
+ (AIBudsEQSettingModel * _Nonnull)country SWIFT_WARN_UNUSED_RESULT;
/// The type of the preset equalizer.
@property (nonatomic, readonly) NSInteger mode;
/// An array of gain values for each frequency band, in dB.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull gains;
/// The name of the preset equalizer.
@property (nonatomic, copy) NSString * _Nullable name;
/// The Chinese name of the preset equalizer.
@property (nonatomic, copy) NSString * _Nullable chineseName;
/// Whether the equalizer is a preset equalizer.
@property (nonatomic, readonly) BOOL isPreset;
/// Whether the equalizer is a custom equalizer.
@property (nonatomic, readonly) BOOL isCustom;
/// The index of the custom equalizer mode.
@property (nonatomic, readonly, strong) NSNumber * _Nullable customIndex;
/// Initializes an <code>EQSettingModel</code> with the specified mode and gains.
/// \param mode The type of the preset equalizer.
///
/// \param gains An array of gain values for each frequency band, in dB.
///
- (nonnull instancetype)initWithMode:(NSInteger)mode gains:(NSArray<NSNumber *> * _Nonnull)gains OBJC_DESIGNATED_INITIALIZER;
/// Initializes an <code>EQSettingModel</code> with the specified mode, gains, name, and Chinese name.
/// \param mode The type of the preset equalizer.
///
/// \param gains An array of gain values for each frequency band, in dB.
///
/// \param name The name of the preset equalizer.
///
/// \param chineseName The Chinese name of the preset equalizer.
///
- (nonnull instancetype)initWithMode:(NSInteger)mode gains:(NSArray<NSNumber *> * _Nonnull)gains name:(NSString * _Nullable)name chineseName:(NSString * _Nullable)chineseName OBJC_DESIGNATED_INITIALIZER;
/// A string representation of <code>EQSettingModel</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsEQSettingModel (SWIFT_EXTENSION(AIBudsFoundation))
/// Hashes the essential components of this value by feeding them into the given hasher.
@property (nonatomic, readonly) NSUInteger hash;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsEarbudSide, "EarbudSide", open) {
/// Unknown
  AIBudsEarbudSideUnknown = -1,
/// Left
  AIBudsEarbudSideLeft = 0,
/// Right
  AIBudsEarbudSideRight = 1,
};

/// Endpoint information
SWIFT_CLASS_NAMED("EndPointInfoModel")
@interface AIBudsEndPointInfoModel : NSObject
/// Endpoint MAC address
@property (nonatomic, readonly, copy) NSString * _Nonnull macAddress;
/// Endpoint Bluetooth name
@property (nonatomic, readonly, copy) NSString * _Nonnull bluetoothName;
/// Whether the endpoint is connected
@property (nonatomic, readonly) BOOL isConnected;
/// Initialize endpoint information
/// \param macAddress Endpoint MAC address
///
/// \param bluetoothName Endpoint Bluetooth name
///
/// \param isConnected Whether the endpoint is connected
///
- (nonnull instancetype)initWithMacAddress:(NSString * _Nonnull)macAddress bluetoothName:(NSString * _Nonnull)bluetoothName isConnected:(BOOL)isConnected OBJC_DESIGNATED_INITIALIZER;
/// A string representation of <code>EndPointInfoModel</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// File deletion progress event enumeration
/// Used to describe different states during the file deletion process
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsFileDeletingProgressEvent, "FileDeletingProgressEvent", open) {
/// Unknown file deleting event
  AIBudsFileDeletingProgressEventUnknown = -1,
/// The deletion process exited unexpectedly, possibly due to a corrupted SD card
  AIBudsFileDeletingProgressEventUnexpectedExit = 0x00,
/// Deletion completed successfully
  AIBudsFileDeletingProgressEventCompleted = 0x01,
};

@class NSData;
/// A model that represents the firmware version of the device.
SWIFT_CLASS_NAMED("FirmwareVersionModel")
@interface AIBudsFirmwareVersionModel : NSObject
/// The raw value of the firmware version.
@property (nonatomic, readonly, copy) NSData * _Nonnull raw;
/// The integer representation of the firmware version derived from the least significant byte.
///
/// returns:
/// An integer value representing the firmware version.
@property (nonatomic, readonly, strong) NSNumber * _Nullable shortVersion;
/// Full firmware version of the device in format X.X.X.X
///
/// returns:
///
/// Full firmware version string, e.g. “0.0.0.108”
@property (nonatomic, readonly, copy) NSString * _Nullable formatedFullVersion;
/// Short firmware version of the device in format X.XX
///
/// returns:
///
/// Short firmware version string, e.g. “1.08”
@property (nonatomic, readonly, copy) NSString * _Nullable formatedShortVersion;
/// Initialize the firmware version model with the raw value.
/// \param raw The raw value of the firmware version.
///
- (nonnull instancetype)initWithRaw:(NSData * _Nonnull)raw OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Hotspot config field definition
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsHotspotConfigField, "HotspotConfigField", open) {
/// mode
  AIBudsHotspotConfigFieldMode = 0x01,
/// SSID
  AIBudsHotspotConfigFieldSsid = 0x02,
/// password
  AIBudsHotspotConfigFieldPassword = 0x03,
/// channel
  AIBudsHotspotConfigFieldChannel = 0x04,
};

/// Hotspot mode definition
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsHotspotMode, "HotspotMode", open) {
/// Station mode: connect to an existing Wi-Fi network (temporarily unsupported)
  AIBudsHotspotModeStation = 0,
/// AP mode: the device creates a hotspot for phone connection
  AIBudsHotspotModeAp = 1,
/// Wi-Fi Direct mode
  AIBudsHotspotModeWifiDirect = 2,
};

/// Hotspot state definition
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsHotspotState, "HotspotState", open) {
/// Unknown
  AIBudsHotspotStateUnknown = -1,
/// Hotspot closed
  AIBudsHotspotStateHotspotClose = 0,
/// Hotspot opened
  AIBudsHotspotStateHotspotOpen = 1,
/// Wi-Fi opened
  AIBudsHotspotStateWifiDirectOpen = 2,
/// Wi-Fi connected
  AIBudsHotspotStateWifiDirectConnected = 3,
/// Wi-Fi connection failed
  AIBudsHotspotStateWifiDirectFailed = 4,
/// Wi-Fi connection timeout
  AIBudsHotspotStateWifiDirectTimeout = 5,
};

/// Manufacturer flag
typedef SWIFT_ENUM_NAMED(NSUInteger, AIBudsManufacturerID, "ManufacturerID", open) {
/// 未知设备
  AIBudsManufacturerIDUnknown = 0,
/// 瑞昱 8773&8763
  AIBudsManufacturerIDRyTB = 0x5442,
/// 恒玄 2700
  AIBudsManufacturerIDHxTD = 0x5444,
/// 中科 895x/568x/569x
  AIBudsManufacturerIDZkTZ = 0x545A,
/// 瑞昱 8762D
  AIBudsManufacturerIDRyHT = 0x4854,
/// 瑞昱 8762c
  AIBudsManufacturerIDRyXQ = 0x5851,
/// 中科戒指
  AIBudsManufacturerIDZkZR = 0x5A52,
/// 中科眼镜
  AIBudsManufacturerIDZkZG = 0x5A47,
/// 文档未描述设备
  AIBudsManufacturerIDHx0600 = 0x0600,
/// 中科/瑞昱 5452 文档未描述设备
  AIBudsManufacturerIDZkryTR = 0x5452,
/// 绅聚 c001
  AIBudsManufacturerIDSjC001 = 0xC001,
/// 蓝讯耳机仓
  AIBudsManufacturerIDZkZC = 0x5A43,
/// 蓝讯耳机
  AIBudsManufacturerIDZk4206 = 0x4206,
/// 中科音频眼镜
  AIBudsManufacturerIDZkZM = 0x5a4d,
};

/// A model that represents the count of different media types.
SWIFT_CLASS_NAMED("MediaCountInfoModel")
@interface AIBudsMediaCountInfoModel : NSObject
/// The number of photos.
@property (nonatomic, readonly, strong) NSNumber * _Nonnull photoCount;
/// The number of videos.
@property (nonatomic, readonly, strong) NSNumber * _Nonnull videoCount;
/// The number of audio files.
@property (nonatomic, readonly, strong) NSNumber * _Nonnull audioCount;
/// Initializes a new <code>MediaCountInfoModel</code> with the specified counts.
/// \param photoCount The number of photos.
///
/// \param videoCount The number of videos.
///
/// \param audioCount The number of audio files.
///
- (nonnull instancetype)initWithPhotoCount:(NSNumber * _Nonnull)photoCount videoCount:(NSNumber * _Nonnull)videoCount audioCount:(NSNumber * _Nonnull)audioCount OBJC_DESIGNATED_INITIALIZER;
/// Returns a string describing the current media count information.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Returns a string describing the current media count information.
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsMediaFileType)
/// Media file info model
SWIFT_CLASS_NAMED("MediaFileInfoModel")
@interface AIBudsMediaFileInfoModel : NSObject <AIBudsCustomDebugJsonStringConvertible>
/// Media file type
@property (nonatomic, readonly) enum AIBudsMediaFileType fileType;
/// Media file name
@property (nonatomic, readonly, copy) NSString * _Nonnull fileName;
/// Media file base URL
@property (nonatomic, readonly, copy) NSString * _Nonnull baseUrl;
/// Whether the media file contains six-axis debounce information
@property (nonatomic, readonly) BOOL containsSixAxisDebounceInfo;
/// Media file full URL
@property (nonatomic, readonly, copy) NSString * _Nonnull fileUrl;
/// Initialize media file info
/// <ul>
///   <li>
///     Parameters fileType: Media file type
///   </li>
///   <li>
///     fileName: Media file name
///   </li>
///   <li>
///     baseUrl: Media file base URL
///   </li>
///   <li>
///     containsSixAxisDebounceInfo: Whether the media file contains six-axis debounce information
///   </li>
/// </ul>
///
/// returns:
/// Media file info model
- (nonnull instancetype)initWithFileType:(enum AIBudsMediaFileType)fileType fileName:(NSString * _Nonnull)fileName baseUrl:(NSString * _Nonnull)baseUrl containsSixAxisDebounceInfo:(BOOL)containsSixAxisDebounceInfo OBJC_DESIGNATED_INITIALIZER;
/// Description of media file info model
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Debug JSON string of media file info model
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMediaFileType, "MediaFileType", open) {
/// Unknown file type
  AIBudsMediaFileTypeUnknown = -1,
/// Image file type
  AIBudsMediaFileTypeImage = 1,
/// Audio file type
  AIBudsMediaFileTypeAudio = 2,
/// Video file type
  AIBudsMediaFileTypeVideo = 3,
};

/// Parameters required to authenticate a device with the MltCloud AI
SWIFT_CLASS_NAMED("MltCloudAIAuthParams")
@interface AIBudsMltCloudAIAuthParams : NSObject <NSSecureCoding>
/// The channel ID used for MltCloud AI authentication.
/// This value is required when connecting devices that support MltCloud AI features.
@property (nonatomic, copy) NSString * _Nullable channelId;
/// Initializes a new instance of the <code>MltCloudAIAuthParams</code> class.
/// This initializer creates a new instance of the <code>MltCloudAIAuthParams</code> class with default values for all properties.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Description of the authentication parameters.
/// This property provides a string description of the authentication parameters,
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// Music play source
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsMusicPlaySource, "MusicPlaySource", open) {
/// Unknown
  AIBudsMusicPlaySourceUnknown = -1,
/// BT music
  AIBudsMusicPlaySourceBt = 0,
/// Local playback
  AIBudsMusicPlaySourceLocalPlayback = 1,
};

/// Navigation alert
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsNavigationAlert, "NavigationAlert", open) {
/// Clear, parameter: alert type id
  AIBudsNavigationAlertClear = 0x00,
/// Speed limit, parameter: speed limit value, unit changes with user configuration
  AIBudsNavigationAlertSpeedLimit = 0x01,
/// Violation camera
  AIBudsNavigationAlertViolationCamera = 0x02,
/// Road construction
  AIBudsNavigationAlertRoadConstruction = 0x03,
/// Average speed zone, parameter: average speed zone value, unit changes with user configuration
  AIBudsNavigationAlertAverageSpeedZone = 0x04,
/// Accident prone area
  AIBudsNavigationAlertAccidentProneArea = 0x05,
/// Rear vehicle warning, parameter: rear vehicle merge direction, @see RearVehicleMergeDirection
  AIBudsNavigationAlertRearVehicleWarning = 0x06,
/// Weak GPS signal
  AIBudsNavigationAlertWeakGPSSignal = 0x07,
/// Icy road
  AIBudsNavigationAlertIcyRoad = 0x08,
/// Road closed or restricted
  AIBudsNavigationAlertRoadClosedOrRestricted = 0x09,
/// Rerouting
  AIBudsNavigationAlertRerouting = 0x0A,
/// Keep left lane
  AIBudsNavigationAlertKeepLeftLane = 0x0B,
/// Keep right lane
  AIBudsNavigationAlertKeepRightLane = 0x0C,
/// Traffic light countdown, parameter: traffic light countdown value in seconds; device will only show 99 if value > 99
  AIBudsNavigationAlertTrafficLightCountdown = 0x0D,
/// Keep left N lanes, parameter: N lanes to keep left, starting from 1 to indicate keeping to the leftmost lane
  AIBudsNavigationAlertKeepLeftNLanes = 0x0E,
/// Keep right N lanes, parameter: N lanes to keep right, starting from 1 to indicate keeping to the rightmost lane
  AIBudsNavigationAlertKeepRightNLanes = 0x0F,
};

/// Navigation alert info
SWIFT_CLASS_NAMED("NavigationAlertInfoModel")
@interface AIBudsNavigationAlertInfoModel : NSObject <AIBudsCustomDebugJsonStringConvertible>
/// Alert type, defines in <code>NavigationAlert</code>
@property (nonatomic, readonly, strong) NSNumber * _Nonnull alertType;
/// Params value, depends on alert type, @see <code>NavigationAlert</code> for details
@property (nonatomic, strong) NSNumber * _Nullable paramsValue;
/// Init with alert type and params value
/// \param alertType Alert type, defines in <code>NavigationAlert</code>
///
/// \param paramsValue Params value, depends on alert type, @see <code>NavigationAlert</code> for details
///
/// \param Returns Navigation alert info
///
- (nonnull instancetype)initWithAlertType:(NSNumber * _Nonnull)alertType paramsValue:(NSNumber * _Nullable)paramsValue OBJC_DESIGNATED_INITIALIZER;
/// Description of navigation alert info model
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Debug JSON string of navigation alert info model
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Navigation info
SWIFT_CLASS_NAMED("NavigationInfoModel")
@interface AIBudsNavigationInfoModel : NSObject <AIBudsCustomDebugJsonStringConvertible>
/// Next step distance text, e.g. 300m, 1.5km, 400yd, 2mi
@property (nonatomic, copy) NSString * _Nullable nextStepDistanceText;
/// Maneuver, defines in <code>NavigationManeuver</code>
@property (nonatomic, strong) NSNumber * _Nullable maneuver;
/// Instruction text, max length is 128 bytes, e.g. go straight, turn left, turn right
@property (nonatomic, copy) NSString * _Nullable instruction;
/// Road name text, max length is 128 bytes, e.g. 厚载门街开源大道口北
@property (nonatomic, copy) NSString * _Nullable roadName;
/// Alert info model, defines in <code>NavigationAlertInfoModel</code> for details
@property (nonatomic, strong) AIBudsNavigationAlertInfoModel * _Nullable alertInfo;
/// Map provider, defines in <code>NavigationMapProvider</code>
@property (nonatomic, strong) NSNumber * _Nullable mapProvider;
/// Transport mode, defines in <code>NavigationTransportMode</code>
@property (nonatomic, strong) NSNumber * _Nullable transportMode;
/// Remaining time, in seconds
@property (nonatomic, strong) NSNumber * _Nullable remainingTime;
/// Remaining distance, in meters
@property (nonatomic, strong) NSNumber * _Nullable remainingDistance;
/// Description of navigation info model
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Debug JSON string of navigation info model
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Navigation maneuver
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsNavigationManeuver, "NavigationManeuver", open) {
/// None
  AIBudsNavigationManeuverNone = 0x00,
/// Start
  AIBudsNavigationManeuverStart = 0x01,
/// Straight
  AIBudsNavigationManeuverStraight = 0x02,
/// Slight Right
  AIBudsNavigationManeuverSlightRight = 0x03,
/// Right
  AIBudsNavigationManeuverRight = 0x04,
/// Sharp Right
  AIBudsNavigationManeuverSharpRight = 0x05,
/// Slight Left
  AIBudsNavigationManeuverSlightLeft = 0x06,
/// Left
  AIBudsNavigationManeuverLeft = 0x07,
/// Sharp Left
  AIBudsNavigationManeuverSharpLeft = 0x08,
/// U-Turn Left
  AIBudsNavigationManeuverUTurnLeft = 0x09,
/// U-Turn Right
  AIBudsNavigationManeuverUTurnRight = 0x0A,
/// Arrive
  AIBudsNavigationManeuverArrive = 0x0B,
/// Stairs or Overpass
  AIBudsNavigationManeuverStairsOrOverpass = 0x0C,
/// Station or Platform
  AIBudsNavigationManeuverStationPlatform = 0x0D,
/// Merge Left
  AIBudsNavigationManeuverMergeLeft = 0x0E,
/// Merge Right
  AIBudsNavigationManeuverMergeRight = 0x0F,
/// Roundabout Enter Right
  AIBudsNavigationManeuverRoundaboutEnterRight = 0x10,
/// Roundabout Enter Left
  AIBudsNavigationManeuverRoundaboutEnterLeft = 0x11,
/// Roundabout Pass Left
  AIBudsNavigationManeuverRoundaboutPassLeft = 0x12,
/// Roundabout Pass Right
  AIBudsNavigationManeuverRoundaboutPassRight = 0x13,
/// Roundabout Exit Right
  AIBudsNavigationManeuverRoundaboutExitRight = 0x14,
/// Roundabout Exit Left
  AIBudsNavigationManeuverRoundaboutExitLeft = 0x15,
/// Highway Enter
  AIBudsNavigationManeuverHighwayEnter = 0x16,
/// Highway Exit Next Right
  AIBudsNavigationManeuverHighwayExitNextRight = 0x17,
/// Highway Exit Next Left
  AIBudsNavigationManeuverHighwayExitNextLeft = 0x18,
/// Highway Exit Exit Right
  AIBudsNavigationManeuverHighwayExitRight = 0x19,
/// Highway Exit Left
  AIBudsNavigationManeuverHighwayExitLeft = 0x1A,
/// Tunnel Enter
  AIBudsNavigationManeuverTunnelEnter = 0x1B,
/// Tunnel Exit
  AIBudsNavigationManeuverTunnelExit = 0x1C,
/// Ferry
  AIBudsNavigationManeuverFerry = 0x1D,
/// Stop Wait
  AIBudsNavigationManeuverStopWait = 0x1F,
};

/// Navigation map provider
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsNavigationMapProvider, "NavigationMapProvider", open) {
/// Unspecified
  AIBudsNavigationMapProviderUnspecified = 0x00,
/// Baidu
  AIBudsNavigationMapProviderBaidu = 0x01,
/// Amap
  AIBudsNavigationMapProviderAmap = 0x02,
/// HERE
  AIBudsNavigationMapProviderHere = 0x03,
/// TomTom
  AIBudsNavigationMapProviderTomtom = 0x04,
};

/// Navigation transport mode
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsNavigationTransportMode, "NavigationTransportMode", open) {
/// Unspecified
  AIBudsNavigationTransportModeUnspecified = 0x00,
/// Bicycle
  AIBudsNavigationTransportModeBicycle = 0x01,
/// Ebike
  AIBudsNavigationTransportModeEbike = 0x02,
/// Walk
  AIBudsNavigationTransportModeWalk = 0x03,
/// Drive
  AIBudsNavigationTransportModeDrive = 0x04,
};

/// On-device voice assistant capability
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsOnDeviceVoiceAssistantCapability, "OnDeviceVoiceAssistantCapability", open) {
/// No voice command capability
  AIBudsOnDeviceVoiceAssistantCapabilityNone = 0,
/// Keyword wakeup only (e.g., “Hi Buds”)
  AIBudsOnDeviceVoiceAssistantCapabilityKeywordWakeup = 1,
/// Common commands supported (play/pause, skip track, volume control, etc.)
  AIBudsOnDeviceVoiceAssistantCapabilityCommon = 2,
};

/// On-device voice assistant mode
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsOnDeviceVoiceAssistantMode, "OnDeviceVoiceAssistantMode", open) {
/// Unknown
  AIBudsOnDeviceVoiceAssistantModeUnknown = -1,
/// Disable on-device voice assistant
  AIBudsOnDeviceVoiceAssistantModeDisabled = 0,
/// Wake-up + basic voice commands
  AIBudsOnDeviceVoiceAssistantModeBasic = 1,
/// Includes call-state voice control
  AIBudsOnDeviceVoiceAssistantModeAdvanced = 2,
};

/// The purpose for opus audio data
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsOpusAudioDataPurpose, "OpusAudioDataPurpose", open) {
/// Unknown
  AIBudsOpusAudioDataPurposeUnknown = -1,
/// AI audio record
  AIBudsOpusAudioDataPurposeAiAudioRecord = 0,
/// AI chat
  AIBudsOpusAudioDataPurposeAiChat = 1,
};

/// The ota ble protocol capability of the device.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsOtaProtocolCapability, "OtaProtocolCapability", open) {
/// None
  AIBudsOtaProtocolCapabilityNone = -1,
/// ABMate
  AIBudsOtaProtocolCapabilityAbmate = 0,
/// FitCloud Pro
  AIBudsOtaProtocolCapabilityFitcloudPro = 1,
/// Both
  AIBudsOtaProtocolCapabilityBoth = 2,
};

/// The ota ble protocol kind of the device.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsOtaProtocolKind, "OtaProtocolKind", open) {
/// ABMate
  AIBudsOtaProtocolKindAbmate = 0,
/// FitCloud Pro
  AIBudsOtaProtocolKindFitcloudPro = 1,
};

/// Rear vehicle merge direction
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsRearVehicleMergeDirection, "RearVehicleMergeDirection", open) {
/// Unknown
  AIBudsRearVehicleMergeDirectionUnknown = 0,
/// From right
  AIBudsRearVehicleMergeDirectionFromRight = 1,
/// From left
  AIBudsRearVehicleMergeDirectionFromLeft = 2,
};

/// Audio recording scene
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsRecordingScene, "RecordingScene", open) {
/// On-site recording (ambient/field capture)
  AIBudsRecordingSceneOnSite = 0,
/// Call recording (during phone call)
  AIBudsRecordingSceneCall = 1,
};

/// Remote shutter event
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsRemoteShutterEvent, "RemoteShutterEvent", open) {
/// Unknown
  AIBudsRemoteShutterEventUnknown = -1,
/// Exit camera
  AIBudsRemoteShutterEventExit = 0,
/// Enter camera
  AIBudsRemoteShutterEventEnter = 1,
/// Capture photo
  AIBudsRemoteShutterEventCapture = 2,
};

/// The state of the remote shutter.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsRemoteShutterState, "RemoteShutterState", open) {
/// Exited photo mode or unable to enter
  AIBudsRemoteShutterStateExitedOrUnableToEnter = 0,
/// Successfully entered photo mode
  AIBudsRemoteShutterStateEnteredPhotoMode = 1,
/// Photo taken successfully
  AIBudsRemoteShutterStatePhotoSuccess = 2,
/// Photo failed (no permission or storage full)
  AIBudsRemoteShutterStatePhotoFailed = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsServiceAuthType, "ServiceAuthType", open) {
/// StarBurst AI
  AIBudsServiceAuthTypeStarBurst = 1,
/// On-device voice assistant
  AIBudsServiceAuthTypeOnDeviceVoiceAssistant = 2,
};

/// Spatial audio mode
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsSpatialAudioMode, "SpatialAudioMode", open) {
/// Unknown
  AIBudsSpatialAudioModeUnknown = -1,
/// Off
  AIBudsSpatialAudioModeOff = 0,
/// Fixed
  AIBudsSpatialAudioModeFixed = 1,
/// Head tracking
  AIBudsSpatialAudioModeHeadTracking = 2,
};

/// Parameters required to authenticate a device with the StarBurst AI
SWIFT_CLASS_NAMED("StarBurstAIAuthParams")
@interface AIBudsStarBurstAIAuthParams : NSObject <NSSecureCoding>
/// The SDK type used for StarBurst AI authentication.
/// This value specifies the type of SDK to be used for authentication with StarBurst AI features.
/// It determines the authentication flow and requirements for connecting devices.
/// The value is of type <code>StarBurstAuthSdk</code> enum. Default: <code>.glassesBle</code>
@property (nonatomic, strong) NSNumber * _Nullable authSdk;
/// The product identifier used for StarBurst AI authentication.
/// <blockquote>
/// Important: This value is required when connecting devices that support StarBurst AI features.
///
/// </blockquote>
@property (nonatomic, copy) NSString * _Nullable productId;
/// The PPE environment identifier for StarBurst AI authentication.
/// This value specifies the PPE environment when connecting devices that support StarBurst AI features.
/// Example value: <code>"ppe_tis_translate_mode"</code>
@property (nonatomic, copy) NSString * _Nullable ppeEnv;
/// Initializes a new instance of the <code>StarBurstAIAuthParams</code> class.
/// This initializer creates a new instance of the <code>StarBurstAIAuthParams</code> class with default values for all properties.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Description of the authentication parameters.
/// This property provides a string description of the authentication parameters,
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// Defines the auth types of StarBurst SDK.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsStarBurstAuthSdk, "StarBurstAuthSdk", open) {
/// Device authentication + device audio pickup (dialog SDK internally encapsulates earphone recording via BLE transmission)
  AIBudsStarBurstAuthSdkBle = 1,
/// Account authentication + phone audio pickup (dialog SDK internally encapsulates phone recording)
  AIBudsStarBurstAuthSdkPhone = 2,
/// Device authentication + phone audio pickup (dialog SDK internally encapsulates phone recording)
  AIBudsStarBurstAuthSdkMix = 3,
/// Glasses board + device authentication (dialog requires external audio stream feeding)
  AIBudsStarBurstAuthSdkGlassesBle = 4,
/// Glasses board + account authentication (dialog requires external audio stream feeding)
  AIBudsStarBurstAuthSdkGlassesAccount = 5,
};

/// Storage information model that describes the device’s storage usage.
SWIFT_CLASS_NAMED("StorageInfoModel")
@interface AIBudsStorageInfoModel : NSObject
/// Used storage space in megabytes (MB).
@property (nonatomic, readonly, strong) NSNumber * _Nonnull usedSpaceInMB;
/// Remaining available storage space in megabytes (MB).
@property (nonatomic, readonly, strong) NSNumber * _Nonnull freeSpaceInMB;
/// Initialize a storage information model instance.
/// \param usedSpaceInMB Used storage space (MB).
///
/// \param freeSpaceInMB Remaining available storage space (MB).
///
- (nonnull instancetype)initWithUsedSpaceInMB:(NSNumber * _Nonnull)usedSpaceInMB freeSpaceInMB:(NSNumber * _Nonnull)freeSpaceInMB OBJC_DESIGNATED_INITIALIZER;
/// Returns a string describing the current storage information, formatted as “usedSpaceInMB=xxx, freeSpaceInMB=xxx”.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Returns a string describing the current storage information, formatted as “usedSpaceInMB=xxx, freeSpaceInMB=xxx”.
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Time format
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsTimeFormat, "TimeFormat", open) {
/// 24-hour format
  AIBudsTimeFormatFormat24Hour = 0,
/// 12-hour format
  AIBudsTimeFormatFormat12Hour = 1,
};

/// Video record direction
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsVideoRecordDirection, "VideoRecordDirection", open) {
/// Landscape direction
  AIBudsVideoRecordDirectionLandscape = 0,
/// Portrait direction
  AIBudsVideoRecordDirectionPortrait = 1,
};

/// Video record direction info model
SWIFT_CLASS_NAMED("VideoRecordDirectionInfoModel")
@interface AIBudsVideoRecordDirectionInfoModel : NSObject
/// Whether video recording direction switching is supported
@property (nonatomic, readonly) BOOL isDirectionSwitchSupported;
/// Current video record direction
@property (nonatomic, readonly) enum AIBudsVideoRecordDirection currentDirection;
- (nonnull instancetype)initWithDirectionSwitchSupported:(BOOL)isDirectionSwitchSupported currentDirection:(enum AIBudsVideoRecordDirection)currentDirection OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Device volume change reason
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsVolumeChangedReason, "VolumeChangedReason", open) {
/// 0 - Adjusted by device (physical buttons on the device or the phone)
  AIBudsVolumeChangedReasonDevice = 0,
/// 1 - Adjusted via Bluetooth command
  AIBudsVolumeChangedReasonBluetoothCommand = 1,
};

/// Enum for volume-setting capability
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsVolumeSetCapability, "VolumeSetCapability", open) {
/// Not supported
  AIBudsVolumeSetCapabilityNone = 0,
/// Supports setting system, media, and call volumes separately
  AIBudsVolumeSetCapabilityCommon = 1,
/// Supports setting system, media, call, and local playback volumes separately
  AIBudsVolumeSetCapabilityAdvanced = 2,
};

/// A model that encapsulates volume information for various audio streams.
/// Use <code>VolumesInfoModel</code> to retrieve or update the current volume levels
/// for system, media, call, and local-playback audio streams.
SWIFT_CLASS_NAMED("VolumesInfoModel")
@interface AIBudsVolumesInfoModel : NSObject
/// The current system prompt volume, if available. （0~100）
@property (nonatomic, readonly, strong) NSNumber * _Nullable systemPromptVolume;
/// The current media-playback volume, if available. （0~100）
@property (nonatomic, readonly, strong) NSNumber * _Nullable mediaVolume;
/// The current in-call volume, if available. （0~100）
@property (nonatomic, readonly, strong) NSNumber * _Nullable callVolume;
/// The current local-playback volume, if available. （0~100）
@property (nonatomic, readonly, strong) NSNumber * _Nullable localPlaybackVolume;
/// Creates a new volume-info model with the specified levels.
/// \param systemPromptVolume The system-level volume. （0~100）
///
/// \param mediaVolume The media-playback volume. （0~100）
///
/// \param callVolume The in-call volume. （0~100）
///
/// \param localPlaybackVolume The local-playback volume. （0~100）
///
- (nonnull instancetype)initWithSystemPromptVolume:(NSNumber * _Nullable)systemPromptVolume mediaVolume:(NSNumber * _Nullable)mediaVolume callVolume:(NSNumber * _Nullable)callVolume localPlaybackVolume:(NSNumber * _Nullable)localPlaybackVolume OBJC_DESIGNATED_INITIALIZER;
/// 返回描述当前音量信息的字符串
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsWearDetectionCapability, "WearDetectionCapability", open) {
/// Not supported
  AIBudsWearDetectionCapabilityNone = 0,
/// Supported but not configurable
  AIBudsWearDetectionCapabilitySupportedNotConfigurable = 1,
/// Supported and configurable
  AIBudsWearDetectionCapabilitySupportedAndConfigurable = 2,
};

/// Wear status.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsWearStatus, "WearStatus", open) {
/// Unknown
  AIBudsWearStatusUnknown = -1,
/// Not wearing
  AIBudsWearStatusNotWearing = 0,
/// Only left ear wearing
  AIBudsWearStatusLeftWearing = 1,
/// Only right ear wearing
  AIBudsWearStatusRightWearing = 2,
/// Both ears wearing
  AIBudsWearStatusBothWearing = 3,
};

/// work mode definition
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsWorkMode, "WorkMode", open) {
/// unknown mode
  AIBudsWorkModeUnknown = -1,
/// normal mode
  AIBudsWorkModeNormal = 0,
/// game mode
  AIBudsWorkModeGame = 1,
};

/// Device work state
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsWorkState, "WorkState", open) {
/// Unknown
  AIBudsWorkStateUnknown = -1,
/// Reserved
  AIBudsWorkStateReserved = 0,
/// Initializing
  AIBudsWorkStateInitializing = 1,
/// BT/BLE disconnected, waiting for connection
  AIBudsWorkStateBtOrBleWaitingForConnection = 2,
/// BT/BLE connected, idle
  AIBudsWorkStateBtOrBleConnectedIdle = 3,
/// BT/BLE disconnected, idle
  AIBudsWorkStateBtOrBleDisconnectedIdle = 4,
/// In call
  AIBudsWorkStateCalling = 5,
/// Playing local music
  AIBudsWorkStatePlayingLocalMusic = 6,
/// AI conversing
  AIBudsWorkStateAiConversing = 7,
/// Restoring factory settings
  AIBudsWorkStateRestoringFactorySettings = 8,
/// Taking photo
  AIBudsWorkStateTakingPhoto = 9,
/// AI taking photo
  AIBudsWorkStateAiTakingPhoto = 10,
/// Recording video
  AIBudsWorkStateRecordingVideo = 11,
/// Recording audio
  AIBudsWorkStateRecordingAudio = 12,
/// File transferring
  AIBudsWorkStateFileTransferring = 13,
/// Streaming
  AIBudsWorkStateStreaming = 14,
/// OTA upgrading
  AIBudsWorkStateOta = 15,
/// Shutting down
  AIBudsWorkStateShuttingDown = 16,
/// Factory testing
  AIBudsWorkStateFactoryTesting = 17,
/// LED testing
  AIBudsWorkStateLedTesting = 18,
/// Button testing
  AIBudsWorkStateButtonTesting = 19,
/// Echo testing
  AIBudsWorkStateEchoTesting = 20,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
