#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef AIBUDSSTARBURST_SWIFT_H
#define AIBUDSSTARBURST_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AIBuds;
@import AIBudsAI;
@import AIBudsAIFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsStarBurst",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// The error codes used for AIBudsStarBurstSDK errors
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsStarBurstSdkErrorCode, "SdkErrorCode", open) {
/// Unknown error
  AIBudsStarBurstSdkErrorCodeUnknown = -1,
/// Authentication failed
  AIBudsStarBurstSdkErrorCodeAuthenticationFailed = 1001,
/// Insufficient quota
  AIBudsStarBurstSdkErrorCodeInsufficientQuota = 1002,
/// Service failed due to the sdk is not authenticated
  AIBudsStarBurstSdkErrorCodeServiceFailedDueToSdkNotAuthenticated = 1003,
/// Busy, please wait for the previous request to complete
  AIBudsStarBurstSdkErrorCodeBusy = 1004,
/// Microphone usage description not configured in the Info.plist
  AIBudsStarBurstSdkErrorCodeMicrophoneUsageDescriptionNotConfigured = 1005,
/// Microphone permission denied by the user
  AIBudsStarBurstSdkErrorCodeMicrophonePermissionDenied = 1006,
/// Generate summary failed
  AIBudsStarBurstSdkErrorCodeGenerateSummaryFailed = 3001,
/// Translate failed due to the target language is empty
  AIBudsStarBurstSdkErrorCodeTranslateFailedDueToTargetLanguageEmpty = 4001,
/// Translate failed
  AIBudsStarBurstSdkErrorCodeTranslateFailed = 4002,
/// TTS failed
  AIBudsStarBurstSdkErrorCodeTtsFailed = 4003,
/// Start simultaneous interpretation failed due to the target language is empty
  AIBudsStarBurstSdkErrorCodeStartSimultaneousInterpretationFailedDueToTargetLanguageEmpty = 5001,
/// Start simultaneous interpretation failed due to the source language is same as target language
  AIBudsStarBurstSdkErrorCodeStartSimultaneousInterpretationFailedDueToSourceLanguageSameAsTargetLanguage = 5002,
/// Start simultaneous interpretation failed due to the record error
  AIBudsStarBurstSdkErrorCodeStartSimultaneousInterpretationFailedDueToRecordError = 5003,
/// Simultaneous interpretation stopped unexpectedly
  AIBudsStarBurstSdkErrorCodeSimultaneousInterpretationStoppedUnexpectedly = 5004,
/// BLE disconnected during simultaneous interpretation
  AIBudsStarBurstSdkErrorCodeBleDisconnectedDuringSimultaneousInterpretation = 5005,
/// WebSocket disconnected during simultaneous interpretation
  AIBudsStarBurstSdkErrorCodeWebsocketDisconnectedDuringSimultaneousInterpretation = 5006,
/// WebSocket ping timeout during simultaneous interpretation
  AIBudsStarBurstSdkErrorCodeWebsocketPingTimeoutDuringSimultaneousInterpretation = 5007,
/// Network error during simultaneous interpretation
  AIBudsStarBurstSdkErrorCodeNetworkErrorDuringSimultaneousInterpretation = 5008,
/// Start AI-Chat failed due to unable to start the SCO audio capturer
  AIBudsStarBurstSdkErrorCodeStartAIChatFailedDueToUnableToStartSCOAudioCapturer = 6001,
/// BLE disconnected during AI-Chat session
  AIBudsStarBurstSdkErrorCodeBleDisconnectedDuringAIChatSession = 6002,
/// WebSocket disconnected during AI-Chat session
  AIBudsStarBurstSdkErrorCodeWebsocketDisconnectedDuringAIChatSession = 6003,
/// WebSocket ping timeout during AI-Chat session
  AIBudsStarBurstSdkErrorCodeWebsocketPingTimeoutDuringAIChatSession = 6004,
/// Network error during AI-Chat session
  AIBudsStarBurstSdkErrorCodeNetworkErrorDuringAIChatSession = 6005,
/// ASR error with single word unrecognized during AI-Chat session
  AIBudsStarBurstSdkErrorCodeAsrErrorWithSingleWordUnrecognizedDuringAIChatSession = 6006,
/// Unknown server error during AI-Chat session
  AIBudsStarBurstSdkErrorCodeUnknownServerErrorDuringAIChatSession = 6007,
/// Start AI audio recording failed due to the language for speech input is empty
  AIBudsStarBurstSdkErrorCodeStartAIAudioRecordingFailedDueToLanguageForSpeechInputEmpty = 7001,
/// BLE disconnected during AI audio recording
  AIBudsStarBurstSdkErrorCodeBleDisconnectedDuringAIAudioRecording = 7002,
/// WebSocket disconnected during AI audio recording
  AIBudsStarBurstSdkErrorCodeWebsocketDisconnectedDuringAIAudioRecording = 7003,
/// WebSocket ping timeout during AI audio recording
  AIBudsStarBurstSdkErrorCodeWebsocketPingTimeoutDuringAIAudioRecording = 7004,
/// Network error during AI audio recording
  AIBudsStarBurstSdkErrorCodeNetworkErrorDuringAIAudioRecording = 7005,
/// Recognize voice data failed due to unable to resolve fed data
  AIBudsStarBurstSdkErrorCodeRecognizeVoiceDataFailedDueToUnableToResolveFedData = 8001,
/// Recognize voice data failed due to audio file not found
  AIBudsStarBurstSdkErrorCodeRecognizeVoiceDataFailedDueToAudioFileNotFound = 8002,
/// BLE disconnected during streaming ASR
  AIBudsStarBurstSdkErrorCodeBleDisconnectedDuringStreamingASR = 8003,
/// WebSocket disconnected during streaming ASR
  AIBudsStarBurstSdkErrorCodeWebsocketDisconnectedDuringStreamingASR = 8004,
/// WebSocket ping timeout during streaming ASR
  AIBudsStarBurstSdkErrorCodeWebsocketPingTimeoutDuringStreamingASR = 8005,
/// Network error during streaming ASR
  AIBudsStarBurstSdkErrorCodeNetworkErrorDuringStreamingASR = 8006,
/// The Internet connection appears to be offline.
  AIBudsStarBurstSdkErrorCodeInternetConnectionOffline = 9999,
};

@class AIBudsAIAudioRecordingSessionConfig;
@protocol AIBudsAIAudioRecordingSessionConvertible;
@class AIBudsStreamSpeechASRModel;
@class NSError;
@class AIBudsAIAudioRecordingReportModel;
/// A class that provides AI audio recording service.
SWIFT_CLASS_NAMED("StarBurstAIAudioRecordingService")
@interface AIBudsStarBurstAIAudioRecordingService : NSObject <AIBudsAIAudioRecordingServiceAPI>
/// The shared singleton instance of StarBurstAIAudioRecordingService
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstAIAudioRecordingService * _Nonnull shared;)
+ (AIBudsStarBurstAIAudioRecordingService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstAIAudioRecordingService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Whether to use SDK internal recording (YES means SDK records internally; NO means audio data is fed externally)
@property (nonatomic, readonly) BOOL isRecordingInternally;
/// Start the audio recording session.
/// \param config The configuration for the audio recording session.
///
/// \param onStartSuccess The callback when the audio recording session starts successfully.
///
/// \param onStartFailure The callback when the audio recording session starts with an error.
///
/// \param onTranscript The callback when the audio recording session transcribes a speech.
///
/// \param onError The callback when the audio recording session encounters an error.
///
/// \param onFinish The callback when the audio recording session finishes successfully.
///
- (void)startAIAudioRecordingWithConfig:(AIBudsAIAudioRecordingSessionConfig * _Nonnull)config onStartSuccess:(void (^ _Nullable)(id <AIBudsAIAudioRecordingSessionConvertible> _Nonnull))onStartSuccess onStartFailure:(void (^ _Nullable)(NSError * _Nonnull))onStartFailure onTranscript:(void (^ _Nullable)(AIBudsStreamSpeechASRModel * _Nonnull))onTranscript onError:(void (^ _Nullable)(NSError * _Nonnull))onError onFinish:(void (^ _Nullable)(AIBudsAIAudioRecordingReportModel * _Nonnull))onFinish;
/// Stops the current AI audio recording session.
- (void)stopAIAudioRecording;
@end

@class NSDate;
@class NSData;
@class AVAudioPCMBuffer;
/// A class that represents an AI audio recording session.
SWIFT_CLASS_NAMED("StarBurstAIAudioRecordingSession")
@interface AIBudsStarBurstAIAudioRecordingSession : NSObject <AIBudsAIAudioRecordingSessionConvertible>
/// AI service vendor
@property (nonatomic, readonly) enum AIBudsAIServiceVendor serviceVendor;
/// The configuration for AI audio recording (read-only).
@property (nonatomic, readonly, strong) AIBudsAIAudioRecordingSessionConfig * _Nonnull sessionCfg;
/// The time when the session started (read-only).
@property (nonatomic, readonly, copy) NSDate * _Nonnull sessionStartTime;
/// Session end time; <code>nil</code> if the session has not yet ended.
@property (nonatomic, copy) NSDate * _Nullable sessionEndTime;
/// Computes the current session duration in seconds.
/// Returns the interval between the end time and the start time if the session has ended;
/// otherwise returns the interval between the current time and the start time.
@property (nonatomic, readonly) NSTimeInterval sessionDuration;
/// Appends 16-bit linear PCM audio data to the session.
/// \param pcmData A <code>Data</code> object containing 16-bit linear PCM samples.
/// <ul>
///   <li>
///     Sample rate: 16 kHz
///   </li>
///   <li>
///     Bit depth: 16-bit
///   </li>
///   <li>
///     Channels: Mono
///   </li>
///   <li>
///     Interleaved: Yes
///   </li>
///   <li>
///     Endianness: Little-endian
///   </li>
///   <li>
///     Sample format: Signed-integer
///   </li>
/// </ul>
///
- (void)appendInt16PCM:(NSData * _Nonnull)pcmData;
/// Appends audio data from an <code>AVAudioPCMBuffer</code> to the session.
/// \param buffer An <code>AVAudioPCMBuffer</code> instance encapsulating PCM audio data.
///
- (void)appendAudioPCMBuffer:(AVAudioPCMBuffer * _Nonnull)buffer;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AIBudsAIChatSessionConfig;
@protocol AIBudsAIChatSessionConvertible;
@class AIBudsAIChatDataModel;
@class AIBudsAIChatIntentModel;
@class AIBudsAIChatVoiceDataModel;
@class AIBudsAIChatEventModel;
@class AIBudsAIChatSessionReportModel;
/// A class that provides ai-chat service.
SWIFT_CLASS_NAMED("StarBurstAIChatService")
@interface AIBudsStarBurstAIChatService : NSObject <AIBudsAIChatServiceAPI>
/// The shared singleton instance of StarBurstAIChatService
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstAIChatService * _Nonnull shared;)
+ (AIBudsStarBurstAIChatService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstAIChatService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Initiates a new AI chat session with the specified configuration and callbacks
/// note:
/// All callbacks are optional; implement only those relevant to your use case
/// \param config The configuration for the chat session. Defaults to <code>.default</code>
///
/// \param onStartSuccess Called when the session is successfully initiated, providing the active <code>AIChatSessionConvertible</code> object.
/// <ul>
///   <li>
///     session: The active <code>AIChatSessionConvertible</code> object representing the session.
///   </li>
/// </ul>
///
/// \param onStartFailure Called when session initiation fails, providing the associated error.
/// <ul>
///   <li>
///     error: The error that occurred, typically indicating a failure while setting up the session.
///   </li>
/// </ul>
///
/// \param onChatData Called whenever new chat data arrives during the session.
/// <ul>
///   <li>
///     chatData: The chat data model containing the received message.
///   </li>
/// </ul>
///
/// \param onIntent Called when an intent is detected from user input.
/// <ul>
///   <li>
///     intent: The intent model containing the detected intent.
///   </li>
/// </ul>
///
/// \param onVoiceData Called when voice data is received or needs to be processed.
/// <ul>
///   <li>
///     voiceData: The voice data model containing the received audio data.
///   </li>
/// </ul>
///
/// \param onEvent Called for any session-level events (e.g., user join/leave, mute changes)
/// <ul>
///   <li>
///     event: The event model containing the details of the event.
///   </li>
/// </ul>
///
/// \param onError Called when any runtime error occurs during the session.
/// <ul>
///   <li>
///     error: The error that occurred, typically indicating a failure while processing data returned by the model.
///   </li>
/// </ul>
///
/// \param onFinish Called when the session ends, providing a summary report of the session.
/// <ul>
///   <li>
///     report: The session report model containing the details of the session.
///   </li>
/// </ul>
///
- (void)startAIChatWithConfig:(AIBudsAIChatSessionConfig * _Nonnull)config onStartSuccess:(void (^ _Nullable)(id <AIBudsAIChatSessionConvertible> _Nonnull))onStartSuccess onStartFailure:(void (^ _Nullable)(NSError * _Nonnull))onStartFailure onChatData:(void (^ _Nullable)(AIBudsAIChatDataModel * _Nonnull))onChatData onIntent:(void (^ _Nullable)(AIBudsAIChatIntentModel * _Nonnull))onIntent onVoiceData:(void (^ _Nullable)(AIBudsAIChatVoiceDataModel * _Nonnull))onVoiceData onEvent:(void (^ _Nullable)(AIBudsAIChatEventModel * _Nonnull))onEvent onError:(void (^ _Nullable)(NSError * _Nonnull))onError onFinish:(void (^ _Nullable)(AIBudsAIChatSessionReportModel * _Nonnull))onFinish;
/// Terminates the currently active AI chat session, if one exists
/// note:
/// This method is safe to call even when no session is active
- (void)stopAIChat;
@end

@class UIImage;
@class NSString;
/// A class that represents an ai-chat session.
SWIFT_CLASS_NAMED("StarBurstAIChatSession")
@interface AIBudsStarBurstAIChatSession : NSObject <AIBudsAIChatSessionConvertible>
/// AI service vendor
@property (nonatomic, readonly) enum AIBudsAIServiceVendor serviceVendor;
/// Session configuration.
@property (nonatomic, readonly, strong) AIBudsAIChatSessionConfig * _Nonnull sessionCfg;
/// Session start time.
@property (nonatomic, readonly, copy) NSDate * _Nonnull sessionStartTime;
/// Session end time. <code>nil</code> if the session is still active.
@property (nonatomic, copy) NSDate * _Nullable sessionEndTime;
/// Computes the current session duration in seconds.
/// Returns the interval between the end time and the start time if the session has ended;
/// otherwise returns the interval between the current time and the start time.
@property (nonatomic, readonly) NSTimeInterval sessionDuration;
/// Appends 16-bit linear PCM audio data to the session.
/// \param pcmData A <code>Data</code> object containing 16-bit linear PCM samples.
/// <ul>
///   <li>
///     Sample rate: 16 kHz
///   </li>
///   <li>
///     Bit depth: 16-bit
///   </li>
///   <li>
///     Channels: Mono
///   </li>
///   <li>
///     Interleaved: Yes
///   </li>
///   <li>
///     Endianness: Little-endian
///   </li>
///   <li>
///     Sample format: Signed-integer
///   </li>
/// </ul>
///
- (void)appendInt16PCM:(NSData * _Nonnull)pcmData;
/// Appends audio data from an <code>AVAudioPCMBuffer</code> to the session.
/// \param buffer An <code>AVAudioPCMBuffer</code> instance encapsulating PCM audio data.
///
- (void)appendAudioPCMBuffer:(AVAudioPCMBuffer * _Nonnull)buffer;
/// Sends image for photo understanding to the session.
/// \param image A <code>UIImage</code> object.
///
- (void)sendImageForPhotoUnderstanding:(UIImage * _Nonnull)image;
/// Sends image to the session.
/// \param image A <code>UIImage</code> object.
///
- (void)sendImage:(UIImage * _Nonnull)image;
/// Sends text to the session.
/// \param text A string to be sent as text.
///
- (void)sendText:(NSString * _Nonnull)text;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AIBudsStarBurstAuthEnv;
@protocol AIBudsStarBurstDevice;
SWIFT_CLASS_NAMED("StarBurstAuthPlugin")
@interface AIBudsStarBurstAuthPlugin : NSObject <AIBudsStarBurstBridgePlugin>
/// The directory for log files. Default is “.aibuds/logs”.
/// Note: Only relative paths to NSDocumentDirectory are allowed; absolute paths are not permitted.
@property (nonatomic, copy) NSString * _Nonnull logsDirectory;
/// The shared singleton instance of StarBurstAuthPlugin
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstAuthPlugin * _Nonnull shared;)
+ (AIBudsStarBurstAuthPlugin * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstAuthPlugin
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Prepares the authentication environment for StarBurst AI.
/// \param authEnv The authentication environment to be prepared.
///
/// \param device The target device for which the environment is prepared.
///
- (void)prepareAuthEnvForStarBurst:(AIBudsStarBurstAuthEnv * _Nonnull)authEnv withDevice:(id <AIBudsStarBurstDevice> _Nonnull)device;
/// Called when bridge data is received from a device.
/// \param device The device that received the data.
///
/// \param data The received data.
///
- (void)didReceiveStarBurstAiBridgeDataFromDevice:(id <AIBudsStarBurstDevice> _Nonnull)device data:(NSData * _Nonnull)data;
/// Called when the device is connected.
/// \param device The device that is connected.
///
- (void)didStarBurstDeviceConnected:(id <AIBudsStarBurstDevice> _Nonnull)device;
/// Called when the device is disconnected.
/// \param device The device that is disconnected.
///
- (void)didStarBurstDeviceDisconnected:(id <AIBudsStarBurstDevice> _Nonnull)device;
@end

/// The main entry point for the StarBurstSDK.
/// Use this class to access SDK version information and other global SDK-level functionality.
SWIFT_CLASS_NAMED("StarBurstSDK")
@interface AIBudsStarBurstSDK : NSObject
/// The shared singleton instance of StarBurstSDK
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstSDK * _Nonnull shared;)
+ (AIBudsStarBurstSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstSDK
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsStarBurstSDK (SWIFT_EXTENSION(AIBudsStarBurst))
/// The error domain used for AIBudsStarBurstSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorDomain;)
+ (NSString * _Nonnull)ErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// The error key used for AIBudsStarBurstSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorKey;)
+ (NSString * _Nonnull)ErrorKey SWIFT_WARN_UNUSED_RESULT;
/// The error domain used for StarBurst SDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull StarBurstSdkErrorDomain;)
+ (NSString * _Nonnull)StarBurstSdkErrorDomain SWIFT_WARN_UNUSED_RESULT;
@end

@protocol AIBudsAIAuthenticationServiceAPI;
@protocol AIBudsAITextTranslationServiceAPI;
@protocol AIBudsSimultaneousInterpretationServiceAPI;
@protocol AIBudsAISummaryServiceAPI;
@protocol AIBudsStreamingASRServiceAPI;
@protocol AIBudsTTSServiceAPI;
@interface AIBudsStarBurstSDK (SWIFT_EXTENSION(AIBudsStarBurst)) <AIBudsAIConnectSDK>
/// The version number of the SDK
///
/// returns:
/// A string representing the current SDK version (e.g. “1.0.0-beta.1”)
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
/// The build number of the SDK
///
/// returns:
/// A string representing the SDK build number (e.g. “20250315001”)
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkBuild;
/// The release date of the SDK
///
/// returns:
/// A string representing the SDK release date in YYYY-MM-DD format
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkReleaseDate;
/// Returns a formatted string containing SDK version information
/// note:
/// The returned string includes an emoji prefix and is formatted for easy reading
///
/// returns:
/// A string containing the SDK name, version, build number and release date
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersionDescription;
/// The name of the SDK
///
/// returns:
/// A string representing the SDK name (e.g. “StarBurstSDK”)
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkName;
/// The name of the SDK vendor
///
/// returns:
/// A string representing the SDK provider name (e.g. “ByteDance”)
@property (nonatomic, readonly, copy) NSString * _Nonnull vendorName;
/// The SDK vendor
///
/// returns:
/// An AIServiceVendor value indicating the type of service provider (e.g. .byteDance)
@property (nonatomic, readonly) enum AIBudsAIServiceVendor vendor;
/// The authentication initiation mode for the ai service.
///
/// returns:
/// A AIAuthenticationMode value indicating the authentication initiation mode (e.g. .deviceInitiated)
@property (nonatomic, readonly) enum AIBudsAIAuthenticationMode authenticationMode;
/// Indicates whether the device is authenticated for the service provider
///
/// returns:
/// A boolean value indicating whether the device is authenticated
@property (nonatomic, readonly) BOOL isAuthenticated;
/// The authentication service interface for the service provider
///
/// returns:
/// An object conforming to AIAuthenticationServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAIAuthenticationServiceAPI> _Nullable aiAuthenticationService;
/// The chat service interface for the service provider
///
/// returns:
/// An object conforming to AIChatServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAIChatServiceAPI> _Nullable aiChatService;
/// The text translation service interface for the service provider
///
/// returns:
/// An object conforming to AITextTranslationAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAITextTranslationServiceAPI> _Nullable textTranslationService;
/// The simultaneous interpretation service interface for the service provider
///
/// returns:
/// An object conforming to SimultaneousInterpretationService if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsSimultaneousInterpretationServiceAPI> _Nullable simultaneousInterpretationService;
/// The summary service interface for the service provider
///
/// returns:
/// An object conforming to AISummaryAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAISummaryServiceAPI> _Nullable aiSummaryService;
/// The audio recording service interface for the service provider
///
/// returns:
/// An object conforming to AIAudioRecordingAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsAIAudioRecordingServiceAPI> _Nullable aiAudioRecordingService;
/// The streaming ASR service interface for the service provider
///
/// returns:
/// An object conforming to StreamingASRServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsStreamingASRServiceAPI> _Nullable streamingASRService;
/// The TTS service interface for the service provider
///
/// returns:
/// An object conforming to TTSServiceAPI if available, otherwise nil
@property (nonatomic, readonly, strong) id <AIBudsTTSServiceAPI> _Nullable ttsService;
@end

@class AIBudsSimultaneousInterpretationConfig;
@protocol AIBudsSimultaneousInterpretationSessionConvertible;
@class AIBudsSimultaneousInterpretationDataModel;
@class AIBudsSimultaneousInterpretationReportModel;
/// A class that provides simultaneous-interpretation service.
SWIFT_CLASS_NAMED("StarBurstSimultaneousInterpretationService")
@interface AIBudsStarBurstSimultaneousInterpretationService : NSObject <AIBudsSimultaneousInterpretationServiceAPI>
/// The shared singleton instance of StarBurstSimultaneousInterpretationService
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstSimultaneousInterpretationService * _Nonnull shared;)
+ (AIBudsStarBurstSimultaneousInterpretationService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstSimultaneousInterpretationService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Whether to use SDK internal recording (YES means SDK records internally; NO means audio data is fed externally)
@property (nonatomic, readonly) BOOL isRecordingInternally;
/// Starts a simultaneous interpretation session with the specified configuration.
/// \param config The configuration for the simultaneous interpretation session.
///
/// \param onStartSuccess A closure to be called when the session starts successfully.
/// <ul>
///   <li>
///     session: The started simultaneous interpretation session.
///   </li>
/// </ul>
///
/// \param onStartFailure A closure to be called when the session fails to start.
/// <ul>
///   <li>
///     error: The error that occurred.
///   </li>
/// </ul>
///
/// \param onStopByInterruption A closure to be called when the session is stopped by interruption.
/// <ul>
///   <li>
///     error: The error that occurred.
///   </li>
/// </ul>
///
/// \param onException A closure to be called when the session throws an exception. This usually does not mean the session will be stopped.
/// The app should decide whether to stop the session upon receiving the exception.
/// If the session needs to be stopped, the app should call the <code>stopSimultaneousInterpretation</code> method.
/// <ul>
///   <li>
///     error: The error that occurred.
///   </li>
/// </ul>
///
/// \param streamResultHandler A closure to handle the stream results.
/// <ul>
///   <li>
///     isFinal: Whether the result is the final one.
///   </li>
///   <li>
///     response: The simultaneous interpretation data model.
///   </li>
///   <li>
///     error: The error that occurred, typically indicating a failure while processing data returned by the model.
///   </li>
/// </ul>
///
/// \param onFinish A closure to be called when the session finishes, providing a summary report.
/// <ul>
///   <li>
///     report: The simultaneous interpretation report model.
///   </li>
/// </ul>
///
- (void)startSimultaneousInterpretationWithConfig:(AIBudsSimultaneousInterpretationConfig * _Nonnull)config onStartSuccess:(void (^ _Nullable)(id <AIBudsSimultaneousInterpretationSessionConvertible> _Nonnull))onStartSuccess onStartFailure:(void (^ _Nullable)(NSError * _Nonnull))onStartFailure onStopByInterruption:(void (^ _Nullable)(NSError * _Nullable))onStopByInterruption onException:(void (^ _Nullable)(NSError * _Nonnull))onException onStreamResultHandler:(void (^ _Nullable)(BOOL, AIBudsSimultaneousInterpretationDataModel * _Nullable, NSError * _Nullable))streamResultHandler onFinish:(void (^ _Nullable)(AIBudsSimultaneousInterpretationReportModel * _Nonnull))onFinish;
/// Stops the current simultaneous interpretation session.
- (void)stopSimultaneousInterpretation;
@end

/// A class that represents a simultaneous-interpretation session.
SWIFT_CLASS_NAMED("StarBurstSimultaneousInterpretationSession")
@interface AIBudsStarBurstSimultaneousInterpretationSession : NSObject <AIBudsSimultaneousInterpretationSessionConvertible>
/// AI service vendor
@property (nonatomic, readonly) enum AIBudsAIServiceVendor serviceVendor;
/// Whether to use SDK internal recording (YES means SDK records internally; NO means audio data is fed externally)
@property (nonatomic, readonly) BOOL isRecordingInternally;
/// The configuration for simultaneous interpretation (read-only).
@property (nonatomic, readonly, strong) AIBudsSimultaneousInterpretationConfig * _Nonnull sessionCfg;
/// The time when the session started (read-only).
@property (nonatomic, readonly, copy) NSDate * _Nonnull sessionStartTime;
/// Session end time; <code>nil</code> if the session has not yet ended.
@property (nonatomic, copy) NSDate * _Nullable sessionEndTime;
/// Computes the current session duration in seconds.
/// Returns the interval between the end time and the start time if the session has ended;
/// otherwise returns the interval between the current time and the start time.
@property (nonatomic, readonly) NSTimeInterval sessionDuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AIBudsStreamingASRConfig;
/// A class that provides AI audio recording service.
SWIFT_CLASS_NAMED("StarBurstStreamingASRService")
@interface AIBudsStarBurstStreamingASRService : NSObject <AIBudsStreamingASRServiceAPI>
/// The shared singleton instance of StarBurstStreamingASRService
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstStreamingASRService * _Nonnull shared;)
+ (AIBudsStarBurstStreamingASRService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstAIAudioRecordingService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Recognizes the voice data.
/// \param data The voice data.
///
/// \param config The configuration for the recognition.
///
/// \param onTranscript The callback for the transcript data.
/// <ul>
///   <li>
///     transcriptData: The transcript data.
///   </li>
/// </ul>
///
/// \param onFailed The callback for the failed.
/// <ul>
///   <li>
///     error: The error.
///   </li>
/// </ul>
///
/// \param onFinish The callback for the finish.
///
///
/// returns:
/// The task object.
- (void)recognizeVoiceData:(NSData * _Nonnull)data withConfig:(AIBudsStreamingASRConfig * _Nonnull)config onTranscript:(void (^ _Nullable)(AIBudsStreamSpeechASRModel * _Nonnull))onTranscript onFailed:(void (^ _Nullable)(NSError * _Nonnull))onFailed onFinish:(void (^ _Nullable)(void))onFinish;
/// Recognizes the voice file.
/// \param filePath The file path of the voice file.
///
/// \param config The configuration for the recognition.
///
/// \param onTranscript The callback for the transcript data.
/// <ul>
///   <li>
///     transcriptData: The transcript data.
///   </li>
/// </ul>
///
/// \param onFailed The callback for the failed.
/// <ul>
///   <li>
///     error: The error.
///   </li>
/// </ul>
///
/// \param onFinish The callback for the finish.
///
///
/// returns:
/// The task object.
- (void)recognizeVoiceFile:(NSString * _Nonnull)filePath withConfig:(AIBudsStreamingASRConfig * _Nonnull)config onTranscript:(void (^ _Nullable)(AIBudsStreamSpeechASRModel * _Nonnull))onTranscript onFailed:(void (^ _Nullable)(NSError * _Nonnull))onFailed onFinish:(void (^ _Nullable)(void))onFinish;
@end

/// A service class for generating concise summaries of text.
SWIFT_CLASS_NAMED("StarBurstSummaryService")
@interface AIBudsStarBurstSummaryService : NSObject <AIBudsAISummaryServiceAPI>
/// The shared singleton instance of StarBurstSummaryService
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstSummaryService * _Nonnull shared;)
+ (AIBudsStarBurstSummaryService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstSummaryService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Generates a concise summary for the provided text.
/// \param text The text to summarize.
///
/// \param streamResultHandler The callback that delivers summary results.
/// <ul>
///   <li>
///     isFinal: <code>true</code> when the summary is complete; <code>false</code> for partial results.
///   </li>
///   <li>
///     transcript: The current summary text.
///     This text will be returned multiple times. For example, the complete answer <code>"Swift is a fast, safe, and modern programming language developed by Apple."</code> will be returned incrementally:
///     \code
///     "Swift"
///     "Swift is a fast"
///     "Swift is a fast, safe"
///     "Swift is a fast, safe, and modern"
///     "Swift is a fast, safe, and modern programming language"
///     "Swift is a fast, safe, and modern programming language developed by Apple."
///
///     \endcode</li>
///   <li>
///     error: An error object if the operation fails; otherwise <code>nil</code>.
///   </li>
/// </ul>
///
- (void)summaryWithText:(NSString * _Nonnull)text streamResultHandler:(void (^ _Nullable)(BOOL, NSString * _Nullable, NSError * _Nullable))streamResultHandler;
/// Cancels the current summary operation.
/// Call this method to stop the summary process before it completes.
- (void)cancelSummary;
@end

@class AIBudsTTSConfig;
@class AIBudsTTSResultModel;
/// A service class for text-to-speech synthesis.
SWIFT_CLASS_NAMED("StarBurstTTSService")
@interface AIBudsStarBurstTTSService : NSObject <AIBudsTTSServiceAPI>
/// The shared singleton instance of StarBurstTTSService
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstTTSService * _Nonnull shared;)
+ (AIBudsStarBurstTTSService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstTTSService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Synthesizes text into speech
/// note:
/// This method initiates a text-to-speech synthesis request.
/// important:
/// This method must be called from a background thread to avoid blocking the main thread.
/// Calling this method from the main thread may cause UI unresponsiveness.
/// \param text The text to be synthesized into speech
///
/// \param config The configuration for the synthesis request
///
/// \param completion A closure called when synthesis completes, providing:
/// <ul>
///   <li>
///     taskId: A unique identifier for this synthesis request
///   </li>
///   <li>
///     success: Whether the synthesis was successful
///   </li>
///   <li>
///     response: The text-to-speech response model
///     error: Any error that occurred during synthesis
///   </li>
/// </ul>
///
- (void)synthesizeText:(NSString * _Nonnull)text config:(AIBudsTTSConfig * _Nonnull)config completion:(void (^ _Nullable)(NSString * _Nullable, BOOL, AIBudsTTSResultModel * _Nullable, NSError * _Nullable))completion;
@end

SWIFT_CLASS_NAMED("StarBurstTextTranslationService")
@interface AIBudsStarBurstTextTranslationService : NSObject <AIBudsAITextTranslationServiceAPI>
/// The shared singleton instance of StarBurstTextTranslationService
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStarBurstTextTranslationService * _Nonnull shared;)
+ (AIBudsStarBurstTextTranslationService * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of StarBurstTextTranslationService
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Translates the given text from the source language to the target language.
/// \param text The text to be translated.
///
/// \param sourceLanguage The language code of the source language. Empty string means auto-detect.
/// <blockquote>
/// Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>zh-CN</code>
///
/// </blockquote>
/// <ul>
///   <li>
///     Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “zh” for Chinese)
///   </li>
///   <li>
///     Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “CN” for China)
///   </li>
/// </ul>
///
/// \param targetLanguage The language code of the target language.
/// <blockquote>
/// Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>en-US</code>
///
/// </blockquote>
/// <ul>
///   <li>
///     Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “en” for English)
///   </li>
///   <li>
///     Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “US” for United States)
///   </li>
/// </ul>
///
/// \param streamResultHandler A closure that is called multiple times with the translation results.
/// <ul>
///   <li>
///     isFinal: A boolean value indicating whether the translation is complete.
///   </li>
///   <li>
///     transcript: The translated text.
///     This text will be returned multiple times. For example, the complete answer <code>"Swift is a fast, safe, and modern programming language developed by Apple."</code> will be returned incrementally:
///     \code
///     "Swift"
///     "Swift is a fast"
///     "Swift is a fast, safe"
///     "Swift is a fast, safe, and modern"
///     "Swift is a fast, safe, and modern programming language"
///     "Swift is a fast, safe, and modern programming language developed by Apple."
///
///     \endcode</li>
///   <li>
///     error: An error object if the translation fails, or nil if the translation is successful.
///   </li>
/// </ul>
///
- (void)translateText:(NSString * _Nonnull)text from:(NSString * _Nonnull)sourceLanguage to:(NSString * _Nonnull)targetLanguage streamResultHandler:(void (^ _Nullable)(BOOL, NSString * _Nullable, NSError * _Nullable))streamResultHandler;
/// Cancels the current text translation operation.
/// Call this method to stop the text translation process before it completes.
- (void)cancelTextTranslation;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
