#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.1 effective-5.10 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)
#ifndef AIBUDSAIFOUNDATION_SWIFT_H
#define AIBUDSAIFOUNDATION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsAIFoundation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AIBudsFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsAIFoundation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Audio format
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsAIAudioFormat, "AIAudioFormat", open) {
/// Unknown audio format
  AIBudsAIAudioFormatUnknown = -1,
/// No audio format
  AIBudsAIAudioFormatNone = 0,
/// PCM audio format
  AIBudsAIAudioFormatPcm = 1,
/// OPUS audio format
  AIBudsAIAudioFormatOpus = 2,
/// MP3 audio format
  AIBudsAIAudioFormatMp3 = 3,
/// WAV audio format
  AIBudsAIAudioFormatWav = 4,
};

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsRecordingScene)
@class NSString;
/// Configuration for an AI audio recording session.
SWIFT_CLASS_NAMED("AIAudioRecordingSessionConfig")
@interface AIBudsAIAudioRecordingSessionConfig : NSObject <AIBudsCustomDebugJsonStringConvertible>
/// The default configuration shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsAIAudioRecordingSessionConfig * _Nonnull defaultConfig;)
+ (AIBudsAIAudioRecordingSessionConfig * _Nonnull)defaultConfig SWIFT_WARN_UNUSED_RESULT;
/// The recording scene.
@property (nonatomic) enum AIBudsRecordingScene recordingScene;
/// The language setting for speech input
/// A string representing the language identifier, if not provided, the system will use the current app’s localization language (iOS allows setting a specific language per app).
/// <blockquote>
/// Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>zh-CN</code>
///
/// </blockquote>
/// <ul>
///   <li>
///     Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “zh” for Chinese)
///   </li>
///   <li>
///     Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “CN” for China)
///   </li>
/// </ul>
@property (nonatomic, copy) NSString * _Nullable languageForSpeechInput;
/// Whether to allow starting the recording session when the internet is offline. Default value is <code>false</code>.
/// <blockquote>
/// Important: If set to false, the recording session will not start if the internet is not available.
///
/// </blockquote>
@property (nonatomic) BOOL allowRecordingWhileOffline;
/// Initializes a new configuration with the specified recording scene.
/// \param recordingScene The recording scene.
///
/// \param allowRecordingWhileOffline Whether to allow starting the recording session when the internet is offline. Default value is <code>false</code>.
/// <blockquote>
/// Important: If set to false, the recording session will not start if the internet is not available.
///
/// </blockquote>
///
/// \param languageForSpeechInput The language setting for speech input, if not provided, the system will use the current app’s localization language (iOS allows setting a specific language per app).
/// <blockquote>
/// Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>zh-CN</code>
///
/// </blockquote>
/// <ul>
///   <li>
///     Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “zh” for Chinese)
///   </li>
///   <li>
///     Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “CN” for China)
///   </li>
/// </ul>
///
///
/// returns:
/// A new configuration instance of AIAudioRecordingSessionConfig.
- (nonnull instancetype)initWithRecordingScene:(enum AIBudsRecordingScene)recordingScene allowRecordingWhileOffline:(BOOL)allowRecordingWhileOffline languageForSpeechInput:(NSString * _Nullable)languageForSpeechInput OBJC_DESIGNATED_INITIALIZER;
/// Description
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Debug JSON string
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsAIAudioRecordingSessionConfig (SWIFT_EXTENSION(AIBudsAIFoundation)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Defines the authentication initiation mode for the ai service.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsAIAuthenticationMode, "AIAuthenticationMode", open) {
/// Unknown authentication mode.
  AIBudsAIAuthenticationModeUnknown = -1,
/// No authentication mode.
  AIBudsAIAuthenticationModeNone = 0,
/// After the connection is established, the device automatically initiates authentication.
  AIBudsAIAuthenticationModeDeviceInitiated = 1,
/// After the connection is established, the app actively initiates authentication.
  AIBudsAIAuthenticationModeAppInitiated = 2,
};

@class NSDate;
@class NSData;
@class AVAudioPCMBuffer;
/// AI-Chat audio chunk
SWIFT_CLASS_NAMED("AIChatAudioChunk")
@interface AIBudsAIChatAudioChunk : NSObject
/// Sequence number of the audio chunk
@property (nonatomic, readonly) NSInteger sequence;
/// Timestamp when the audio chunk was generated (either from recording buffer creation or original timestamp of the external stream)
@property (nonatomic, readonly, copy) NSDate * _Nonnull generatedAt;
/// Raw audio data in 16-bit linear PCM format
/// <ul>
///   <li>
///     Sample rate: 16 kHz
///   </li>
///   <li>
///     Bit depth: 16-bit
///   </li>
///   <li>
///     Channels: Mono
///   </li>
///   <li>
///     Interleaved: Yes
///   </li>
///   <li>
///     Byte order: Little-endian
///   </li>
///   <li>
///     Sample format: Signed integer
///   </li>
/// </ul>
@property (nonatomic, readonly, copy) NSData * _Nullable rawAudioData;
/// Raw audio buffer in PCM format
@property (nonatomic, readonly, strong) AVAudioPCMBuffer * _Nullable rawAudioBuffer;
/// Length of the raw audio data in bytes
/// note:
/// This property is computed from the raw audio data or buffer.
@property (nonatomic, readonly) NSInteger rawAudioLength;
/// Description of the raw audio data or buffer
@property (nonatomic, readonly, copy) NSString * _Nonnull rawAudioDescription;
/// Resolved audio buffer in 32-bit linear PCM format
/// <ul>
///   <li>
///     Sample rate: 16 kHz
///   </li>
///   <li>
///     Bit depth: 32-bit
///   </li>
///   <li>
///     Channels: Mono
///   </li>
///   <li>
///     Interleaved: Yes
///   </li>
///   <li>
///     Byte order: Little-endian
///   </li>
///   <li>
///     Sample format: Float32
///   </li>
/// </ul>
@property (nonatomic, strong) AVAudioPCMBuffer * _Nullable resolvedAudioBuffer;
/// Float32 format sample array, lazy loaded, range [-1.0, 1.0]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable float32Samples;
/// Int16 format sample array, lazy loaded
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable int16Samples;
/// Int16 format PCM data, lazy loaded
@property (nonatomic, copy) NSData * _Nullable int16PCMData;
/// Timestamp when the audio chunk was processed by VAD
@property (nonatomic, copy) NSDate * _Nullable vadProcessAt;
/// Timestamp when the audio chunk was sent to AI-Chat service vendor SDK
@property (nonatomic, copy) NSDate * _Nullable sentAt;
/// Initializes with audio data
/// \param sequence Sequence number of the audio chunk
///
/// \param rawAudioData Raw audio data in 16-bit linear PCM format
///
/// \param generatedAt Timestamp when the audio chunk was generated (either from recording buffer creation or original timestamp of the external stream)
///
///
/// returns:
/// An initialized instance of AIChatAudioChunk
- (nonnull instancetype)initWithSequence:(NSInteger)sequence rawAudioData:(NSData * _Nonnull)rawAudioData generatedAt:(NSDate * _Nonnull)generatedAt OBJC_DESIGNATED_INITIALIZER;
/// Initializes with audio buffer
/// \param sequence Sequence number of the audio chunk
///
/// \param rawAudioBuffer Raw audio buffer in PCM format
///
/// \param generatedAt Timestamp when the audio chunk was generated (either from recording buffer creation or original timestamp of the external stream)
///
///
/// returns:
/// An initialized instance of AIChatAudioChunk
- (nonnull instancetype)initWithSequence:(NSInteger)sequence rawAudioBuffer:(AVAudioPCMBuffer * _Nonnull)rawAudioBuffer generatedAt:(NSDate * _Nonnull)generatedAt OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A model representing a single chat response in the AIBudsAI system.
/// This class encapsulates both the user’s question and the AI’s answer,
/// along with flags indicating whether each piece of content is considered definite.
SWIFT_CLASS_NAMED("AIChatDataModel")
@interface AIBudsAIChatDataModel : NSObject <AIBudsCustomDebugJsonStringConvertible>
/// Sequence number for the model response.
@property (nonatomic, readonly) NSInteger sequence;
/// Request ID.
@property (nonatomic, readonly, copy) NSString * _Nullable requestId;
/// The unique identifier for the question.
@property (nonatomic, readonly, copy) NSString * _Nonnull questionId;
/// The text of the question asked by the user.
/// This text will be returned multiple times. For example, the complete question <code>"What is Swift?"</code> will be returned incrementally:
/// \code
/// "What"
/// "What is"
/// "What is Swift"
/// "What is Swift?"
///
/// \endcode
@property (nonatomic, readonly, copy) NSString * _Nonnull question;
/// A Boolean value indicating whether the question is considered definite.
/// When <code>true</code>, the question is finalized and should not be modified.
@property (nonatomic, readonly) BOOL isQuestionDefinite;
/// The text of the answer provided by the AI.
/// This text will be returned multiple times. For example, the complete answer <code>"Swift is a fast, safe, and modern programming language developed by Apple."</code> will be returned incrementally:
/// \code
/// "Swift"
/// "Swift is a fast"
/// "Swift is a fast, safe"
/// "Swift is a fast, safe, and modern"
/// "Swift is a fast, safe, and modern programming language"
/// "Swift is a fast, safe, and modern programming language developed by Apple."
///
/// \endcode
@property (nonatomic, readonly, copy) NSString * _Nonnull answer;
/// A Boolean value indicating whether the answer is considered definite.
/// When <code>true</code>, the answer is finalized and should not be modified.
@property (nonatomic, readonly) BOOL isAnswerDefinite;
/// Initializes a new chat response model.
/// \param sequence The sequence number for the model response.
///
/// \param requestId The request ID associated with the response.
///
/// \param questionId The unique identifier for the question.
///
/// \param question The text of the question. Defaults to an empty string.
///
/// \param answer The text of the answer. Defaults to an empty string.
///
/// \param isQuestionDefinite Indicates if the question is definite. Defaults to <code>false</code>.
///
/// \param isAnswerDefinite Indicates if the answer is definite. Defaults to <code>false</code>.
///
- (nonnull instancetype)initWithSequence:(NSInteger)sequence requestId:(NSString * _Nullable)requestId questionId:(NSString * _Nonnull)questionId question:(NSString * _Nonnull)question answer:(NSString * _Nonnull)answer isQuestionDefinite:(BOOL)isQuestionDefinite isAnswerDefinite:(BOOL)isAnswerDefinite OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Events that occur during an AI chat session.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsAIChatEventType, "AIChatEventType", open) {
/// Session started event.
  AIBudsAIChatEventTypeSessionStarted = 1,
/// Session start failed event.
  AIBudsAIChatEventTypeSessionStartFailed = 2,
/// AI service successfully connected.
  AIBudsAIChatEventTypeAiServiceConnected = 3,
/// SCO recording link successfully established.
  AIBudsAIChatEventTypeScoRecordingLinkEstablished = 4,
/// SCO recording start failed
  AIBudsAIChatEventTypeScoRecordingStartFailed = 5,
/// VAD detected the start of user speech.
  AIBudsAIChatEventTypeVadStartSpeaking = 6,
/// Triggered when a new question is asked.
  AIBudsAIChatEventTypeTriggerNewQuestion = 7,
/// VAD detected the end of user speech.
  AIBudsAIChatEventTypeVadEndSpeaking = 8,
/// Triggered when the current question ends.
  AIBudsAIChatEventTypeTriggerEndQuestion = 9,
/// Auto end session triggered event.
  AIBudsAIChatEventTypeAutoEndSessionTriggered = 10,
/// Session ended event.
  AIBudsAIChatEventTypeSessionEnded = 11,
/// AI service authentication failed.
  AIBudsAIChatEventTypeAiServiceUnauthorized = 12,
/// AI service disconnected.
  AIBudsAIChatEventTypeAiServiceDisconnected = 13,
/// AI service encountered a network error.
  AIBudsAIChatEventTypeAiServiceNetworkError = 14,
/// AI service started recording.
  AIBudsAIChatEventTypeAiServiceStartRecording = 15,
/// AI service stopped recording.
  AIBudsAIChatEventTypeAiServiceEndRecording = 16,
/// AI service recording error occurred.
  AIBudsAIChatEventTypeAiServiceRecordingError = 17,
/// AI service response error occurred.
  AIBudsAIChatEventTypeAiServiceResponseError = 18,
/// AI intent received.
  AIBudsAIChatEventTypeAiIntentReceived = 19,
/// AI respond voice playback did start.
  AIBudsAIChatEventTypeAiRespondVoicePlaybackDidStart = 20,
/// AI respond voice playback did stop.
  AIBudsAIChatEventTypeAiRespondVoicePlaybackDidStop = 21,
/// BLE disconnected.
  AIBudsAIChatEventTypeBleDisconnected = 22,
};

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsAIIntentType)
/// A model representing the intent of a chat question in AIBudsAI.
/// Use this model to encapsulate the user’s question and its associated intent,
/// including optional extracted value and intent identifier.
SWIFT_CLASS_NAMED("AIChatIntentModel")
@interface AIBudsAIChatIntentModel : NSObject <AIBudsCustomDebugJsonStringConvertible>
/// Sequence number for the model response.
@property (nonatomic, readonly) NSInteger sequence;
/// Request ID.
@property (nonatomic, readonly, copy) NSString * _Nullable requestId;
/// The unique identifier of the question.
@property (nonatomic, readonly, copy) NSString * _Nonnull questionId;
/// The user’s input query string.
@property (nonatomic, readonly, copy) NSString * _Nonnull query;
/// The classified intent type of the query.
@property (nonatomic, readonly) enum AIBudsAIIntentType intent;
/// The optional extracted value from the query, if any.
@property (nonatomic, readonly, copy) NSString * _Nullable value;
/// The optional unique identifier for the intent itself.
@property (nonatomic, readonly, copy) NSString * _Nullable intentId;
/// The optional extracted value from the query, if any, as a dictionary.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable valueDictionary;
/// Creates a new chat intent model.
/// \param sequence The sequence number for the model response.
///
/// \param questionId The unique identifier of the question.
///
/// \param query The user’s input query string.
///
/// \param intent The classified intent type of the query.
///
/// \param value The optional extracted value from the query, if any.
///
/// \param intentId The optional unique identifier for the intent itself.
///
/// \param requestId The request ID associated with the intent.
///
- (nonnull instancetype)initWithSequence:(NSInteger)sequence questionId:(NSString * _Nonnull)questionId query:(NSString * _Nonnull)query intent:(enum AIBudsAIIntentType)intent value:(NSString * _Nullable)value intentId:(NSString * _Nullable)intentId requestId:(NSString * _Nullable)requestId OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsAIChatAudioChannel)
/// Configuration for an AI chat session.
SWIFT_CLASS_NAMED("AIChatSessionConfig")
@interface AIBudsAIChatSessionConfig : NSObject
/// The default configuration shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsAIChatSessionConfig * _Nonnull defaultConfig;)
+ (AIBudsAIChatSessionConfig * _Nonnull)defaultConfig SWIFT_WARN_UNUSED_RESULT;
/// The language setting for speech input
/// A string representing the language identifier, if not provided, the system will use the current app’s localization language (iOS allows setting a specific language per app).
/// > Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>zh-CN</code>
/// - Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “zh” for Chinese)
/// - Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “CN” for China)
@property (nonatomic, copy) NSString * _Nullable languageForSpeechInput;
/// The audio channel to use for the chat session.
/// Defaults to <code>.opusInA2dpOut</code>.
@property (nonatomic) enum AIBudsAIChatAudioChannel audioChannel;
/// Indicates whether allow the user to interrupt the AI response, typically the voice playback.
@property (nonatomic) BOOL allowUserToInterruptAIResponse;
/// Permitted maximum pause duration (in seconds) before the AI responds.
@property (nonatomic) NSTimeInterval maxPauseDurationBeforeAIResponds;
/// The duration (in seconds) after which the session will be automatically ended if no new input is received.
/// Defaults to <code>15.0</code> seconds.
@property (nonatomic) NSTimeInterval autoEndSessionAfterNoInputDuration;
/// Indicates whether voice playback is enabled, default is <code>true</code>.
@property (nonatomic) BOOL enableVoicePlayback;
/// Indicates whether to save input voice data for debugging and troubleshooting, defaults to <code>false</code>.
@property (nonatomic) BOOL shouldSaveInputVoiceForDebugging;
/// Indicates whether to automatically select an agent by AIBudsSDK when no specific agent is explicitly specified.
/// Defaults to <code>true</code>.
/// <blockquote>
/// Important: Usually, you need to specify a specific agent through additionalOptions
///
/// </blockquote>
@property (nonatomic) BOOL autoSelectAgentIfNotSpecified;
/// Additional configuration options. Defaults to <code>[:]</code>.
/// Known supported configuration options:
/// <ul>
///   <li>
///     <code>starburst.agent_id</code>: The agent ID for StarBurst AI. for example, <code>"ZNT002"</code>.
///   </li>
///   <li>
///     <code>starburst.speaker_id</code>: The speaker ID for StarBurst AI. for example, <code>"zh_female_tianmeitaozi_mars_bigtts"</code>.
///   </li>
///   <li>
///     <code>starburst.init_prompt</code>: The initial prompt for StarBurst AI. for example, <code>"1.User's location is Beijing.\n2.User's age is 25 years old.\n3.User's name is John Doe."</code>
///     <blockquote>
///     Important: If you set this option, the initial prompt will be used to start the conversation.
///
///     </blockquote>
///   </li>
///   <li>
///     <code>starburst.usage_plan</code>: The usage plan to use. Defaults to <code>"pro"</code>. Supported plans:
///     <ul>
///       <li>
///         <code>"lite"</code>: Lite plan, with limited features. Available features include: Normal voice conversation.
///       </li>
///       <li>
///         <code>"pro"</code>: Pro plan, with access to all features. Available features include: Normal voice conversation, AI image recognition, and so on.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>mltcloud.agent_id</code>: The agent ID for MltCloud AI.
///     <ul>
///       <li>
///         <code>0</code>: glass
///       </li>
///       <li>
///         <code>1</code>: toy
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>mltcloud.speaker_id</code>: The speaker ID for MltCloud AI. for example, <code>"siyue"</code>.
///   </li>
///   <li>
///     <code>mltcloud.intent_confg_code</code>: The intent config code for MLTCloud AI. for example, <code>"basic_intent_config"</code>.
///   </li>
/// </ul>
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull additionalOptions;
/// The key for the StarBurst agent ID in the additional options dictionary.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AdditionalOptionKeyStarburstAgentId;)
+ (NSString * _Nonnull)AdditionalOptionKeyStarburstAgentId SWIFT_WARN_UNUSED_RESULT;
/// The key for the StarBurst speaker ID in the additional options dictionary.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AdditionalOptionKeyStarburstSpeakerId;)
+ (NSString * _Nonnull)AdditionalOptionKeyStarburstSpeakerId SWIFT_WARN_UNUSED_RESULT;
/// The key for the StarBurst initial prompt in the additional options dictionary.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AdditionalOptionKeyStarburstInitPrompt;)
+ (NSString * _Nonnull)AdditionalOptionKeyStarburstInitPrompt SWIFT_WARN_UNUSED_RESULT;
/// The key for the StarBurst usage plan in the additional options dictionary.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AdditionalOptionKeyStarburstUsagePlan;)
+ (NSString * _Nonnull)AdditionalOptionKeyStarburstUsagePlan SWIFT_WARN_UNUSED_RESULT;
/// The key for the MltCloud agent ID in the additional options dictionary.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AdditionalOptionKeyMltCloudAgentId;)
+ (NSString * _Nonnull)AdditionalOptionKeyMltCloudAgentId SWIFT_WARN_UNUSED_RESULT;
/// The key for the MltCloud speaker ID in the additional options dictionary.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AdditionalOptionKeyMltCloudSpeakerId;)
+ (NSString * _Nonnull)AdditionalOptionKeyMltCloudSpeakerId SWIFT_WARN_UNUSED_RESULT;
/// The key for the MltCloud intent config code in the additional options dictionary.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AdditionalOptionKeyMltCloudIntentConfigCode;)
+ (NSString * _Nonnull)AdditionalOptionKeyMltCloudIntentConfigCode SWIFT_WARN_UNUSED_RESULT;
/// Creates a new chat session configuration.
/// \param languageForSpeechInput The language setting for speech input. Defaults to <code>nil</code>.
/// A string representing the language identifier, if not provided, the system will use the current app’s localization language (iOS allows setting a specific language per app).
/// <blockquote>
/// Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>zh-CN</code>
///
/// </blockquote>
/// <ul>
///   <li>
///     Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “zh” for Chinese)
///   </li>
///   <li>
///     Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “CN” for China)
///   </li>
/// </ul>
///
/// \param audioChannel The audio channel to use for the chat session. Defaults to <code>.opusInA2dpOut</code>.
///
/// \param allowUserToInterruptAIResponse Whether allow the user to interrupt the AI response. Defaults to <code>true</code>.
///
/// \param maxPauseDurationBeforeAIResponds The maximum pause duration required before AI responds. Defaults to <code>0.8</code> seconds.
///
/// \param autoEndSessionAfterNoInputDuration The duration (in seconds) after which the session will be automatically ended if no new input is received. Defaults to <code>15.0</code> seconds.
///
/// \param enableVoicePlayback Whether voice playback is enabled. Defaults to <code>true</code>.
///
/// \param shouldSaveInputVoiceForDebugging Whether to save input voice data for debugging and troubleshooting. Defaults to <code>false</code>.
///
/// \param additionalOptions Additional configuration options. Defaults to <code>[:]</code>.
/// Known supported configuration options:
/// <ul>
///   <li>
///     <code>starburst.role_id</code>: The role ID for StarBurst AI. for example, <code>"ZNT002"</code>.
///   </li>
///   <li>
///     <code>starburst.speaker_id</code>: The speaker ID for StarBurst AI. for example, <code>"zh_female_tianmeitaozi_mars_bigtts"</code>.
///   </li>
///   <li>
///     <code>starburst.usage_plan</code>: The usage plan to use. Defaults to <code>"pro"</code>. Supported plans:
///     <ul>
///       <li>
///         <code>"lite"</code>: Lite plan, with limited features. Available features include: Normal voice conversation.
///       </li>
///       <li>
///         <code>"pro"</code>: Pro plan, with access to all features. Available features include: Normal voice conversation, AI image recognition, and so on.
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>mltcloud.agent_id</code>: The agent ID for MltCloud AI.
///     <ul>
///       <li>
///         <code>0</code>: glass
///       </li>
///       <li>
///         <code>1</code>: toy
///       </li>
///     </ul>
///   </li>
///   <li>
///     <code>mltcloud.speaker_id</code>: The speaker ID for MltCloud AI. for example, <code>"siyue"</code>.
///   </li>
///   <li>
///     <code>mltcloud.intent_confg_code</code>: The intent config code for MLTCloud AI. for example, <code>"basic_intent_config"</code>.
///   </li>
/// </ul>
///
- (nonnull instancetype)initWithLanguageForSpeechInput:(NSString * _Nullable)languageForSpeechInput audioChannel:(enum AIBudsAIChatAudioChannel)audioChannel allowUserToInterruptAIResponse:(BOOL)allowUserToInterruptAIResponse maxPauseDurationBeforeAIResponds:(NSTimeInterval)maxPauseDurationBeforeAIResponds autoEndSessionAfterNoInputDuration:(NSTimeInterval)autoEndSessionAfterNoInputDuration enableVoicePlayback:(BOOL)enableVoicePlayback shouldSaveInputVoiceForDebugging:(BOOL)shouldSaveInputVoiceForDebugging additionalOptions:(NSDictionary<NSString *, id> * _Nonnull)additionalOptions OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsAIChatSessionConfig (SWIFT_EXTENSION(AIBudsAIFoundation)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// A model representing a segment of voice data in an AI chat response.
/// The voice data is in PCM format with the following properties:
/// <ul>
///   <li>
///     Sample rate: 16 kHz
///   </li>
///   <li>
///     Bit depth: 16-bit
///   </li>
///   <li>
///     Channels: Mono
///   </li>
///   <li>
///     Interleaved: Yes
///   </li>
///   <li>
///     Endianness: Little-endian
///   </li>
///   <li>
///     Sample format: Signed-integer
///   </li>
/// </ul>
SWIFT_CLASS_NAMED("AIChatVoiceDataModel")
@interface AIBudsAIChatVoiceDataModel : NSObject
/// The unique identifier for the voice.
@property (nonatomic, readonly, copy) NSString * _Nonnull voiceId;
/// The PCM audio data for this segment.
/// PCM data: 16 kHz, 16-bit, mono, interleaved, little-endian, signed-integer.
@property (nonatomic, readonly, copy) NSData * _Nonnull pcmSegmentData;
/// Indicates whether this is the final segment of the voice response.
@property (nonatomic, readonly) BOOL isFinal;
/// Initializes a new voice response segment.
/// \param voiceId The unique identifier for the voice.
///
/// \param pcmSegmentData The PCM audio data for this segment.
/// PCM data: 16 kHz, 16-bit, mono, interleaved, little-endian, signed-integer.
///
/// \param isFinal Indicates whether this is the final segment of the voice response.
///
- (nonnull instancetype)initWithVoiceId:(NSString * _Nonnull)voiceId pcmSegmentData:(NSData * _Nonnull)pcmSegmentData isFinal:(BOOL)isFinal OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsDeviceProduct)
@class NSCoder;
/// A model representing information about an AI device.
SWIFT_CLASS_NAMED("AIDeviceInfoModel")
@interface AIBudsAIDeviceInfoModel : NSObject <NSSecureCoding>
/// The product type of the device.
@property (nonatomic, readonly) enum AIBudsDeviceProduct product;
/// The display name of the device.
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// The bluetooth name of the device.
@property (nonatomic, readonly, copy) NSString * _Nullable bluetoothName;
/// The MAC address of the device, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable macAddress;
/// The model identifier of the device, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable model;
/// The formatted project number of the device, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable formatedProjNumber;
/// The formatted firmware version of the device, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable formatedFirmwareVersion;
/// The user identifier associated with the device, if available.
@property (nonatomic, readonly, copy) NSString * _Nullable userID;
/// Additional key-value information about the device, if available.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable additionalInfo;
/// Initializes a new device info model with only the product and name.
/// \param product The product type of the device.
///
/// \param name The display name of the device.
///
- (nonnull instancetype)initWithProduct:(enum AIBudsDeviceProduct)product name:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
/// Initializes a new device info model.
/// \param product The product type of the device.
///
/// \param name The display name of the device.
///
/// \param bluetoothName The bluetooth name of the device.
///
/// \param macAddress The MAC address of the device.
///
/// \param model The model identifier of the device.
///
/// \param formatedProjNumber The formatted project number of the device.
///
/// \param formatedFirmwareVersion The formatted firmware version of the device.
///
/// \param userID The user identifier associated with the device.
///
/// \param additionalInfo Additional key-value information about the device.
///
- (nonnull instancetype)initWithProduct:(enum AIBudsDeviceProduct)product name:(NSString * _Nonnull)name bluetoothName:(NSString * _Nullable)bluetoothName macAddress:(NSString * _Nullable)macAddress model:(NSString * _Nullable)model formatedProjNumber:(NSString * _Nullable)formatedProjNumber formatedFirmwareVersion:(NSString * _Nullable)formatedFirmwareVersion userID:(NSString * _Nullable)userID additionalInfo:(NSDictionary<NSString *, id> * _Nullable)additionalInfo OBJC_DESIGNATED_INITIALIZER;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsAIDeviceInfoModel (SWIFT_EXTENSION(AIBudsAIFoundation)) <NSCopying>
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end

/// Intent type
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsAIIntentType, "AIIntentType", open) {
/// unknown
  AIBudsAIIntentTypeUnknown = -1,
/// No intent
  AIBudsAIIntentTypeNone = 0,
/// Start taking photo
  AIBudsAIIntentTypePhotoStart = 1,
/// Understand photo content
  AIBudsAIIntentTypePhotoUnderstand = 2,
/// Start recording audio
  AIBudsAIIntentTypeAudioRecording = 3,
/// Start recording video
  AIBudsAIIntentTypeVideoStart = 4,
/// Stop recording video
  AIBudsAIIntentTypeVideoStop = 5,
/// Increase volume
  AIBudsAIIntentTypeVolumeUp = 6,
/// Decrease volume
  AIBudsAIIntentTypeVolumeDown = 7,
/// Set volume
  AIBudsAIIntentTypeVolumeSet = 8,
/// Exit dialog
  AIBudsAIIntentTypeDialogExit = 9,
/// Switch role
  AIBudsAIIntentTypeRoleSet = 10,
/// Power off device
  AIBudsAIIntentTypeDevicePowerOff = 11,
/// Voice clone
  AIBudsAIIntentTypeVoiceClone = 12,
/// Play music
  AIBudsAIIntentTypeMusicPlay = 13,
/// Play next track
  AIBudsAIIntentTypeMusicNext = 14,
/// Play previous track
  AIBudsAIIntentTypeMusicPrev = 15,
/// Stop playback
  AIBudsAIIntentTypeMusicStop = 16,
/// Check battery
  AIBudsAIIntentTypeDeviceBattery = 17,
/// Answer the incoming call
  AIBudsAIIntentTypeAnswerCall = 18,
/// Decline the incoming call
  AIBudsAIIntentTypeDeclineCall = 19,
/// Start recording incoming call
  AIBudsAIIntentTypeCallRecording = 20,
};

/// Enumeration for the ai service vendor
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsAIServiceVendor, "AIServiceVendor", open) {
/// No ai service vendor is set
/// note:
/// This is the default value
  AIBudsAIServiceVendorNone = 0,
/// StarBurst AI, provided by ByteDance
  AIBudsAIServiceVendorStarBurst = 1,
/// MLTCloud AI, provided by MLTCloud
  AIBudsAIServiceVendorMltcloud = 2,
};

/// Configuration class for simultaneous interpretation settings.
SWIFT_CLASS_NAMED("SimultaneousInterpretationConfig")
@interface AIBudsSimultaneousInterpretationConfig : NSObject
/// The default configuration shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsSimultaneousInterpretationConfig * _Nonnull defaultConfig;)
+ (AIBudsSimultaneousInterpretationConfig * _Nonnull)defaultConfig SWIFT_WARN_UNUSED_RESULT;
/// The source language code, e.g. “zh-CN”. Empty string means auto-detect.
/// A string representing the language identifier, if not provided, the system will use the current app’s localization language (iOS allows setting a specific language per app).
/// > Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>zh-CN</code>
/// - Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “zh” for Chinese)
/// - Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “CN” for China)
@property (nonatomic, copy) NSString * _Nullable sourceLanguage;
/// The target language code, e.g. “en-US”.
/// A string representing the language identifier, if not provided, the default value is “en-US”.
/// > Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>en-US</code>
/// - Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “en” for English)
/// - Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “US” for United States)
@property (nonatomic, copy) NSString * _Nonnull targetLanguage;
/// Indicates whether TTS (Text-to-Speech) is enabled, default is <code>true</code>.
@property (nonatomic) BOOL enableTTS;
/// Indicates whether voice playback is enabled, default is <code>true</code>.
@property (nonatomic) BOOL enableVoicePlayback;
/// Initializes a new instance of the <code>SimultaneousInterpretationConfig</code> class.
/// \param targetLanguage The target language code, e.g. “en-US”. Default is “en-US”.
///
/// \param sourceLanguage The source language code, e.g. “zh-CN”. Empty string means auto-detect. Default is <code>nil</code>.
///
- (nonnull instancetype)initWithTargetLanguage:(NSString * _Nonnull)targetLanguage sourceLanguage:(NSString * _Nullable)sourceLanguage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
@class AIBudsSpeakerSegment;
/// Simultaneous interpretation data model.
SWIFT_CLASS_NAMED("SimultaneousInterpretationDataModel")
@interface AIBudsSimultaneousInterpretationDataModel : NSObject
/// Sequence number for the model response.
@property (nonatomic, readonly) NSInteger sequence;
/// Request ID.
@property (nonatomic, readonly, copy) NSString * _Nullable requestId;
/// Source text.
@property (nonatomic, readonly, copy) NSString * _Nullable sourceText;
/// Is source text definite.
@property (nonatomic, readonly) BOOL isSourceTextDefinite;
/// Source text sequence number.
@property (nonatomic, readonly, strong) NSNumber * _Nullable sourceTextSequence;
/// Target text.
@property (nonatomic, readonly, copy) NSString * _Nullable targetText;
/// Is target text definite.
@property (nonatomic, readonly) BOOL isTargetTextDefinite;
/// Target text sequence number.
@property (nonatomic, readonly, strong) NSNumber * _Nullable targetTextSequence;
/// Base64 encoded audio data of TTS result for target text.
@property (nonatomic, readonly, copy) NSString * _Nullable base64AudioData;
/// Audio data sequence number.
@property (nonatomic, readonly, strong) NSNumber * _Nullable audioDataSequence;
/// Associated target text sequence number for the audio data.
@property (nonatomic, readonly, strong) NSNumber * _Nullable associatedTargetTextSequenceForAudioData;
/// Speaker segments.
@property (nonatomic, readonly, copy) NSArray<AIBudsSpeakerSegment *> * _Nullable speakerSegments;
/// Initializes a new instance of the <code>SimultaneousInterpretationDataModel</code> class.
/// \param sequence Sequence number.
///
/// \param requestId Request ID.
///
/// \param sourceText Source text.
///
/// \param isSourceTextDefinite Is source text definite.
///
/// \param sourceTextSequence Source text sequence number.
///
/// \param targetText Target text.
///
/// \param isTargetTextDefinite Is target text definite.
///
/// \param targetTextSequence Target text sequence number.
///
/// \param base64AudioData Base64 encoded audio data of TTS result for target text.
///
/// \param audioDataSequence Audio data sequence number.
///
/// \param associatedTargetTextSequenceForAudioData Associated target text sequence number with audio data.
///
/// \param speakerSegments Speaker segments.
///
- (nonnull instancetype)initWithSequence:(NSInteger)sequence requestId:(NSString * _Nullable)requestId sourceText:(NSString * _Nullable)sourceText isSourceTextDefinite:(BOOL)isSourceTextDefinite sourceTextSequence:(NSNumber * _Nullable)sourceTextSequence targetText:(NSString * _Nullable)targetText isTargetTextDefinite:(BOOL)isTargetTextDefinite targetTextSequence:(NSNumber * _Nullable)targetTextSequence base64AudioData:(NSString * _Nullable)base64AudioData audioDataSequence:(NSNumber * _Nullable)audioDataSequence associatedTargetTextSequenceForAudioData:(NSNumber * _Nullable)associatedTargetTextSequenceForAudioData speakerSegments:(NSArray<AIBudsSpeakerSegment *> * _Nullable)speakerSegments OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Speaker segment
SWIFT_CLASS_NAMED("SpeakerSegment")
@interface AIBudsSpeakerSegment : NSObject
/// Sequence number of the speaker segment
@property (nonatomic, readonly) NSInteger sequence;
/// Speaker ID
@property (nonatomic, readonly, copy) NSString * _Nullable speakerId;
/// Start time in milliseconds
@property (nonatomic, readonly) NSInteger startTimeMs;
/// End time in milliseconds
@property (nonatomic, readonly) NSInteger endTimeMs;
/// Text of the speaker segment
@property (nonatomic, readonly, copy) NSString * _Nullable text;
/// Initializes a new speaker segment.
/// \param sequence Sequence number of the speaker segment.
///
/// \param speakerId Speaker ID.
///
/// \param startTimeMs Start time in milliseconds.
///
/// \param endTimeMs End time in milliseconds.
///
/// \param text Text of the speaker segment.
///
- (nonnull instancetype)initWithStartTimeMs:(NSInteger)sequence endTimeMs:(NSString * _Nullable)speakerId sequence:(NSInteger)startTimeMs speakerId:(NSInteger)endTimeMs text:(NSString * _Nullable)text OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface AIBudsSpeakerSegment (SWIFT_EXTENSION(AIBudsAIFoundation)) <AIBudsCustomDebugJsonStringConvertible>
/// Debug JSON string
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
@end

/// Stream speech ASR data model.
SWIFT_CLASS_NAMED("StreamSpeechASRModel")
@interface AIBudsStreamSpeechASRModel : NSObject <AIBudsCustomDebugJsonStringConvertible>
/// Sequence number for the model response.
@property (nonatomic, readonly) NSInteger sequence;
/// Request ID.
@property (nonatomic, readonly, copy) NSString * _Nullable requestId;
/// Transcript text.
/// This text will be returned multiple times. For example, the complete sentence <code>"Hello, I am a student."</code> will be returned incrementally:
/// \code
/// "Hello"
/// "Hello, I"
/// "Hello, I am a student."
///
/// \endcode
@property (nonatomic, readonly, copy) NSString * _Nullable transcript;
/// Is current transcript text definite.
@property (nonatomic, readonly) BOOL isDefinite;
/// Transcript text sequence number.
@property (nonatomic, readonly, strong) NSNumber * _Nullable transcriptSequence;
/// Speaker segments.
@property (nonatomic, readonly, copy) NSArray<AIBudsSpeakerSegment *> * _Nullable speakerSegments;
/// Initializes a new instance of the <code>StreamSpeechASRModel</code> class.
/// \param sequence Sequence number.
///
/// \param requestId Request ID.
///
/// \param transcript Transcript text.
/// This text will be returned multiple times. For example, the complete sentence <code>"Hello, I am a student."</code> will be returned incrementally:
/// \code
/// "Hello"
/// "Hello, I"
/// "Hello, I am a student."
///
/// \endcode
/// \param isDefinite Is current transcript text definite.
///
/// \param transcriptSequence Transcript text sequence number.
///
/// \param speakerSegments Speaker segments.
///
- (nonnull instancetype)initWithSequence:(NSInteger)sequence requestId:(NSString * _Nullable)requestId transcript:(NSString * _Nullable)transcript isDefinite:(BOOL)isDefinite transcriptSequence:(NSNumber * _Nullable)transcriptSequence speakerSegments:(NSArray<AIBudsSpeakerSegment *> * _Nullable)speakerSegments OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugJsonString;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Configuration class for streaming ASR settings.
SWIFT_CLASS_NAMED("StreamingASRConfig")
@interface AIBudsStreamingASRConfig : NSObject
/// The default configuration shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsStreamingASRConfig * _Nonnull defaultConfig;)
+ (AIBudsStreamingASRConfig * _Nonnull)defaultConfig SWIFT_WARN_UNUSED_RESULT;
/// The language setting for speech input
/// A string representing the language identifier, if not provided, the system will use the current app’s localization language (iOS allows setting a specific language per app).
/// > Important: Language identifiers must follow the hyphenated format specification, e.g.: <code>zh-CN</code>
/// - Part1: Language code (ISO 639-1) - Two letters identifying the base language (e.g., “zh” for Chinese)
/// - Part2: Country/Region code (ISO 3166-1) - Optional two letters specifying the country or region (e.g., “CN” for China)
@property (nonatomic, readonly, copy) NSString * _Nullable languageForSpeechInput;
/// The audio format for speech input
@property (nonatomic, readonly) enum AIBudsAIAudioFormat audioFormat;
/// Initializes a new instance of the <code>StreamingASRConfig</code> class.
/// \param languageForSpeechInput The language setting for speech input. Default is <code>nil</code>.
///
/// \param audioFormat The audio format for speech input. Default is <code>.pcm</code>.
///
- (nonnull instancetype)initWithLanguageForSpeechInput:(NSString * _Nullable)languageForSpeechInput audioFormat:(enum AIBudsAIAudioFormat)audioFormat OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Configuration class for tts settings.
SWIFT_CLASS_NAMED("TTSConfig")
@interface AIBudsTTSConfig : NSObject
/// The default configuration shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsTTSConfig * _Nonnull defaultConfig;)
+ (AIBudsTTSConfig * _Nonnull)defaultConfig SWIFT_WARN_UNUSED_RESULT;
/// The speaker ID for speech, for example, <code>"zh_female_vv_uranus_bigtts"</code>.
@property (nonatomic, copy) NSString * _Nullable speakerId;
/// Initializes a new instance of the <code>TTSConfig</code> class.
/// \param speakerId The speaker ID for speech. Default is <code>nil</code>.
///
- (nonnull instancetype)initWithSpeakerId:(NSString * _Nullable)speakerId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Text-to-speech response model.
SWIFT_CLASS_NAMED("TTSResultModel")
@interface AIBudsTTSResultModel : NSObject
/// Text-to-speech response audio file (relative to the documents directory).
@property (nonatomic, readonly, copy) NSString * _Nonnull audioFile;
/// Audio format of the text-to-speech response audio file.
@property (nonatomic, readonly) enum AIBudsAIAudioFormat audioFormat;
/// Initialize the model with the specified audio file and format.
/// \param audioFile The relative path to the audio file (relative to the documents directory).
///
/// \param audioFormat The audio format of the audio file.
///
- (nonnull instancetype)initWithAudioFile:(NSString * _Nonnull)audioFile audioFormat:(enum AIBudsAIAudioFormat)audioFormat OBJC_DESIGNATED_INITIALIZER;
/// Full path to the text-to-speech response audio file.
@property (nonatomic, readonly, copy) NSString * _Nonnull audioFilePath;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
