# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'
ENV['COCOAPODS_SKIP_BUNDLE_INSTALL'] = '1'

platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

# Define a reusable method to include shared pods across targets
def commonPods
  
end

workspace 'AIBuds.xcworkspace'



target 'AIBudsSDK-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  project 'AIBuds.xcodeproj'

  # Include common pods
  commonPods
  
  pod 'iOSLogBrowserSDK'
  pod 'Reachability'
  pod 'Popover.OC'
  pod 'DZNEmptyDataSet'
  pod 'Toast'
  pod 'AIBudsSDK/AllInOne', :path => '../'
  
end

dynamic_frameworks = ['AFNetworking', 'WCDB.swift', 'WCDBOptimizedSQLCipher']
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if dynamic_frameworks.include?(pod.name)
      def pod.static_framework?;
        false
      end
      def pod.build_type;
        Pod::BuildType.dynamic_framework
      end
    end
  end
end

def patch_private_header(installer, pod_subdir_pairs)
  
  pod_subdir_pairs.each do |pod_name, sub_dir|
    target_dir = sub_dir ? File.join(installer.sandbox.pod_dir(pod_name), sub_dir) : installer.sandbox.pod_dir(pod_name)
    puts target_dir
    next unless Dir.exist?(target_dir)

    private_header_import = '#import <netinet6/in6.h>'
    Dir.glob(File.join(target_dir, '**', '*.{h,m}')).each do |file_path|
      puts file_path
      next unless File.exist?(file_path)

      file_content = File.read(file_path)
      next unless file_content.include?(private_header_import)

      original_mode = File.stat(file_path).mode
      File.chmod(original_mode | 0o200, file_path)
      File.write(file_path, file_content.gsub(private_header_import, ''))
      File.chmod(original_mode, file_path)
      puts "patched #{pod_name} private header import: #{File.basename(file_path)}"
    end
  end
end

post_install do |installer|
  patch_private_header(installer, {'AFNetworking' => 'AFNetworking', 'Reachability' => nil })
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
