#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3 effective-5.10 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef AIBUDSLOG_SWIFT_H
#define AIBUDSLOG_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsLog",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsLog",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@protocol AIBudsLogService;
@class AIBudsLogConfiguration;
@protocol AIBudsXLFacilityPlugin;
/// The main entry point for the AIBudsLogSDK.
/// Use this class to access SDK version information and other global SDK-level functionality.
SWIFT_CLASS("_TtC9AIBudsLog12AIBudsLogSDK")
@interface AIBudsLogSDK : NSObject
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of AIBudsLogSDK
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The version number of the SDK
///
/// returns:
/// A string representing the current SDK version (e.g. “1.0.0-beta.1”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// The build number of the SDK
///
/// returns:
/// A string representing the SDK build number (e.g. “20250315001”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkBuild;)
+ (NSString * _Nonnull)sdkBuild SWIFT_WARN_UNUSED_RESULT;
/// The release date of the SDK
///
/// returns:
/// A string representing the SDK release date in YYYY-MM-DD format
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkReleaseDate;)
+ (NSString * _Nonnull)sdkReleaseDate SWIFT_WARN_UNUSED_RESULT;
/// Returns a formatted string containing SDK version information
/// note:
/// The returned string includes an emoji prefix and is formatted for easy reading
///
/// returns:
/// A string containing the SDK name, version, build number and release date
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersionDescription;)
+ (NSString * _Nonnull)sdkVersionDescription SWIFT_WARN_UNUSED_RESULT;
/// Returns the current log service
/// note:
/// If no custom log service has been set, the default <code>DefaultLogger</code> is returned
///
/// returns:
/// An object conforming to <code>AIBudsLog.LogService</code> that will handle logging
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <AIBudsLogService> _Nonnull logService;)
+ (id <AIBudsLogService> _Nonnull)logService SWIFT_WARN_UNUSED_RESULT;
/// The current log configuration
///
/// returns:
/// An LogConfiguration object containing the current log settings
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsLogConfiguration * _Nonnull logConfiguration;)
+ (AIBudsLogConfiguration * _Nonnull)logConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Sets a custom log service for the SDK
/// important:
/// This method should be called before using any logging functionality
/// note:
/// Only one log service can be active at a time. Setting a new service replaces the existing one
/// \param logService An object conforming to <code>AIBudsLog.LogService</code> that will handle logging
///
+ (void)setLogService:(id <AIBudsLogService> _Nonnull)logService;
/// Adds an XLFacilityPlugin to the SDK
/// \param plugin An object conforming to <code>AIBudsLog.XLFacilityPlugin</code> that will handle logging to XLFacility
///
+ (void)setXLFacilityPlugin:(id <AIBudsXLFacilityPlugin> _Nonnull)plugin;
@end

@interface AIBudsLogSDK (SWIFT_EXTENSION(AIBudsLog))
/// The error domain used for AIBudsLogSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorDomain;)
+ (NSString * _Nonnull)ErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// The error key used for AIBudsLogSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorKey;)
+ (NSString * _Nonnull)ErrorKey SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsLogLevel)
@class NSDate;
@class NSError;
/// Protocol that provides unified logging capabilities.
/// Implementers are responsible for outputting log messages by the specified level, subsystem, and category.
SWIFT_PROTOCOL_NAMED("LogService")
@protocol AIBudsLogService <NSObject>
/// Records a log message.
/// \param message The content of the log to be recorded.
///
/// \param level The log level, used to distinguish the severity of the log.
///
/// \param subsystem Optional, identifies the subsystem to which the log belongs.
///
/// \param category Optional, identifies the category to which the log belongs.
///
- (void)logMessage:(NSString * _Nonnull)message level:(enum AIBudsLogLevel)level subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a verbose log message.
/// \param message The content of the verbose log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the verbose log belongs.
///
/// \param category Optional, identifies the category to which the verbose log belongs.
///
- (void)verbose:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a debug log message.
/// \param message The content of the debug log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the debug log belongs.
///
/// \param category Optional, identifies the category to which the debug log belongs.
///
- (void)debug:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a info log message.
/// \param message The content of the info log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the info log belongs.
///
/// \param category Optional, identifies the category to which the info log belongs.
///
- (void)info:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a warning log message.
/// \param message The content of the warning log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the warning log belongs.
///
/// \param category Optional, identifies the category to which the warning log belongs.
///
- (void)warn:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a error log message.
/// \param message The content of the error log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the error log belongs.
///
/// \param category Optional, identifies the category to which the error log belongs.
///
- (void)error:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a fatal log message.
/// \param message The content of the fatal log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the fatal log belongs.
///
/// \param category Optional, identifies the category to which the fatal log belongs.
///
- (void)fatal:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Exports all log messages to a file.
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePath: The path to the exported log file, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
- (void)exportLogsWithCompletion:(void (^ _Nullable)(NSString * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Exports log messages to multiple files with size limit.
/// \param maxFileSize The maximum size of each log file in bytes.
///
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePaths: An array of paths to the exported log files, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
- (void)exportLogsWithMaxFileSize:(uint64_t)maxFileSize completion:(void (^ _Nullable)(NSArray<NSString *> * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified max age.
/// \param maxAge The maximum age in days for log messages to be retained.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsWithMaxAge:(NSInteger)maxAge completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified date.
/// \param timestamp The timestamp before which log messages should be purged.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsBefore:(NSDate * _Nonnull)timestamp completion:(void (^ _Nullable)(NSError * _Nullable))completion;
@end

/// The default logger implementation for the AIBudsLog SDK.
/// This class records log messages to the console and a log file,
/// with support for log levels and optional subsystem and category identification.
SWIFT_CLASS_NAMED("DefaultLogger")
@interface AIBudsDefaultLogger : NSObject <AIBudsLogService>
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of DefaultLogger
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Singleton instance of <code>DefaultLogger</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsDefaultLogger * _Nonnull shared;)
+ (AIBudsDefaultLogger * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Records a log message.
/// \param message The content of the log to be recorded.
///
/// \param level The log level, used to distinguish the severity of the log.
///
/// \param subsystem Optional, identifies the subsystem to which the log belongs.
///
/// \param category Optional, identifies the category to which the log belongs.
///
- (void)logMessage:(NSString * _Nonnull)message level:(enum AIBudsLogLevel)level subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a verbose log message.
/// \param message The content of the verbose log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the verbose log belongs.
///
/// \param category Optional, identifies the category to which the verbose log belongs.
///
- (void)verbose:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a debug log message.
/// \param message The content of the debug log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the debug log belongs.
///
/// \param category Optional, identifies the category to which the debug log belongs.
///
- (void)debug:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a info log message.
/// \param message The content of the info log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the info log belongs.
///
/// \param category Optional, identifies the category to which the info log belongs.
///
- (void)info:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a warning log message.
/// \param message The content of the warning log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the warning log belongs.
///
/// \param category Optional, identifies the category to which the warning log belongs.
///
- (void)warn:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a error log message.
/// \param message The content of the error log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the error log belongs.
///
/// \param category Optional, identifies the category to which the error log belongs.
///
- (void)error:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a fatal log message.
/// \param message The content of the fatal log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the fatal log belongs.
///
/// \param category Optional, identifies the category to which the fatal log belongs.
///
- (void)fatal:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Exports all log messages to a file.
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePath: The path to the exported log file, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
/// \a completion returns: 
/// Void
///
- (void)exportLogsWithCompletion:(void (^ _Nullable)(NSString * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Exports log messages to multiple files with size limit.
/// \param maxFileSize The maximum size of each log file in bytes.
///
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePaths: An array of paths to the exported log files, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
/// \a completion returns: 
/// Void
///
- (void)exportLogsWithMaxFileSize:(uint64_t)maxFileSize completion:(void (^ _Nullable)(NSArray<NSString *> * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified max age.
/// \param maxAge The maximum age in days for log messages to be retained.
///
/// \param completion The completion handler that is called when the purge operation is completed.
/// <ul>
///   <li>
///     error: The error object, or nil if the purge operation was successful.
///   </li>
/// </ul>
///
- (void)purgeOldLogsWithMaxAge:(NSInteger)maxAge completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified date.
/// \param timestamp The timestamp before which log messages should be purged.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsBefore:(NSDate * _Nonnull)timestamp completion:(void (^ _Nullable)(NSError * _Nullable))completion;
@end

@class NSURL;
@class NSProgress;
@interface NSFileManager (SWIFT_EXTENSION(AIBudsLog))
/// Extracts the tar at <code>tarURL</code> to <code>dirURL</code>.
/// \param at The path of the Tar file to extract.
///
/// \param to The path to which to extract the Tar file. A directory will be created at this path containing the extracted files.
///
/// \param restoreAttributes If <code>false</code>, file attributes stored in the archive such as modification dates and file
/// permissions be ignored. This can significantly speed up the extraction process.
///
/// \param progressBody A closure with a <code>Double</code> parameter representing the current progress (from 0.0 to 1.0).
///
- (BOOL)extractTarAtURL:(NSURL * _Nonnull)tarURL toDirectoryAtURL:(NSURL * _Nonnull)dirURL restoreAttributes:(BOOL)restoreAttributes progressBlock:(NSProgress * _Nullable)progress error:(NSError * _Nullable * _Nullable)error;
/// Creates a Tar file at <code>tarURL</code>.
/// \param at The path at which the Tar file should be created.
///
/// \param from A directory containing the files that that should be archived.
///
/// \param convertAliasFiles The Tar format doesn’t support alias files by default, only symbolic links. If this
/// is set to <code>true</code>, archiving will check for alias files and store them as symbolic links. This can take longer.
///
/// \param progressBody A closure with a <code>Double</code> parameter representing the current progress (from 0.0 to 1.0).
///
- (BOOL)createTarAtURL:(NSURL * _Nonnull)tarURL fromDirectoryAtURL:(NSURL * _Nonnull)dirURL convertAliasFiles:(BOOL)convertAliasFiles progressBlock:(NSProgress * _Nullable)progress error:(NSError * _Nullable * _Nullable)error;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsLogDestination)
SWIFT_CLASS_NAMED("LogConfiguration")
@interface AIBudsLogConfiguration : NSObject
/// The directory for log files. Default is “.aibuds/logs”.
/// Note: Only relative paths to NSDocumentDirectory are allowed; absolute paths are not permitted.
@property (nonatomic, copy) NSString * _Nonnull logsDirectory;
/// Maximum size of a single log file, default is 10MB
@property (nonatomic) uint64_t maxFileSize;
/// Maximum age (in days) for log files, default is 3 days
@property (nonatomic) NSInteger logFileMaxAge;
/// The severity level for logging. Default is <code>.info</code>.
@property (nonatomic) enum AIBudsLogLevel level;
/// The destination for log output. Default is <code>.xlfacility</code>.
@property (nonatomic) enum AIBudsLogDestination destination;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of AIBudsLogSDK
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Singleton instance of <code>LogConfiguration</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsLogConfiguration * _Nonnull shared;)
+ (AIBudsLogConfiguration * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@end

/// Specifies the destination for log output.
/// Use <code>LogDestination</code> to choose where log messages should be sent:
/// <ul>
///   <li>
///     <code>.console</code>: Printed to the Xcode debugger console.
///   </li>
///   <li>
///     <code>.oslogger</code>: Routed through <code>os_log</code> for system-wide visibility.
///   </li>
///   <li>
///     <code>.file</code>: Written to a specified file on disk.
///   </li>
///   <li>
///     <code>.xlfacility</code>: Forwarded to the xlfacility.
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsLogDestination, "LogDestination", open) {
/// Logs are printed to the Xcode debugger console.
  AIBudsLogDestinationConsole = 0,
/// Logs are routed through <code>os_log</code> for system-wide visibility.
  AIBudsLogDestinationOslogger = 1,
/// Logs are written to a specified file on disk.
  AIBudsLogDestinationFile = 2,
/// Logs are forwarded to the xlfacility.
  AIBudsLogDestinationXlfacility = 3,
};

/// The severity levels used by AIBudsLog.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsLogLevel, "LogLevel", open) {
/// The most detailed level, used for tracing execution flow.
  AIBudsLogLevelVerbose = 0,
/// Detailed diagnostic information, useful during development.
  AIBudsLogLevelDebug = 1,
/// General informational messages that highlight progress.
  AIBudsLogLevelInfo = 2,
/// Potentially harmful situations that may require attention.
  AIBudsLogLevelWarn = 3,
/// Error events that might still allow the application to continue.
  AIBudsLogLevelError = 4,
/// Critical errors that may cause the application to terminate.
  AIBudsLogLevelFatal = 5,
/// A special level that disables all logging output.
  AIBudsLogLevelMute = 2147483647,
};

/// The error codes used for AIBudsLogSDK errors
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsLogSdkErrorCode, "SdkErrorCode", open) {
/// Unknown error
  AIBudsLogSdkErrorCodeUnknown = -1,
/// Invalid parameter
  AIBudsLogSdkErrorCodeInvalidParameter = 1,
/// The current log destination does not support log export.
  AIBudsLogSdkErrorCodeDestinationNotSupportExport = 1001,
/// The current log destination plugin is not configured.
  AIBudsLogSdkErrorCodeDestinationPluginNotConfigured = 1002,
/// The current log destination does not support log purge.
  AIBudsLogSdkErrorCodeDestinationNotSupportPurge = 1003,
/// The log root URL is not configured.
  AIBudsLogSdkErrorCodeLogRootUnavailable = 1004,
/// Failed to calculate cut-off time.
  AIBudsLogSdkErrorCodeFailedToCalculateCutOffTime = 1005,
/// Failed to enumerate log directories.
  AIBudsLogSdkErrorCodeFailedToEnumerateLogDirectories = 1006,
};

/// The protocol for plugins that record log messages to XLFacility.
SWIFT_PROTOCOL_NAMED("XLFacilityPlugin")
@protocol AIBudsXLFacilityPlugin <NSObject>
/// Indicates whether the plugin is loaded and ready to use.
@property (nonatomic, readonly) BOOL isLoaded;
/// Loads the plugin, initializing any necessary resources.
- (void)load;
/// Exports all log messages to a file.
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePath: The path to the exported log file, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
- (void)exportLogsWithCompletion:(void (^ _Nullable)(NSString * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Exports log messages to multiple files with size limit.
/// \param maxFileSize The maximum size of each log file in bytes.
///
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePaths: An array of paths to the exported log files, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
- (void)exportLogsWithMaxFileSize:(uint64_t)maxFileSize completion:(void (^ _Nullable)(NSArray<NSString *> * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified max age.
/// \param maxAge The maximum age in days for log messages to be retained.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsWithMaxAge:(NSInteger)maxAge completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified date.
/// \param timestamp The timestamp before which log messages should be purged.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsBefore:(NSDate * _Nonnull)timestamp completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Records a log message.
/// \param message The content of the log to be recorded.
///
/// \param level The log level, used to distinguish the severity of the log.
///
/// \param subsystem Optional, identifies the subsystem to which the log belongs.
///
/// \param category Optional, identifies the category to which the log belongs.
///
- (void)logMessage:(NSString * _Nonnull)message level:(enum AIBudsLogLevel)level subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3 effective-5.10 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef AIBUDSLOG_SWIFT_H
#define AIBUDSLOG_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsLog",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIBudsLog",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@protocol AIBudsLogService;
@class AIBudsLogConfiguration;
@protocol AIBudsXLFacilityPlugin;
/// The main entry point for the AIBudsLogSDK.
/// Use this class to access SDK version information and other global SDK-level functionality.
SWIFT_CLASS("_TtC9AIBudsLog12AIBudsLogSDK")
@interface AIBudsLogSDK : NSObject
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of AIBudsLogSDK
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The version number of the SDK
///
/// returns:
/// A string representing the current SDK version (e.g. “1.0.0-beta.1”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// The build number of the SDK
///
/// returns:
/// A string representing the SDK build number (e.g. “20250315001”)
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkBuild;)
+ (NSString * _Nonnull)sdkBuild SWIFT_WARN_UNUSED_RESULT;
/// The release date of the SDK
///
/// returns:
/// A string representing the SDK release date in YYYY-MM-DD format
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkReleaseDate;)
+ (NSString * _Nonnull)sdkReleaseDate SWIFT_WARN_UNUSED_RESULT;
/// Returns a formatted string containing SDK version information
/// note:
/// The returned string includes an emoji prefix and is formatted for easy reading
///
/// returns:
/// A string containing the SDK name, version, build number and release date
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersionDescription;)
+ (NSString * _Nonnull)sdkVersionDescription SWIFT_WARN_UNUSED_RESULT;
/// Returns the current log service
/// note:
/// If no custom log service has been set, the default <code>DefaultLogger</code> is returned
///
/// returns:
/// An object conforming to <code>AIBudsLog.LogService</code> that will handle logging
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <AIBudsLogService> _Nonnull logService;)
+ (id <AIBudsLogService> _Nonnull)logService SWIFT_WARN_UNUSED_RESULT;
/// The current log configuration
///
/// returns:
/// An LogConfiguration object containing the current log settings
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsLogConfiguration * _Nonnull logConfiguration;)
+ (AIBudsLogConfiguration * _Nonnull)logConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Sets a custom log service for the SDK
/// important:
/// This method should be called before using any logging functionality
/// note:
/// Only one log service can be active at a time. Setting a new service replaces the existing one
/// \param logService An object conforming to <code>AIBudsLog.LogService</code> that will handle logging
///
+ (void)setLogService:(id <AIBudsLogService> _Nonnull)logService;
/// Adds an XLFacilityPlugin to the SDK
/// \param plugin An object conforming to <code>AIBudsLog.XLFacilityPlugin</code> that will handle logging to XLFacility
///
+ (void)setXLFacilityPlugin:(id <AIBudsXLFacilityPlugin> _Nonnull)plugin;
@end

@interface AIBudsLogSDK (SWIFT_EXTENSION(AIBudsLog))
/// The error domain used for AIBudsLogSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorDomain;)
+ (NSString * _Nonnull)ErrorDomain SWIFT_WARN_UNUSED_RESULT;
/// The error key used for AIBudsLogSDK errors
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ErrorKey;)
+ (NSString * _Nonnull)ErrorKey SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsLogLevel)
@class NSDate;
@class NSError;
/// Protocol that provides unified logging capabilities.
/// Implementers are responsible for outputting log messages by the specified level, subsystem, and category.
SWIFT_PROTOCOL_NAMED("LogService")
@protocol AIBudsLogService <NSObject>
/// Records a log message.
/// \param message The content of the log to be recorded.
///
/// \param level The log level, used to distinguish the severity of the log.
///
/// \param subsystem Optional, identifies the subsystem to which the log belongs.
///
/// \param category Optional, identifies the category to which the log belongs.
///
- (void)logMessage:(NSString * _Nonnull)message level:(enum AIBudsLogLevel)level subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a verbose log message.
/// \param message The content of the verbose log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the verbose log belongs.
///
/// \param category Optional, identifies the category to which the verbose log belongs.
///
- (void)verbose:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a debug log message.
/// \param message The content of the debug log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the debug log belongs.
///
/// \param category Optional, identifies the category to which the debug log belongs.
///
- (void)debug:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a info log message.
/// \param message The content of the info log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the info log belongs.
///
/// \param category Optional, identifies the category to which the info log belongs.
///
- (void)info:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a warning log message.
/// \param message The content of the warning log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the warning log belongs.
///
/// \param category Optional, identifies the category to which the warning log belongs.
///
- (void)warn:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a error log message.
/// \param message The content of the error log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the error log belongs.
///
/// \param category Optional, identifies the category to which the error log belongs.
///
- (void)error:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a fatal log message.
/// \param message The content of the fatal log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the fatal log belongs.
///
/// \param category Optional, identifies the category to which the fatal log belongs.
///
- (void)fatal:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Exports all log messages to a file.
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePath: The path to the exported log file, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
- (void)exportLogsWithCompletion:(void (^ _Nullable)(NSString * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Exports log messages to multiple files with size limit.
/// \param maxFileSize The maximum size of each log file in bytes.
///
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePaths: An array of paths to the exported log files, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
- (void)exportLogsWithMaxFileSize:(uint64_t)maxFileSize completion:(void (^ _Nullable)(NSArray<NSString *> * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified max age.
/// \param maxAge The maximum age in days for log messages to be retained.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsWithMaxAge:(NSInteger)maxAge completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified date.
/// \param timestamp The timestamp before which log messages should be purged.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsBefore:(NSDate * _Nonnull)timestamp completion:(void (^ _Nullable)(NSError * _Nullable))completion;
@end

/// The default logger implementation for the AIBudsLog SDK.
/// This class records log messages to the console and a log file,
/// with support for log levels and optional subsystem and category identification.
SWIFT_CLASS_NAMED("DefaultLogger")
@interface AIBudsDefaultLogger : NSObject <AIBudsLogService>
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of DefaultLogger
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Singleton instance of <code>DefaultLogger</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsDefaultLogger * _Nonnull shared;)
+ (AIBudsDefaultLogger * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Records a log message.
/// \param message The content of the log to be recorded.
///
/// \param level The log level, used to distinguish the severity of the log.
///
/// \param subsystem Optional, identifies the subsystem to which the log belongs.
///
/// \param category Optional, identifies the category to which the log belongs.
///
- (void)logMessage:(NSString * _Nonnull)message level:(enum AIBudsLogLevel)level subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a verbose log message.
/// \param message The content of the verbose log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the verbose log belongs.
///
/// \param category Optional, identifies the category to which the verbose log belongs.
///
- (void)verbose:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a debug log message.
/// \param message The content of the debug log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the debug log belongs.
///
/// \param category Optional, identifies the category to which the debug log belongs.
///
- (void)debug:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a info log message.
/// \param message The content of the info log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the info log belongs.
///
/// \param category Optional, identifies the category to which the info log belongs.
///
- (void)info:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a warning log message.
/// \param message The content of the warning log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the warning log belongs.
///
/// \param category Optional, identifies the category to which the warning log belongs.
///
- (void)warn:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a error log message.
/// \param message The content of the error log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the error log belongs.
///
/// \param category Optional, identifies the category to which the error log belongs.
///
- (void)error:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Records a fatal log message.
/// \param message The content of the fatal log to be recorded.
///
/// \param subsystem Optional, identifies the subsystem to which the fatal log belongs.
///
/// \param category Optional, identifies the category to which the fatal log belongs.
///
- (void)fatal:(NSString * _Nonnull)message subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
/// Exports all log messages to a file.
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePath: The path to the exported log file, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
/// \a completion returns: 
/// Void
///
- (void)exportLogsWithCompletion:(void (^ _Nullable)(NSString * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Exports log messages to multiple files with size limit.
/// \param maxFileSize The maximum size of each log file in bytes.
///
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePaths: An array of paths to the exported log files, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
/// \a completion returns: 
/// Void
///
- (void)exportLogsWithMaxFileSize:(uint64_t)maxFileSize completion:(void (^ _Nullable)(NSArray<NSString *> * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified max age.
/// \param maxAge The maximum age in days for log messages to be retained.
///
/// \param completion The completion handler that is called when the purge operation is completed.
/// <ul>
///   <li>
///     error: The error object, or nil if the purge operation was successful.
///   </li>
/// </ul>
///
- (void)purgeOldLogsWithMaxAge:(NSInteger)maxAge completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified date.
/// \param timestamp The timestamp before which log messages should be purged.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsBefore:(NSDate * _Nonnull)timestamp completion:(void (^ _Nullable)(NSError * _Nullable))completion;
@end

@class NSURL;
@class NSProgress;
@interface NSFileManager (SWIFT_EXTENSION(AIBudsLog))
/// Extracts the tar at <code>tarURL</code> to <code>dirURL</code>.
/// \param at The path of the Tar file to extract.
///
/// \param to The path to which to extract the Tar file. A directory will be created at this path containing the extracted files.
///
/// \param restoreAttributes If <code>false</code>, file attributes stored in the archive such as modification dates and file
/// permissions be ignored. This can significantly speed up the extraction process.
///
/// \param progressBody A closure with a <code>Double</code> parameter representing the current progress (from 0.0 to 1.0).
///
- (BOOL)extractTarAtURL:(NSURL * _Nonnull)tarURL toDirectoryAtURL:(NSURL * _Nonnull)dirURL restoreAttributes:(BOOL)restoreAttributes progressBlock:(NSProgress * _Nullable)progress error:(NSError * _Nullable * _Nullable)error;
/// Creates a Tar file at <code>tarURL</code>.
/// \param at The path at which the Tar file should be created.
///
/// \param from A directory containing the files that that should be archived.
///
/// \param convertAliasFiles The Tar format doesn’t support alias files by default, only symbolic links. If this
/// is set to <code>true</code>, archiving will check for alias files and store them as symbolic links. This can take longer.
///
/// \param progressBody A closure with a <code>Double</code> parameter representing the current progress (from 0.0 to 1.0).
///
- (BOOL)createTarAtURL:(NSURL * _Nonnull)tarURL fromDirectoryAtURL:(NSURL * _Nonnull)dirURL convertAliasFiles:(BOOL)convertAliasFiles progressBlock:(NSProgress * _Nullable)progress error:(NSError * _Nullable * _Nullable)error;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, AIBudsLogDestination)
SWIFT_CLASS_NAMED("LogConfiguration")
@interface AIBudsLogConfiguration : NSObject
/// The directory for log files. Default is “.aibuds/logs”.
/// Note: Only relative paths to NSDocumentDirectory are allowed; absolute paths are not permitted.
@property (nonatomic, copy) NSString * _Nonnull logsDirectory;
/// Maximum size of a single log file, default is 10MB
@property (nonatomic) uint64_t maxFileSize;
/// Maximum age (in days) for log files, default is 3 days
@property (nonatomic) NSInteger logFileMaxAge;
/// The severity level for logging. Default is <code>.info</code>.
@property (nonatomic) enum AIBudsLogLevel level;
/// The destination for log output. Default is <code>.xlfacility</code>.
@property (nonatomic) enum AIBudsLogDestination destination;
/// Private initializer to enforce singleton pattern
/// note:
/// This prevents creating multiple instances of AIBudsLogSDK
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Singleton instance of <code>LogConfiguration</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AIBudsLogConfiguration * _Nonnull shared;)
+ (AIBudsLogConfiguration * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@end

/// Specifies the destination for log output.
/// Use <code>LogDestination</code> to choose where log messages should be sent:
/// <ul>
///   <li>
///     <code>.console</code>: Printed to the Xcode debugger console.
///   </li>
///   <li>
///     <code>.oslogger</code>: Routed through <code>os_log</code> for system-wide visibility.
///   </li>
///   <li>
///     <code>.file</code>: Written to a specified file on disk.
///   </li>
///   <li>
///     <code>.xlfacility</code>: Forwarded to the xlfacility.
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsLogDestination, "LogDestination", open) {
/// Logs are printed to the Xcode debugger console.
  AIBudsLogDestinationConsole = 0,
/// Logs are routed through <code>os_log</code> for system-wide visibility.
  AIBudsLogDestinationOslogger = 1,
/// Logs are written to a specified file on disk.
  AIBudsLogDestinationFile = 2,
/// Logs are forwarded to the xlfacility.
  AIBudsLogDestinationXlfacility = 3,
};

/// The severity levels used by AIBudsLog.
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsLogLevel, "LogLevel", open) {
/// The most detailed level, used for tracing execution flow.
  AIBudsLogLevelVerbose = 0,
/// Detailed diagnostic information, useful during development.
  AIBudsLogLevelDebug = 1,
/// General informational messages that highlight progress.
  AIBudsLogLevelInfo = 2,
/// Potentially harmful situations that may require attention.
  AIBudsLogLevelWarn = 3,
/// Error events that might still allow the application to continue.
  AIBudsLogLevelError = 4,
/// Critical errors that may cause the application to terminate.
  AIBudsLogLevelFatal = 5,
/// A special level that disables all logging output.
  AIBudsLogLevelMute = 2147483647,
};

/// The error codes used for AIBudsLogSDK errors
typedef SWIFT_ENUM_NAMED(NSInteger, AIBudsLogSdkErrorCode, "SdkErrorCode", open) {
/// Unknown error
  AIBudsLogSdkErrorCodeUnknown = -1,
/// Invalid parameter
  AIBudsLogSdkErrorCodeInvalidParameter = 1,
/// The current log destination does not support log export.
  AIBudsLogSdkErrorCodeDestinationNotSupportExport = 1001,
/// The current log destination plugin is not configured.
  AIBudsLogSdkErrorCodeDestinationPluginNotConfigured = 1002,
/// The current log destination does not support log purge.
  AIBudsLogSdkErrorCodeDestinationNotSupportPurge = 1003,
/// The log root URL is not configured.
  AIBudsLogSdkErrorCodeLogRootUnavailable = 1004,
/// Failed to calculate cut-off time.
  AIBudsLogSdkErrorCodeFailedToCalculateCutOffTime = 1005,
/// Failed to enumerate log directories.
  AIBudsLogSdkErrorCodeFailedToEnumerateLogDirectories = 1006,
};

/// The protocol for plugins that record log messages to XLFacility.
SWIFT_PROTOCOL_NAMED("XLFacilityPlugin")
@protocol AIBudsXLFacilityPlugin <NSObject>
/// Indicates whether the plugin is loaded and ready to use.
@property (nonatomic, readonly) BOOL isLoaded;
/// Loads the plugin, initializing any necessary resources.
- (void)load;
/// Exports all log messages to a file.
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePath: The path to the exported log file, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
- (void)exportLogsWithCompletion:(void (^ _Nullable)(NSString * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Exports log messages to multiple files with size limit.
/// \param maxFileSize The maximum size of each log file in bytes.
///
/// \param completion The completion handler that is called when the export operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// filePaths: An array of paths to the exported log files, or nil if the export failed.
/// </li>
/// <li>
/// logStartFrom: The start timestamp of the export range.
/// </li>
/// <li>
/// logEndAt: The end timestamp of the export range.
/// </li>
/// <li>
/// error: The error object, or nil if the export operation was successful.
/// </li>
/// </ul>
///
///
- (void)exportLogsWithMaxFileSize:(uint64_t)maxFileSize completion:(void (^ _Nullable)(NSArray<NSString *> * _Nullable, NSDate * _Nullable, NSDate * _Nullable, NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified max age.
/// \param maxAge The maximum age in days for log messages to be retained.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsWithMaxAge:(NSInteger)maxAge completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Purges old log messages from the database that are older than the specified date.
/// \param timestamp The timestamp before which log messages should be purged.
///
/// \param completion The completion handler that is called when the purge operation is completed.
///
/// \a completion parameters:
/// <ul>
/// <li>
/// error: The error object, or nil if the purge operation was successful.
/// </li>
/// </ul>
///
///
- (void)purgeOldLogsBefore:(NSDate * _Nonnull)timestamp completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Records a log message.
/// \param message The content of the log to be recorded.
///
/// \param level The log level, used to distinguish the severity of the log.
///
/// \param subsystem Optional, identifies the subsystem to which the log belongs.
///
/// \param category Optional, identifies the category to which the log belongs.
///
- (void)logMessage:(NSString * _Nonnull)message level:(enum AIBudsLogLevel)level subsystem:(NSString * _Nullable)subsystem category:(NSString * _Nullable)category;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
